### ISSUE TITLE
Package required to build successfully

### ISSUE THREAD

**Issue by lucasgomide** [appsignal/appsignal-elixir#106]
After some attempts to deploy my app in production with AppSignal, so... I just figured out that the`build-essential` package is required to compiler the appsignal.

I'd suggest to add that's information into docs.

**Comment by tombruijn** [comment]
Thanks! We'll add it to the documentation

**Comment by tombruijn** [comment]
Installation instructions added in https://github.com/appsignal/appsignal-docs/commit/e91262424bb984142a2772e3b5f4055847324f1c
