### ISSUE TITLE
Move changelog to repo

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#111]
Right now we keep track of the changelog per release on the releases page: https://github.com/appsignal/appsignal-elixir/releases

Should we instead do the same as the ruby gem repo and keep a changelog file in the repo itself? (see https://github.com/appsignal/appsignal-ruby/blob/master/CHANGELOG.md) This way we standardize how we keep a changelog and make it more accessible (in my opinion) than the releases page

WDYT?

**Comment by jeffkreeftmeijer** [comment]
+1 on keeping it in line with the Ruby integration. I like having the tagged releases around, though (maybe we should link to the CHANGELOG from those?), so maybe we should introduce those on the Ruby side?
