### ISSUE TITLE
Samples are missing events

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#117]
Some samples seem to be missing events from the sample.

I can reproduce this in the [jeffkreeftmeijer/appsignal-phoenix-example](https://github.com/jeffkreeftmeijer/appsignal-phoenix-example) app. @jeffkreeftmeijer you can also find an example of this event timeline in your own test apps organization under the "appsignal_phoenix_example" app `dev` env.

![image](https://cloud.githubusercontent.com/assets/282402/22654290/9c87502a-ec8c-11e6-9768-909f17bbe55e.png)

The "dash"/"indenting line" before the event name shouldn't be there for the first event. Apparently there's an event above it we don't track?

This is how it should look:

![image](https://cloud.githubusercontent.com/assets/282402/22654557/672841c2-ec8d-11e6-954c-c308c519e343.png)

This sample event data comes from the agent, so there is something going wrong there.

We need to check and test to see if there's a scenario that crashes or breaks the transaction in some way that it misses events.

---

## Possibly related problem from the Ruby gem

We had a similar issue before in the Ruby gem for Sinatra apps where the transaction wasn't completed properly (it crashed), then a new request came in and transactions overlapped requests. That way the events that were monitored on one sample could be from one or more requests.

The PR that described that problem and fixed it: https://github.com/appsignal/appsignal-ruby/pull/145

The same probably occurs here: https://app.intercom.io/a/apps/yzor8gyw/inbox/all/conversations/7981810773

----

sorry if the description doesn't make a ton of sense, I'll try to expand on the problem later.

**Comment by jeffkreeftmeijer** [comment]
We're one step closer, but #118 didn't fix this issue completely.

**Comment by tombruijn** [comment]
Great! Looks like the direct parent is being captured better, but the top event is still missing. Could be that we don't track that yet?

![image](https://cloud.githubusercontent.com/assets/282402/22701970/7a9502ae-ed5f-11e6-8845-dc49d90aaa46.png)
