### ISSUE TITLE
(ArithmeticError) bad argument in arithmetic expression

### ISSUE THREAD

**Issue by alanpeabody** [appsignal/appsignal-elixir#13]
Hi folks, giving AppSignal a try for some elixir apps, however I noticed when I installed in and included the Ecto log hook I am getting an ArithmeticError coming from https://github.com/appsignal/appsignal-elixir/blob/master/lib/appsignal/ecto.ex#L28 on all of my previously working POST/PUT requests (even in tests). 

Removing the logger in the Repo config removes all errors.

It appears to raise this error on any Repo.update, Repo.insert, and Repo.update_or_insert when passed a changeset. 

Is this possibly a version issue? 

I tried running Appsignal 0.2.0 and master with Ecto 2.0.4, phoenix_ecto 3.0.1, db_connection 1.0.0-rc.5, postgrex 0.11.2.

**Comment by arjan** [comment]
Thanks for the report! I'll have a look at what this causes.

**Comment by arjan** [comment]
Found it, it turned out [Ecto.LogEntry](https://hexdocs.pm/ecto/Ecto.LogEntry.html)'s time fields could be `nil`.

**Comment by alanpeabody** [comment]
Awesome, thanks @arjan !

**Comment by aboatswain** [comment]
this seems to still be happening

**Comment by tombruijn** [comment]
Hi @aboatswain, we've not had a report about this in a long time. Can you give us some details about the issue you're running into and let us know at support@appsignal.com ?
