### ISSUE TITLE
mix notify_of_deploy

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#139]
As a first step in providing deploy notifications, we'll implement a mix task like [the `notify_of_deploy` Rake task in the Ruby integration](http://docs.appsignal.com/ruby/command-line/notify_of_deploy.html).

**Comment by raytalks** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/rayta@appsignal.com/conversations/8795614465

**Comment by tombruijn** [comment]
Will be fixed in: https://github.com/appsignal/appsignal-docs/issues/93

**Comment by tombruijn** [comment]
Closing this issue.

Short story: We will not support a `mix notify_of_deploy` task for Elixir.

Longer story: We've reviewed how we're registering deploys and are favoring a (previously less well documented) method using the `APP_REVISION` environment variable. With the `APP_REVISION` environment variable you can configure the current version/revision of an application instance. This means that when running multiple instances you can also run multiple versions/revision and the errors and performance issues will continue to be reported under the version they are running.

For more information about this please see our (new) documentation page for deploy markers: http://docs.appsignal.com/application/markers/deploy-markers.html

If you don't want to use `APP_REVISION` you can also still send us a request with the deploy marker manually with something like curl, as (also) documented here: http://docs.appsignal.com/application/markers/deploy-markers.html
