### ISSUE TITLE
Plug support without Phoenix

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#153]

**Comment by cbarratt** [comment]
This feature sounds great and will be awesome. I'm currently trying to gauge whether or not I can at the very least get errors from including AppSignal in my Plug application?

**Comment by jeffkreeftmeijer** [comment]
Hey @cbarratt! :wave:

AppSignal will report errors for crashes out of the box. However, as Ranch catches them before the process crashes, you’ll need to explicitly catch errors thrown inside your Plug application. The new [`Appsignal.Plug` module](https://github.com/appsignal/appsignal-elixir/blob/plug/lib/appsignal/plug.ex) will do that for you by starting a transaction for each request, running the action, catching errors if they occur, and finishing the transaction to be sent to AppSignal.

Since all that work needs to be done to get an error from your Plug app into AppSignal, there's currently no easier way to do this. That's why we're working on separating our Phoenix support from the Plug parts. 

We have a working version of our new `Appsignal.Plug` module in the [plug branch](https://github.com/appsignal/appsignal-elixir/tree/plug), which we're currently testing. Although it’s not production ready yet, it’d be great if you could take it for a spin to see if you run into any issues using it in your application.
