### ISSUE TITLE
Dialyzer errors

### ISSUE THREAD

**Issue by suhrawardi** [appsignal/appsignal-elixir#165]
Appsignal-Elixir in a Phoenix project causes the following Dialyzer errors:

In `lib/my_app/endpoint.ex`:
```
 defmodule MyApp.Endpoint do                                            
                                                                                 
   use Appsignal.Phoenix # On line 51                                                    
                                                                                 
   plug MyApp.Router                                                    
 end   
```
When running `mix dialyzer` I get the following errors:
```
lib/hue_labs_backend/endpoint.ex:51: The pattern 'true' can never match the type 'false'
lib/hue_labs_backend/endpoint.ex:51: The test 'nil' | 'no_sample' == 'sample' can never evaluate to 'true'
```

```
* phoenix 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (phoenix) 6dc59224
  ok
* appsignal 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (appsignal) eb030975
  ok
```

Thanks!

**Comment by jeffkreeftmeijer** [comment]
Hey @suhrawardi! We'll go over the Dializer warnings in the integration, and we'll work on making sure we won't add any warnings to your application in an upcoming version of the integration. Thanks for opening this issue!

**Comment by suhrawardi** [comment]
Thanks a lot!! @jeffkreeftmeijer and @tombruijn

**Comment by RobinClowers** [comment]
Any word on this? I just ran into this when upgrading to 1.2.3. I also tried beta 1.3.0-beta.2, but it still has the issue as well.

**Comment by thijsc** [comment]
@jeffkreeftmeijer who was working on this is on holiday at the moment, he'll be working on this again next week.
