### ISSUE TITLE
Move environment to string rather than atom?

### ISSUE THREAD

**Issue by stevedomin** [appsignal/appsignal-elixir#17]
Right now the environment is set with the following config:

```
config :appsignal, :config,
  name: :my_first_app,
  push_api_key: "your-hex-appsignal-key",
  env: :prod
```

I'm interested to understand if there is any reason for not making the environment a string rather than an atom. At the moment it prevents using anything else than `:prod`, `:test` or `:dev`. I'd really like to set it to `staging` for instance.

**Comment by arjan** [comment]
The reason is that `Mix.env` also returns an atom. But I don't think there is a reason you cannot put `:staging` there; you can put any atom there, it will be converted to a string when sent to Appsignal.

**Comment by stevedomin** [comment]
@arjan yes but that prevents you from using an environment variable other than `APPSIGNAL_ENVIRONMENT`.

`Mix.env` is almost always going to be `:prod` I think as far as Elixir is concerned it's considered more like a build env rather than a deployment environment.

That's why I have an other environment variable `APP_ENV` which is set to `production`, `staging`, `qa`, etc. based on the environment the app is running on. Ideally I'd like to reuse the same env variable but I can't currently because that would mean converting the string to an atom in the config:

```
config :appsignal, :config,
  name: :my_first_app,
  push_api_key: "your-hex-appsignal-key",
  env: System.get_env("APP_ENV") |> String.to_atom
```

Unfortunately hat would fail to compile in some environment due to APP_ENV being `nil` (when developing on my laptop or building the slug on Heroku). Plus it's not very clean.

**Comment by arjan** [comment]
Yes and above fix would do this at compile time instead of runtime.
Phoenix supports a syntax like:
```
env: {:system, "APP_ENV"}
```
PR's welcome :-)
