### ISSUE TITLE
Add ability to track error-level logs

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#172]
When a log message is written with the log level "error" we can record this as an error in AppSignal as well. Erlang has an error_logger report_handler where we can register a error logger handler.

We could add this and turn it on by default or make it a configuration option.

WDYT?

http://erlang.org/doc/man/error_logger.html#add_report_handler-2
https://app.intercom.io/a/apps/yzor8gyw/inbox/conversation/8713666221

**Comment by arjan** [comment]
[This is already done](https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal.ex#L28), right?

**Comment by tombruijn** [comment]
Hmm okay.. That's odd, I don't actually get this working when using `Logger.error "foo"`
No error is reported on AppSignal.com

**Comment by arjan** [comment]
Yes well, Elixir's `Logger` is not tied up to Erlang's, it's the other way around.

Handling `Logger.error` events requires writing an Elixir logger backend, see the [Custom backends section](https://hexdocs.pm/logger/Logger.html) of the Elixir docs.

Maybe it's best to rename this ticket :)

**Comment by tombruijn** [comment]
Closing. If a user wants to report an error to AppSignal they should use `Appsignal.set|send_error`. We're not going to build an integration for the Logger to capture `error`-level log messages.
