### ISSUE TITLE
Detect if instrumentation is set up correct

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#178]
In the Ruby gem we log to appsignal.log when certain instrumentation becomes active. See https://github.com/appsignal/appsignal-ruby/blob/559d32b73e7b4032f3966549c4fbb3dd55c6c6e7/lib/appsignal/integrations/padrino.rb#L6

We should research if we can do the same for the AppSignal.Phoenix module, Phoenix instrumentor, Phoenix template instrumentation and Ecto instrumentation.

**Comment by tombruijn** [comment]
Related: https://github.com/appsignal/appsignal-agent/issues/346

**Comment by jeffkreeftmeijer** [comment]
We’ve added log output in https://github.com/appsignal/appsignal-elixir-plug/commit/f06ffc475dbe152aed5735864861d11915b69f81, which prints an INFO log line whenever the `Appsignal.Plug` module is included in a Plug endpoint.
