### ISSUE TITLE
Check whether Elixir sends the same request headers as Ruby gem does

### ISSUE THREAD

**Issue by arjan** [appsignal/appsignal-elixir#18]
HTTP_ACCEPT _/_
HTTP_ACCEPT_ENCODING    gzip, deflate
HTTP_CONNECTION close
HTTP_USER_AGENT Twitterbot/1.0
HTTP_X_FORWARDED_FOR    199.16.156.125

**Comment by thijsc** [comment]
What do you want to add these errors to?

**Comment by arjan** [comment]
I am not sure anymore. I saw that some request headers were missing.

**Comment by arjan** [comment]
We should just send all headers, discussed this with @thijsc . Creating new issue for it.
