### ISSUE TITLE
ignore Ecto.NoResultsError 

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#181]
From [support](https://app.intercom.io/a/apps/yzor8gyw/inbox/elixir/conversations/8790049685) (intercom link):

> Hi we use elixir/phoenix and appsignal. Right now i'm getting EctoNoResultsError polluting our appsignal UI. By default EctoNoResultsError returns a 404 and is not a typical exception. How can i disable this being sent to appsingal?

**Comment by tombruijn** [comment]
I don't think we should do this: ignoring errors by default for the user. Could a user unset this default somehow if we would?

@arjan you had some thoughts about this?

**Comment by tombruijn** [comment]
We won't ignore this error, because it might be relevant in some scenarios.
We should update the docs for something like how we do it in Rails:

```ruby
rescue_from ActiveRecord::RecordNotFound, :with => :not_found
```

**Comment by tombruijn** [comment]
Continued in https://github.com/appsignal/appsignal-docs/issues/128
