### ISSUE TITLE
Decorated functions running in linked processes don't get instrumented

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#188]
[Decorated](http://docs.appsignal.com/elixir/instrumentation/instrumentation.html#function-decorators) functions don't get instrumented into the current transaction.

In this example, the call to `decorated/0` should be instrumented, but since the pid of the process is [different from the one used to start the transaction](https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal/instrumentation/decorators.ex#L75), the event is not added to the current transaction.

``` elixir
  def decorator(conn, _params) do
    task = Task.async(fn -> decorated() end)
    time = Task.await(task)

    text conn, "Slept for #{time}ms."
  end

  @decorate transaction_event()
  defp decorated do
    time = :rand.uniform(3000)
    :timer.sleep(time)
    time
  end
```

https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540654/conversations/11300982245

**Comment by arjan** [comment]
How would you define "subprocesses"?

**Comment by xymbol** [comment]
@jeffkreeftmeijer Have you tried passing in the caller's process identifier?

```elixir
defmodule Blog.PostController do
  use Blog.Web, :controller

  def index(conn, _params) do
    pid = self()
    
    task = Task.async(fn ->
      instrument(pid, "task.posts", "Running important task", fn ->
        # ...
      end)
    end)
    Task.await(task)
    
    render conn, "index.html"
  end
end
```

Passing in a pid to `instrument/4` should trigger a transaction lookup.

**Comment by jeffkreeftmeijer** [comment]
@arjan @xymbol this is specifically about decorated functions being called from a process that's [different from the one that started the transaction](https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal/instrumentation/decorators.ex#L75). In that case, the event is not added to the current transaction. I've updated this issue's title and description.

**Comment by arjan** [comment]
A process has no way of knowing its "parent process", as there is no such concept in Erlang.
When you want to use decorators (which use the pid to lookup the current transaction), you need to make a way of letting the "subprocess" know its transaction. 
The reference to the transaction could be stored twice in the transaction registry ETS table, I think. However, you will have to deal with concurrency issues, you don't want the transaction to be closed multiple times or events to be coming in after the transaction has finished.

I would just call `Appsignal.TransactionRegistry.register/1` with the transaction of the "parent" process. The function which should be called as (one of) the first things in the Task, and which adds an ETS entry.

**Comment by xymbol** [comment]
@jeffkreeftmeijer I see, yes. In that case, I would not expect decorated functions to work. I would pass it and do explicit instrumentation as in the second example.

**Comment by tombruijn** [comment]
Relevant (private) issue: https://github.com/appsignal/appsignal-server/issues/2589
