### ISSUE TITLE
Limit number of records sent to Appsignal

### ISSUE THREAD

**Issue by sorliem** [appsignal/appsignal-elixir#189]
Hello,

I was wondering if there was a way to limit the number of requests sent to Appsignal? For example, send every 10th request from each controller to Appsignal, but still send all errors. I know there is the option to ignore certain controller actions, but that is not ideal.

I want to keep using Appsignal, but my projected usage would be too high for me to sign up for a paid plan. Thanks.

**Comment by tombruijn** [comment]
I see we already answered this through our support channel :)
