### ISSUE TITLE
Agent always starting in prod env

### ISSUE THREAD

**Issue by arjan** [appsignal/appsignal-elixir#2]
When used as hex package, it seems that the agent always picks prod as the environment, and does not take `MIX_ENV` into account.

**Comment by robvandenbogaard** [comment]
Thanks for opening the issue. Maybe good to know that the agent does log "[debug] Appsignal starting." when starting the phoenix server.

**Comment by arjan** [comment]
Yes this `[debug]` is not to be confused with the environment; it is the log level. 

(on an unrelated note: `debug` log messages will not show when `MIX_ENV=prod`)

**Comment by arjan** [comment]
Mix dependencies seem to be always compiled with `Mix.env == :prod`. This makes it hard to determine the actual application's environment on compile time.

A runtime config variable (in e.g. `config/prod.exs`) seems to be the only solution:

```elixir
    config :appsignal, :config,
      env: :prod
```

where `:env` would default to `:dev`.

**Comment by robvandenbogaard** [comment]
Wow, so it is an Elixir thing, hmm, aha it seems it's also intended behaviour: https://github.com/elixir-lang/elixir/issues/4119

**Comment by arjan** [comment]
Yep. Seems quite logical now that I think of it. A library could have many dev dependencies which you wouldn't need as a user of the library.
I'll implement the config variable like above.
