### ISSUE TITLE
🚀 Configuration option for `APP_REVISON`

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#215]
We removed the config for the `APP_REVISON` config in https://github.com/appsignal/appsignal-elixir/pull/154

Not sure if we can't add this option now. Would make for a nice way to standardize all the AppSignal configuration, as it currently is the only config var that you can only set with an env var.

The problem with automatically setting the project version as the revision, is that our integration with GitHub relies on the revision being a existing git reference on the linked repository. So to use the project version as the revision and use the GitHub integration we need users to tag their project versions in git.

```
git tag v1.0.1
```

```elixir
# config/appsignal.exs
config :appsignal, :config, revision: "v1.0.1"
# or linked with the project version
config :appsignal, :config, revision: "v#{Mix.Project.config[:version]}"

# mix.exs
def project do
  [app: :appsignal_phoenix_example,
   version: "1.0.1"]
end
```

Asked in: https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/tom@appsignal.com/conversations/9047619500

**Comment by thijsc** [comment]
I just had a conversation with a customer about using the Erlang package revision feature we removed. For him this is a great feature. As part of their deploy process they tag the released sha with this version number. We then used to pick up on this and everything worked out of the box.

I think we should revert this pull and add the functionality back in. If APP_REVISION is set it should override, but at least we can take this as the default. We could document that we expect people to tag their releases in Git if they want to use this.

**Comment by thijsc** [comment]
So in the context of this issue: I think we should add a revision config option. Then first fill it from the package revision, then overwrite it with `APP_REVISION` if present.

**Comment by doughsay** [comment]
sooo... just to be clear:  is it currently only possible to set the revision using the env var?  Or can I use the above config snippet in my config.exs?

**Comment by tombruijn** [comment]
@doughsay yes, it's currently only possible to use the env var. We're thinking of adding support back for a config option, but the automatic link between the AppSignal revision and mix project version will probably confuse people so we haven't added it yet.

**Comment by doughsay** [comment]
@tombruijn thanks for the update.  I'll try and get it working on my end with the env var, but for what it's worth, I would also vote for adding the config option back in some form.  Thanks!

**Comment by Wijnand** [comment]
I would love to be able to use the Erlang package revision again as well.

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540709/conversations/15281931450
