### ISSUE TITLE
Front End monitoring support

### ISSUE THREAD

**Issue by suhrawardi** [appsignal/appsignal-elixir#220]
We would love to make use of the Front End monitoring support for our Elixir app. 
Are there any plans to get support for it into this Elixir package? Or will it be a separate Hex package?

Thx!

**Comment by jeffkreeftmeijer** [comment]
Hey @suhrawardi,

Thanks for putting this on the radar. We’re getting ready to continue work on this in the Ruby integration. After that’s done, we’re planning on adding front end monitoring to the Elixir integration too. However, we’re not sure how long that’s going to take, and how it’ll be implemented. We’ll use this issue to keep you posted on our progress on this, though!

Thanks again!

**Comment by viniciussbs** [comment]
I'm planning to use AppSignal on my Ember app, too.

The Ruby integration has an [Rack middleware to receive error messages](https://github.com/appsignal/appsignal-ruby/blob/master/lib/appsignal/rack/js_exception_catcher.rb) from a front-end app and to forward them to AppSignal's endpoint - using a specific [transaction class for front-end errors](https://github.com/appsignal/appsignal-ruby/blob/master/lib/appsignal/js_exception_transaction.rb).

Are you planning to support Elixir with front-end integration during the beta or only when the integration is production-ready?

**Comment by tombruijn** [comment]
I've created a separate package for front-end monitoring with AppSignal for Elixir: https://github.com/tombruijn/appsignal-elixir_js_plug
You can use that until we review and rework our JS support for both Ruby and Elixir.
Let me know on that repo if you experience any problems with the Appsignal.JSPlug
