### ISSUE TITLE
Disable gracefully on Windows

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#224]
Instead of crashing while trying to compile, AppSignal should install and be able to run the mix tasks. The integration itself should always be disabled.

**Comment by eteeselink** [comment]
I would like to add that, even when the `active` config param is set to `false`, appsignal shows this error in a windows dev environment:

```
**warning: Error loading NIF (Is your operating system (win32) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
Failed to load NIF library c:/code/talkjs/backend/_build/test/lib/appsignal/priv/appsignal_extension: 'The specified module could not be found.'
  (appsignal 1.10.13) lib/appsignal/nif.ex:48: Appsignal.Nif.init/0
  (kernel 6.5.1) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
```

There's no noticeable effect, which is good, but it's still sloppy that an error is shown when nothing is the matter. It doesn't match the "safe, robust" emotion that AppSignal is trying to broadcast. Would it be possible to just not try to load the nif if AppSignal isn't marked active? Or, just move the error to Nif.start() somehow?

**Comment by jeffkreeftmeijer** [comment]
Hey @eteeselink,

Sorry for being so slow to respond to this one. Currently, we do try to load the Nif, but we don’t actually create the spans, so the Nif’s functions aren’t actually called. I’ve opened a new issue in #635, to track this.

Thanks for verifying compilation now completes on Windows. I’m closing this one in favor of #635.
