### ISSUE TITLE
Officially support Elixir 1.5

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#237]
Officially support Elixir 1.5 now that it's released: https://elixir-lang.org/blog/2017/07/25/elixir-v1-5-0-released/

- [x] Add Elixir 1.5 to the test matrix in TravisCI
- [ ] Add OTP 20 to the test matrix on TravisCI
- [x] Fix anything that might be broken

**Comment by blatyo** [comment]
I had to completely remove instrumentation for channels for them to not raise a runtime error. I was using `@decorate channel_action()`

```
** (EXIT from #PID<0.2362.0>) an exception was raised:
         ** (RuntimeError) Expected `handle_in/3` to return one of:

         {:noreply, Socket.t} |
         {:reply, {status :: atom, response :: map}, Socket.t} |
         {:reply, status :: atom, Socket.t} |
         {:stop, reason :: term, Socket.t} |
         {:stop, reason :: term, {status :: atom, response :: map}, Socket.t} |
         {:stop, reason :: term, status :: atom, Socket.t}

     got [do: {:reply, :ok, %Phoenix.Socket{}}]
```
socket was abbreviated

**Comment by arjan** [comment]
Yes the `decorator` package needs to be at least on version 1.2.2 to support Elixir 1.5 properly.

**Comment by tombruijn** [comment]
@jeffkreeftmeijer can we close this issue now that #248 is merged?

**Comment by jeffkreeftmeijer** [comment]
We have some test failures on OTP 20 we should fix before we can close this.
