### ISSUE TITLE
Transaction is not using request id as an id

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#239]
The transaction is not using a request's request id when the Plug.RequestId is being used.
The `Logger.metadata()` is empty when it's called here https://github.com/appsignal/appsignal-elixir/blob/a8550ee6efdc935a8059e0807756a72d65d8616e/lib/appsignal/plug.ex#L12

which means it's always generating a new transaction id which means that users cannot connect the request id from their logs to AppSignal transactions.

As reported in: https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540709/conversations/11076180555

**Comment by dbhobbs** [comment]
Is this still an issue? It looks like it may have been fixed in v1.4.4.

**Comment by jeffkreeftmeijer** [comment]
Hey @dbhobbs,

You're right! This was fixed in https://github.com/appsignal/appsignal-elixir/commit/adbf0d1a0fa708569a6540a12f5e381caa99bfc9, and this issue is a dupe. Thanks for the reminder! :)
