### ISSUE TITLE
Drop Phoenix dependency

### ISSUE THREAD

**Issue by tomasz-tomczyk** [appsignal/appsignal-elixir#24]
I'm not very familiar with how Elixir dependancies work and if they add bloat, so this may be a non-issue but wondering why is Phoenix a dependency? Should it only be if I'm including AppSignal on a Phoenix app?

**Comment by arjan** [comment]
Right now we have been focussing on Phoenix, but you're right, Phoenix should not be a dependency of Appsignal. Although there is Phoenix-specific code in the library (mostly integrations), it should be be perfectly possible to use it separately from Phoenix. I'll see if I can remove the dependency in the next release.

**Comment by teamon** [comment]
@arjan You could use optional dependencies like e.g https://github.com/teamon/tesla/blob/master/mix.exs#L47 and then conditionally compile phoenix-only modules if phoenix is present - https://github.com/teamon/tesla/blob/master/lib/tesla/adapter/hackney.ex#L1

**Comment by arjan** [comment]
That's a good idea, thanks! I'll see if I can make it work using this approach.
