### ISSUE TITLE
Set channel payload from `Appsignal.Phoenix.Channel.channel_action/4`

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#243]
Right now, [`Appsignal.Phoenix.Channel.channel_action/4`](https://github.com/appsignal/appsignal-elixir/blob/a8550ee6efdc935a8059e0807756a72d65d8616e/lib/appsignal/phoenix/channel.ex#L51-L69) doesn't include the channel payload. 

To include the payload, we need to add `channel_action/5`, which takes the payload and uses `Appsignal.Utils.ParamsFilter` to filter out sensitive data.

**Comment by jeffkreeftmeijer** [comment]
https://app.intercom.io/a/apps/yzor8gyw/respond/inbox/540654/conversations/10967655373

**Comment by tombruijn** [comment]
See also: https://github.com/appsignal/appsignal-elixir/issues/232

**Comment by tombruijn** [comment]
@jeffkreeftmeijer since this hasn't been fixed yet by #255, but we'll solve it with Phoenix instrumenters, I'll disconnect issue #255 and move this to the backlog.

**Comment by jeffkreeftmeijer** [comment]
We allow passing channel params through [`Appsignal.Phoenix.Channel.instrument/5` in 2.x](https://github.com/appsignal/appsignal-elixir-phoenix/blob/9888c85b3cf9cd5babcaca4b2428e677c58685bf/lib/appsignal_phoenix/channel.ex#L38-L70).
