### ISSUE TITLE
Support/Upgrade to Phoenix 1.3 

### ISSUE THREAD

**Issue by mbenatti** [appsignal/appsignal-elixir#244]
Hi guys, how are the support for the phoenix 1.3?
I tried to run it with my phoenix 1.3 project, but I need to fix the deps.

```
$ mix test
Unchecked dependencies for environment test:
* phoenix (Hex package)
  the dependency phoenix 1.3.0

  > In mix.exs:
    {:phoenix, "~> 1.3.0", [env: :prod, repo: "hexpm", hex: "phoenix", manager: :mix]}

  does not match the requirement specified

  > In /home/marcos/xxx/deps/appsignal/mix.exs:
    {:phoenix, "~> 1.2.0", [env: :prod, hex: "phoenix", repo: "hexpm", optional: true]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies

```

**Comment by tombruijn** [comment]
Hi @mbenatti !

We support Phoenix 1.3. What version of the AppSignal for Elixir package are you using?
Try upgrading to our latest 1.3.0 package `mix deps.update appsignal` and let me know if that fixes it.

**Comment by mbenatti** [comment]
@tombruijn I don't think so because you have `{:phoenix, ">= 1.2.0", optional: true, only: [:prod, :test_phoenix, :dev]}` in your mix.exs, changing to `{:phoenix, ">= 1.2", optional: true, only: [:prod, :test_phoenix, :dev]}` or `:phoenix, "~> 1.2"` can fix that

**Comment by mbenatti** [comment]
@tombruijn fixed updating, thanks!

**Comment by tombruijn** [comment]
Great! Thanks for reporting back
