### ISSUE TITLE
Build version with appsignal elixir

### ISSUE THREAD

**Issue by nulian** [appsignal/appsignal-elixir#250]
Since a long time our build version doesn't update on deploys anymore with app_signal and elixir.

I was wondering how app signal determines what version you are using. So I can debug why app_signal isn't updating release versions anymore.

**Comment by jeffkreeftmeijer** [comment]
Hey @nulian,

You can let us know about deploys though our [deploy markers](https://docs.appsignal.com/application/markers/deploy-markers.html). 

If you're talking about your app's revision (`Mix.Project.config[:version]`): we used to recommend setting a `:revision` in your appsignal configuration. We removed support for that in #154, as the deploy marker logic on the server side was only intended for git commit SHAs. We have been discussing bringing it back in #215, but we haven't gotten around to doing so.

**Comment by tombruijn** [comment]
Closing in favor of #215
