### ISSUE TITLE
Appsignal.Plug.extract_action captures too many requests

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#264]
The following function captures all asset routes for example, but it also catches all Absinthe requests. It doesn't set an action name, which makes the transaction invalid. And then the transaction won't be sent to AppSignal.

https://github.com/appsignal/appsignal-elixir/blob/909054d77584d49f1997ae55a2337ddb56c185f3/lib/appsignal/plug.ex#L76

A workaround for this scenario is to set the action name manually, like I did for Absinthe with this plug:

```elixir
defmodule AppsignalAbsinthePlug do
  @transaction Application.get_env(:appsignal, :appsignal_transaction, Appsignal.Transaction)

  def init(_), do: nil

  def call(%Plug.Conn{request_path: "/graphql", method: "POST"} = conn, _) do
    @transaction.lookup_or_create_transaction(nil, :http_request)
    |> @transaction.set_action("POST /graphql")

    conn
  end

  def call(conn, _) do
    conn
  end
end

# And then use that plug somewhere. I did so in the `lib/my_app/endpoint.ex` file.
use Appsignal.Phoenix
plug AppsignalAbsinthePlug
```

**Comment by tombruijn** [comment]
We weren't able to fix this today. We need have a good way to match assets. The Plug.Static plug gets config options we can't read from our plug. And we need to match against those options:

https://github.com/elixir-plug/plug/blob/37f60bc9d818554635c230632df5444392166f68/lib/plug/static.ex#L154-L158

https://github.com/elixir-plug/plug/blob/37f60bc9d818554635c230632df5444392166f68/lib/plug/static.ex#L187-L191

**Comment by jeffkreeftmeijer** [comment]
Since 2.0, we’re [setting the action name](https://github.com/appsignal/appsignal-elixir-plug/blob/main/lib/appsignal_plug.ex#L150-L152) by taking the matched route, meaning actions without names is no longer an issue.
