### ISSUE TITLE
Query Logging: Appsignal.Ecto.log/1 errors when using the preferred Ecto.Repo loggers format

### ISSUE THREAD

**Issue by wheels** [appsignal/appsignal-elixir#27]
From the Ecto docs:

`:loggers` - a list of `{mod, fun, args}` tuples...

https://hexdocs.pm/ecto/Ecto.Repo.html

In Ecto 2.0.2, when I add Appsignal to Repo loggers using the preferred format

`loggers: [{Appsignal.Ecto, :log, []}]` 

it throws an error here:

https://github.com/appsignal/appsignal-elixir/blob/master/lib/appsignal/ecto.ex#L29

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.queue_time/0 is undefined or private
        nil.queue_time()
        (appsignal) Appsignal.Ecto.log/1
```

**Comment by arjan** [comment]
Sorry, I can't seem to reproduce this. Are you using the latest version? It seems the LogEntry that's passed in is `nil`..

I also don't see how this variant could cause the error, [they look pretty similar](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex#L98). Are you doing something special? e.g. when there is another logger that does not return the `entry` value back, the next logger function could crash.

**Comment by wheels** [comment]
It only happens in prod for me. I'm passing in other loggers as well so it looks like this:

`loggers: [{Ecto.LogEntry, :log, []}, {MyApp.Repo.Metrics, :record_metric, []}, {Appsignal.Ecto, :log, []]

**Comment by arjan** [comment]
You should check whether your `record_metric` function returns the log entry.

**Comment by wheels** [comment]
Ah, nice catch. Didn't realize each one affected subsequent calls.

**Comment by arjan** [comment]
NP! I also just realised this by looking at Ecto's source.
