### ISSUE TITLE
Dialyzer: Expression produces a value of type 'nil'

### ISSUE THREAD

**Issue by xanderdunn** [appsignal/appsignal-elixir#276]
AppSignal 1.4.0
Elixir 1.5.1
dialyxir 0.5.1

Dialyzer output:
```
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/local/dev/api-tournament/_build/dev/lib/dialyxir/plt_file.plt',
 files_rec: ['/local/dev/api-tournament/_build/dev/lib/api_tournament/ebin'],
 warnings: [:unmatched_returns]]
done in 0m4.42s
lib/endpoint.ex:11: Expression produces a value of type 'nil' | #{'__struct__':='Elixir.Appsignal.Transaction', 'id':=_, 'resource':=_}, but this value is unmatched
done (warnings were emitted)
```

Although it's working locally, we can't merge appsignal to our master branch for deployment because of this warning.

The line `use Appsignal.Phoenix` is the cause of the warning.  Otherwise, dialyzer passes.

**Comment by tombruijn** [comment]
Hi @xanderdunn,

We're working on fixing all the dialyzer warnings in PR #271 .
Can you try that branch in your app and tell us if the warning disappears?

```elixir
# mix.exs
defp deps do
  [
    # your deps here
    {:appsignal, git: "https://github.com/appsignal/appsignal-elixir.git", ref: "dialyzer"}
  ]
end
```

I wouldn't recommend running it with that branch just yet, so don't deploy it to production

**Comment by tombruijn** [comment]
The Dialyzer PR is merged and should fix this problem. Will most likely ship in the next minor release, v1.5.
