### ISSUE TITLE
Create working_dir_path if required

### ISSUE THREAD

**Issue by Nicd** [appsignal/appsignal-elixir#278]
It would be nice if AppSignal could create the `working_dir_path` before it starts if it doesn't exist.

For example, to have multiple instances running on my server, I use `working_dir_path: "/tmp/appsignal-codestats-prod/"`, but I have to set up creation of that path myself or AppSignal will die since it doesn't exist. It would be easier to set up if it could attempt `File.mkdir_p(path)` before giving up.

**Comment by jeffkreeftmeijer** [comment]
Hey @Nicd! :wave:

Thanks for putting this back on the radar. We've been planning to fix this in the agent, and we'll update this ticket when we have a release of the Elixir package that uses a new version of the agent that makes sure to create the working_dir_path if it doesn't exist yet. We'll be in touch!

**Comment by tombruijn** [comment]
Will be fixed in #363 and shipped in 1.8
