### ISSUE TITLE
(UndefinedFunctionError) function Appsignal.System.agent_platform/0 is undefined or private

### ISSUE THREAD

**Issue by suhrawardi** [appsignal/appsignal-elixir#288]
Hi,

After updating appsignal-elixir from 1.3.5 to 1.4.5 I get this error message while doing a deployment:
```
remote: could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
remote: ==> appsignal
remote: ** (UndefinedFunctionError) function Appsignal.System.agent_platform/0 is undefined or private
remote:     Appsignal.System.agent_platform()
remote:     mix_helpers.exs:12: Mix.Appsignal.Helper.verify_system_architecture/0
remote:     /tmp/build/deps/appsignal/mix.exs:17: Mix.Tasks.Compile.Appsignal.run/1
remote:     (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
remote:     (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
remote:     (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
remote:     (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
remote:     (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
```

We use Herokuish on Ubuntu with these build packs:
https://github.com/HashNuke/heroku-buildpack-elixir.git                         
https://github.com/gjaldon/heroku-buildpack-phoenix-static.git 

```
cat elixir_buildpack.config
 erlang_version=20.1                                                             
 elixir_version=1.5.2                                                            
 always_rebuild=false                                                            
 runtime_path=/app 

cat phoenix_static_buildpack.config
 phoenix_relative_path=apps/app-name                                     
 assets_path=../../assets                                                        
 phoenix_ex=phx  
```

Please let me know what else you want to know... :-)

Any ideas how to fix this?
Thx!

**Comment by tombruijn** [comment]
Hi @suhrawardi ,

We've seen this happen before such as in #284, and I'm not sure why it keeps happening, but could you try running `mix deps.clean appsignal`?

**Comment by suhrawardi** [comment]
Thanks @tombruijn, I overlooked #284.

`mix deps.clean appsignal` indeed fixes it, but is a bit awkward. We hacked the _heroku-buildpack-elixir_ to make it work for us. :-)

Thx!

**Comment by tombruijn** [comment]
Good to hear it's working. I'll close this issue for now. Yes it's a bit awkward. We'll look into it.

**Comment by fdietz** [comment]
I just ran into the same issue, while deploying to Heroku. Any news on this? 

I'm pretty new to Heroku buildbacks and would rather wait for an official fix.

**Comment by jeffkreeftmeijer** [comment]
Hey @fdietz,

Thanks for letting us know about this. We've been looking into this today, and we're testing a patch for this internally as we speak. We're hoping to get that out to you soon. 

Am I correct you're trying to update from a version before 1.4.3? If so, there's a problem recompiling some of the required files, which can be fixed by running `mix deps.clean appsignal`. Using the Heroku buildpack, you can [configure](https://github.com/HashNuke/heroku-buildpack-elixir#configuration) the build process to rebuild everything on every deploy by putting `always_rebuild=true` in a  file named `elixir_buildpack.config` in your project root. Once you're upgraded to a version above 1.4.3, you should be able to remove this configuration again.

We'll update this issue when we have more news about this.

**Comment by fdietz** [comment]
Hi @jeffkreeftmeijer!

I was updating from version 1.3.5. 

The steps you describe by changing the buildpack configuration seem easy to do. I will give this a try and will report back to you tomorrow. 

Thank you so much for your assistance!

**Comment by jeffkreeftmeijer** [comment]
We've merged a fix for this, and will be releasing it as part of 1.5.0-beta.1 as soon as possible. Once upgraded to that, you should be able to upgrade to new versions without having to rebuild manually.

**Comment by jeffkreeftmeijer** [comment]
We released version 1.5.0-beta.1 of the AppSignal for Elixir integration last week, which includes a fix for this issue. It'd be great if you could upgrade to this new version and let us know if this fixes the issue for you, so we can release 1.5 as soon as possible.

**Comment by fdietz** [comment]
Hi @jeffkreeftmeijer!

I've just tested with my Phoenix app and got the following error message when doing a "mix compile":

```
> mix compile
==> appsignal
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (Code.LoadError) could not load /Users/fdietz/git/link_shortener/deps/appsignal/agent.exs
    (elixir) lib/code.ex:691: Code.find_file/2
    (elixir) lib/code.ex:308: Code.eval_file/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:438: :erl_eval.expr/5
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:176: Code.eval_string/3
    /Users/fdietz/git/link_shortener/deps/appsignal/mix.exs:5: Mix.Tasks.Compile.Appsignal.run/1
```

Note though I've upgraded from version "1.4.10" with your guideline above before.

Please, let me know if you need any further information to help you track this down!

**Comment by fdietz** [comment]
Version 1.5.0-beta.2 works for me. I've successfully compiled and deployed to Heroku.

Thanks!
