### ISSUE TITLE
plug is no longer an optional dependency.

### ISSUE THREAD

**Issue by jestingrabbit** [appsignal/appsignal-elixir#292]
This line

https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal/error_handler.ex#L118

is compiled regardless of the value of `Appsignal.plug?` (it has no value at compile time). It can't compile unless plug is also a dependency.

**Comment by tombruijn** [comment]
Hi @jestingrabbit,

We've fixed this in PR #291, but haven't released it yet. I think we'll release it tomorrow in v1.4.6.

The value of `Appsignal.plug?` will be either `true` or `false` during compile time.

**Comment by tombruijn** [comment]
1.4.6 has been released on the 22nd of January 2018. Closing
