### ISSUE TITLE
Appsignal.ErrorHandler generates warnings of unhandled messages

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-elixir#294]
```
10:03:23.140 [warn] ** Undefined handle_info in Appsignal.ErrorHandler
** Unhandled message: {#Reference<0.1055377727.902561793.74842>,
{:ok, "xxx"}}

10:03:23.140 [warn] ** Undefined handle_info in Appsignal.ErrorHandler
** Unhandled message: {:DOWN, #Reference<0.1055377727.902561793.74842>, :process, #PID<0.2903.0>,
:normal}
```

**Comment by husafwan** [comment]
faced this issue when i call async function in GenStage 
i think this happend because function who called this async function not found or finished her job

**Comment by jeffkreeftmeijer** [comment]
Hey @husafwan, what version are you running? Do you still get these unhandled warnings when upgrading to a version above 1.4.9?

**Comment by husafwan** [comment]
I need to check again

**Comment by husafwan** [comment]
@jeffkreeftmeijer  version of what ?

**Comment by husafwan** [comment]
@jeffkreeftmeijer  Yes the warning still appear
`17:09:49.740 [warn] ** Undefined handle_info in ProcessStage
** Unhandled message: {#Reference<0.377497240.3068657665.83327>, {:ok, %Mongo.UpdateResult{matched_count: 1, modified_count: 1, upserted_id: nil}}}
17:09:49.740 [warn] ** Undefined handle_info in ProcessStage
** Unhandled message: {:DOWN, #Reference<0.377497240.3068657665.83327>, :process, #PID<0.683.0>, :normal}`

**Comment by jeffkreeftmeijer** [comment]
Hey @husafwan,

The version of appsignal-elixir. We pushed a fix for this issue in 1.4.9, so upgrading the dependency (`mix deps.update appsignal`) should stop these messages from triggering warnings.

**Comment by husafwan** [comment]
@jeffkreeftmeijer 
** (Mix) Unknown dependency appsignal for environment prod

**Comment by jeffkreeftmeijer** [comment]
Hey @husafwan,

Could you let us know which version of the appsignal dependency you currently have installed in your app? It'd be great if you could paste the line mentioning appsignal from your `mix.lock` file here.

**Comment by husafwan** [comment]
@jeffkreeftmeijer 
can't find appsignal in mix.lock file !

**Comment by jeffkreeftmeijer** [comment]
Hey @husafwan,

That'd explain why you're getting the "Unknown dependency"-error when running `mix deps.update appsignal`. If you don't have AppSignal installed in your app, I'm struggeling to understand why you'd see `Undefined handle_info in Appsignal.ErrorHandler` in your logs. Do you have the appsignal dependency in your `mix.exs` file?
