### ISSUE TITLE
Metadata not showing up on Appsignal 

### ISSUE THREAD

**Issue by deepfryed** [appsignal/appsignal-elixir#302]
Hi,

Using https://hexdocs.pm/appsignal/1.4.7/Appsignal.html#send_error/7 to send error reports with metadata and we're unable to see them on the Appsignal incidents page.

**Comment by jeffkreeftmeijer** [comment]
Hey @deepfryed.

We just released [1.4.8](https://github.com/appsignal/appsignal-elixir/blob/develop/CHANGELOG.md#148), which includes the patch for this issue. Could you try that and let us know if that fixes the issue for you?

**Comment by deepfryed** [comment]
Yes, works. Thanks heaps++
