### ISSUE TITLE
Error loading NIF on Heroku

### ISSUE THREAD

**Issue by RobinClowers** [appsignal/appsignal-elixir#305]
On the cedar-16 stack using the [elixir buildpack](https://github.com/HashNuke/heroku-buildpack-elixir), I get this error:

```
19:24:07.727 [error] Error loading NIF, AppSignal integration disabled!

Failed to load NIF library: '/app/_build/prod/lib/appsignal/priv/appsignal_extension.so: cannot open shared object file: No such file or directory'

Is your operating system (x86_64-unknown-linux-gnu) supported?
Please check http://docs.appsignal.com/support/operating-systems.html
```
This issue looks very similar to https://github.com/appsignal/appsignal-elixir/issues/273, except the Heroku image is based on Ubuntu. Is this something Heroku would have to fix on their image?

**Comment by RobinClowers** [comment]
Hmm, upgrading from 1.3.4 to 1.4.8 seems to have fixed this.

**Comment by jeffkreeftmeijer** [comment]
Hey @RobinClowers! :wave: Great to hear this is working for you again, and thanks for letting us know upgrading fixed your issue.
