### ISSUE TITLE
🚀 Configurable :request_headers / APPSIGNAL_REQUEST_HEADERS

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#317]
We currently have a whitelist for request headers, which we'd like to make configurable.

https://github.com/appsignal/appsignal-elixir/blob/1f37ef36811089871db4cc0f773702426625212f/lib/appsignal/plug.ex#L157-L167

## The quick solution

The quickest to implement would be to [move the whitelist to the configuration](https://github.com/appsignal/appsignal-elixir/commit/10e694f98fb900cdb7b0a5eea93a41de16276b84). However, that makes it difficult for our users to add or remove a single header. Because `Appsignal.Config` isn't loaded int he host application's `config/appsignal.exs`, something like this won't work:

``` elixir
config :appsignal, :config,
  name: "appsignal-phoenix-example",
  push_api_key: "00000000-0000-0000-0000-000000000000",
  request_headers: Appsignal.Config.default_request_headers -- ~w(user-agent), # <- This won't work.
  env: Mix.env
````

To remove a single header from the config, one would have to copy the whole list into their configuration, and remove the one they don't want manually. 

``` elixir
config :appsignal, :config,
  name: "appsignal-phoenix-example",
  push_api_key: "00000000-0000-0000-0000-000000000000",
  request_headers: ~w(accept accept-charset accept-encoding accept-language cache-control connection content-length from negotiate pragma referer range auth-type gateway-interface path-translated remote-host remote-ident remote-user remote-addr request-method server-name server-port server-protocol request-uri path-info client-ip range x-request-start x-queue-start x-queue-time x-heroku-queue-wait-time x-application-start x-forwarded-for x-real-ip)
  env: Mix.env
```

## The explicit solution

Instead of having two places the configuration gets loaded from, the most explicit solution is to write the environment list to the configuration by default. Whenever a user uses the installer (`mix appsignal.install`), the generated config file will include the list of request headers. This will make sure there's one place where the request headers are listed.

We'll have to decide which headers we want to pick up by default, which will be a shorter list than we do now as users can now add their own request headers to the configuration.

``` elixir
config :appsignal, :config,
  name: "appsignal-phoenix-example",
  push_api_key: "00000000-0000-0000-0000-000000000000",
  request_headers: ~w(accept accept-charset accept-encoding accept-language cache-control connection content-length user-agent from negotiate pragma referer range),
  env: Mix.env
```

### Upgrading

For users with "old" configuration files that don't have the list in there just yet (meaning the header keys is `nil`), we'll fall back to the current list, which we won't remove until we do a major version bump. We could print a warning about this. 

## Conclusion

Both implementations seem alike, because they’re pretty much the same. The biggest difference is that the explicit solution moves the headers to the users’ configurations and makes the default list shorter. In both solutions, we’ll have a fallback list, and every edit is a complete overwrite of that default.

*Note*: decisions made here will have effect on the Ruby side. Although it's easier to implement a solution that won't work in Elixir, we'd like to keep both implementations similar. What do you think about this for both the Ruby and Elixir implementations, @matsimitsu and @tombruijn?

**Comment by tombruijn** [comment]
I like the explicit whitelist, but the ton of config by default is something I always find personally annoying.

An alternative would be to implement both a whitelist and a blacklist (with a leading blacklist) and a sane default.

But the explicit whitelist is probably the way to go. We'd have to start printing a deprecation warning as soon as possible when people don't have the config option set, and add a section to the docs explaining the change.

**Comment by matsimitsu** [comment]
I also like the explicit whitelist, otherwise you'd have to figure out what to remove from the default list.

**Comment by jeffkreeftmeijer** [comment]
Great! As you can imagine, I'd like to have the smallest amount of keys in the configuration as possible. Since existing installs will use the current list in both Elixir and Ruby, we should be able to write a smaller list to the configuration (and supply a shorter list for the environment variable). @matsimitsu @tombruijn which of the keys do we want to keep in the main list? Can we remove all `x-` keys, for example?

Currently, the list in Elixir looks like this:

```
accept accept-charset accept-encoding accept-language cache-control 
connection content-length user-agent from negotiate pragma referer range 
  
auth-type gateway-interface path-translated remote-host remote-ident 
remote-user remote-addr request-method server-name server-port 
server-protocol request-uri path-info client-ip range 
  
x-request-start x-queue-start x-queue-time x-heroku-queue-wait-time 
x-application-start x-forwarded-for x-real-ip 
```

**Comment by tombruijn** [comment]
We can remove the queue timing headers from the metadata as long as we still fetch the data and store it on the transactions.

The x-forwarded-for x-real-ip  headers are only interesting if the remote-addr header returns the load balancer's or proxy's ip address. On the other hand maybe we shouldn't store that either by default?

**Comment by matsimitsu** [comment]
I think we need most of them, for debugging purposes (e.g. accept/referer/content-length etc). Maybe do a call this afternoon to talk em through?

**Comment by jeffkreeftmeijer** [comment]
Linking this conversation from Intercom https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540654/conversations/14994864230 (sorry, private link)
