### ISSUE TITLE
Allow httposion 1.0.0

### ISSUE THREAD

**Issue by bundacia** [appsignal/appsignal-elixir#320]
I keep getting httposion dependency version conflicts because this package dictates `{:httpoison, "~> 0.11"},` while other packages in my project (eg. [google_maps](https://github.com/sntran/ex_maps/blob/d2332400491e1e240f85d99edf5fc80e702d05a7/mix.exs#L46)) dictate: `{:httpoison, "~> 1.0"}`. I can fix this with an `override: true` but I'm starting to have to put that in more and more places. At first glance it looks like [the changes](https://github.com/edgurgel/httpoison/compare/v0.13.0...v1.0.0) to 1.0.0 are not that significant.

Can we change the dependency in this package to allow something like `{:httpoison, "< 2.0"}`?

**Comment by lpil** [comment]
Yes please :)

**Comment by jeffkreeftmeijer** [comment]
Hey @bundacia and @lpil,

Thanks for letting us know about this. I've just opened #322 to allow ~> 1.0, as 1.0.0 doesn't have any backwards incompatible changes.

**Comment by bundacia** [comment]
Thanks!
