### ISSUE TITLE
Minutely probes

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#328]
In the Ruby integration, [minutely probes](https://github.com/appsignal/appsignal-ruby/blob/48508ba0eb32d7553b925b1b84f15b6afa31b9da/lib/appsignal/minutely.rb) allows running a piece of code every minute, which can be used to send custom metrics (and it's used internally to send GC stats).

To get the Elixir integration up to speed with the Ruby integration, we should investigate how to offer something like minutely probes in the Elixir library.

**Comment by tombruijn** [comment]
Added in Elixir package 1.10, #461
