### ISSUE TITLE
0.9.0 release notes say `import Appsignal.Instrumentation.Decorators` but I needed `use …`

### ISSUE THREAD

**Issue by lucas-nelson** [appsignal/appsignal-elixir#33]
Following the instructions at https://github.com/appsignal/appsignal-elixir/releases/tag/0.9.0 (under _Instrumentation macro deprecation_), I changed my instrumentation to 

```
  import Appsignal.Instrumentation.Decorators

  @decorate transaction_event
  def bar(arg) do
    # code to be instrumented
  end
```

But then I got a compilation error:

```
== Compilation error on file lib/my_instrumented_module.ex ==
** (ArgumentError) Decorator :transaction_event can only be used with the @decorate syntax
    expanding macro: Appsignal.Instrumentation.Decorators.transaction_event/1
    lib/my_instrumented_module.ex:22: MyInstrumentedModule (module)
    (elixir) expanding macro: Kernel.@/1
    lib/my_instrumented_module.ex:22: MyInstrumentedModule (module)
```

When I changed the `import` to `use`, the module compiled and the instrumentation was correctly sent to AppSignal.

Should `import` have worked? If not, and we need to use `use`, can the release notes be updated?

**Comment by arjan** [comment]
Hi lucas, thanks for reporting this, `use` is indeed the right way, i'll fix the release notes.
