### ISSUE TITLE
Allow nested metadata

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-elixir#341]
It would be nice if we could support nested metadata, so customers don't have to stringify objects to JSON to get them to AppSignal

**Comment by tombruijn** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/14894/conversations/15985344181

**Comment by tombruijn** [comment]
This should also apply to the Ruby gem.

**Comment by tombruijn** [comment]
Related issue: https://github.com/appsignal/appsignal-server/issues/2454

**Comment by ftes** [comment]
Has this since been addressed?

**Comment by ftes** [comment]
Workaround using JSON (`logger_json`):

> https://docs.appsignal.com/logging/formatting/json.html
> For nested objects, the attributes will be flattened, separated by a . character.

So if we include `metadata` in a JSON formatted log message, AppSignal picks it up.

```diff
-  Appsignal.Logger.Handler.add("phoenix")
+  :logger.add_handler(:appsignal_log, Appsignal.Logger.Handler, %{
+    config: %{group: "phoenix", format: :json},
+    formatter: {LoggerJSON.Formatters.Basic, [metadata: :all]}
+  })
```
