### ISSUE TITLE
Elixir package doesn't log to appsignal.log

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#342]
But all logs are logged to the application's STDOUT.
In the Ruby gem we hardly ever log to STDOUT, but to appsignal.log.
Any reason we're logging to STDOUT for the Elixir package?

**Comment by doughsay** [comment]
My 2 cents: don't log to files; it doesn't play nice in containerized environments.  It should be the job of the process runner to decide what to do with STDOUT, wether it eventually end up in a file or be streamed to an external logging service.

If appsignal started logging to a file for my elixir projects, I'd look for a way to turn that off.

**Comment by tombruijn** [comment]
Hi @doughsay, I've created this issue primarily to highlight a difference between our Ruby and Elixir libraries. Something we'd like to keep as similar as possible.

When we're trying to debug an issue one of our users is having we usually ask for the `appsignal.log` file to get a better idea of what our integration is doing. If part of the log is missing, because it's printed in the application's STDOUT, we might not get the whole picture.

We support logging to STDOUT using the [`log` option](https://docs.appsignal.com/elixir/configuration/options.html#appsignal_log-log). It's just that the logs are now split between the `appsignal.log` and application STDOUT by default.

**Comment by jeffkreeftmeijer** [comment]
Aside from the debug log lines discussed in #634, we now log everything through the agent to `appsignal.log` (or to stdout by using the `log` config option), so this one can be closed.
