### ISSUE TITLE
Support Erlang error messages better

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#357]
Now we get an error message as the error class, which will be truncated if it's longer than 100 characters.

```
{:badkey, :message, %Ecto.InvalidChangesetError{action: :update, changeset: #Ecto.Changeset<action:
```

Would be nice to unwrap an Erlang error message into something smaller, such as `:badkey`, or if available -> the Elixir exception struct.

As reported in: https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/15857926961

**Comment by thijsc** [comment]
https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/14888/conversations/16507346629

**Comment by jeffkreeftmeijer** [comment]
We should use [`Exception.normalize/3`](https://hexdocs.pm/elixir/Exception.html#normalize/3) to convert Erlang errors to their Elixir counterparts. Doing that should allow us to remove most of the extraction code from `Appsignal.ErrorHandler`.
