### ISSUE TITLE
Manually sending errors

### ISSUE THREAD

**Issue by cbarratt** [appsignal/appsignal-elixir#37]
I'm a little unsure if it's supposed to be a feature, but I'm currently trying to manually send exceptions like so:

`Appsignal.send_error(%RuntimeError{message: error}, "Error", System.stacktrace(), context)`

context is just a map of metadata

This is running locally in development where im attempting to test this. I have the API key set in env var and `active: true` set in the dev.exs configuration.

I'm not seeing any errors come through, I'm guessing im doing something wrong here! Any direction would be appreciated :)

**Comment by arjan** [comment]
Hmm, this is supposed to work.
@jeffkreeftmeijer would you mind trying to reproduce this?

**Comment by cbarratt** [comment]
It looks like I have this working now, but it looks like I'm not seeing the metadata sent in app signal UI :(

**Comment by arjan** [comment]
Metadata sending has been fixed in #40
