### ISSUE TITLE
Compile failure for 1.7.0-beta.1 on OTP21

### ISSUE THREAD

**Issue by schnittchen** [appsignal/appsignal-elixir#371]
Hi,

I just tried if 1.7.0 would fix a problem I have with `APP_REVISION` so I threw the beta.1 into our CI.

```
/app/_build/test/lib/appsignal/priv/libappsignal.a: member /app/_build/test/lib/appsignal/priv/libappsignal.a(__.SYMDEF) in archive is not an object
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

Don't hesitate to ask if you need more background info.

**Comment by matsimitsu** [comment]
Thanks for the report! 

We've fixed the `APP_REVISION` issue in 1.6.7, it also works with OTP21

**Comment by jeffkreeftmeijer** [comment]
Hey @schnittchen 👋

Thanks for reporting this issue. This looks like you're somehow getting the agent build for the wrong architecture. Could you paste the output of `:erlang.system_info(:system_architecture)` on your CI system?

**Comment by schnittchen** [comment]
@matsimitsu indeed 1.6.7 fixes it, thanks!

@jeffkreeftmeijer I'm running a docker container based off `elixir:1.6.6-slim` which gives me

```
iex(phx@fd1d3634039e)2> :erlang.system_info(:system_architecture)
'x86_64-pc-linux-gnu'
```

**Comment by jeffkreeftmeijer** [comment]
Hey @schnittchen,

It looks like something went wrong with the agent build in 1.7.0-beta.1. We've just released a second beta, which works in my `elixir:1.6.6-slim` container locally. If you have time, could you try that and let us know if that compiles and starts your app properly?

**Comment by schnittchen** [comment]
The error has disappeared with 1.7.0-beta.2. And I see no problems in `Mix.env == :test`.

**Comment by schnittchen** [comment]
Congrats on the new dashboard, looks really nice!

**Comment by schnittchen** [comment]
I've been able to deploy 1.7.0-beta.2 to a preproduction environment.

**Comment by jeffkreeftmeijer** [comment]
Thanks for getting back to us about this, and great to head the second beta works for you! Please let us know if you run into anything else! :)
