### ISSUE TITLE
Compilation error with Appsignal.Phoenix.Instrumenter

### ISSUE THREAD

**Issue by axelson** [appsignal/appsignal-elixir#373]
When running the tests locally we're seeing a compilation error. We believe that the error is due to us having an umbrella project with multiple applications that depend on appsignal, where only some of the applications are Phoenix applications and thus load Phoenix.

We have an alias setup in the umbrella project that:
```
  defp aliases do
    [
      "test.setup": [
        "cmd MIX_ENV=test mix test.setup"
      ],
      test: ["test.setup", "test"]
    ]
  end
```

So if the first application that gets compiled depends on appsignal but not on phoenix then appsignal gets compiled incorrectly. Is there a way to override `Appsignal.phoenix?` to always return true for our application?

Here is an example of the error that we get when we run `mix test`:
```
==> web_interface
Compiling 52 files (.ex)

== Compilation error in file lib/web_interface/endpoint.ex ==
** (UndefinedFunctionError) function Appsignal.Phoenix.Instrumenter.__info__/1 is undefined (module Appsignal.Phoenix.Instrumenter is not available)
    Appsignal.Phoenix.Instrumenter.__info__(:functions)
    (phoenix) lib/phoenix/endpoint/instrument.ex:187: anonymous fn/2 in Phoenix.Endpoint.Instrument.instrumenters_and_events/1
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) lib/phoenix/endpoint/instrument.ex:186: Phoenix.Endpoint.Instrument.instrumenters_and_events/1
    (phoenix) lib/phoenix/endpoint/instrument.ex:179: Phoenix.Endpoint.Instrument.events_to_instrumenters/1
    (phoenix) lib/phoenix/endpoint/instrument.ex:10: Phoenix.Endpoint.Instrument.definstrument/2
    (phoenix) expanding macro: Phoenix.Endpoint.__before_compile__/1
    lib/web_interface/endpoint.ex:1: WebInterface.Endpoint (module)
```

**Comment by jeffkreeftmeijer** [comment]
Hey @axelson,

Thanks for letting us know about this. Is this only happening when running your tests, or does this prevent your app from starting as well?

We generally recommend to put the appsignal dependency in the umbrella’s mix.exs file (like in https://github.com/jeffkreeftmeijer/appsignal-phoenix-example). That way, the dependency is always available to all of your apps. Would that work for your use case?

Also, could you let us know which versions of Elixir, AppSignal and Phoenix you’re using?
