### ISSUE TITLE
Toniq errors are not tracked

### ISSUE THREAD

**Issue by aaronjensen** [appsignal/appsignal-elixir#38]
Toniq uses the error log to report errors. I thought that appsignal listened to that, but I'm not seeing errors when I intentionally cause them.

Should this work or is this not hooked up?

See: https://github.com/joakimk/toniq/issues/29

**Comment by arjan** [comment]
The [second reply](https://github.com/joakimk/toniq/issues/29#issuecomment-261707812) from the ticket describes the exact issue: Appsignal also expects the process just to crash. It does not tie in to Elixir's logger but ties into the lower-level Erlang `error_logger` module.

I guess Appsignal could use a similar `use_logger` option as well (with the risk of having errors reported multiple times)

**Comment by aaronjensen** [comment]
I see, thanks for the explanation. I'm checking to see if we can just add a hook to toniq rather than rely on a `use_logger` option, though that may not be a horrible thing. It'd just depend on how many duplicates we got in practice.

**Comment by arjan** [comment]
Okay, let me know how it goes. Appsignal has a [send_error](https://hexdocs.pm/appsignal/Appsignal.html#send_error/4) function which you can use in your hook to easily send an error.

**Comment by arjan** [comment]
Maybe, if you've found a solution, it would be nice to integrate this into the Appsignal extension directly; Appsignal could check whether Toniq is used and install its error handler.

**Comment by aaronjensen** [comment]
👍  see https://github.com/joakimk/toniq/issues/29#issuecomment-265251468 for the first draft.

**Comment by tombruijn** [comment]
Closed in favor of #176
