### ISSUE TITLE
Windows reporting nano_seconds, native as zero causes div by zero

### ISSUE THREAD

**Issue by mraaroncruz** [appsignal/appsignal-elixir#385]
On a colleague's windows machine, `@nano_seconds` equals zero here.
https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal/ecto.ex#L18

So this line divides by zero and we get a bad arithmetic error.
https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal/ecto.ex#L30

On a side note `:nano_seconds` has been deprecated in favor of `:nanosecond` [Source](https://bugs.erlang.org/browse/ERL-339)

Thank you!

**Comment by tombruijn** [comment]
Hi @mraaroncruz, that's not good. We don't actively support Windows, but it shouldn't crash your app either. We'll look at how we can disable the integration on Windows even further to avoid this error.

Thanks for reporting the issue!

**Comment by tombruijn** [comment]
This is probably fixed if we fix this issue: https://github.com/appsignal/appsignal-elixir/issues/409

**Comment by tombruijn** [comment]
We should disable completely on Windows, in case of other errors that may occur. Instead of working around this error we will work on disabling the integration on Windows in issue #409.
