### ISSUE TITLE
metadata sent via send_error does not show up in appsignal

### ISSUE THREAD

**Issue by aaronjensen** [appsignal/appsignal-elixir#39]
Using `Appsignal.send_error/4`, I'm not seeing any of the metadata I send in the 4th argument in my error on appsignal. 

I'm using https://github.com/joakimk/toniq/issues/29#issuecomment-265251468

**Comment by cbarratt** [comment]
I'm currently seeing the same issue, I'm getting the error message but zero metadata.

**Comment by arjan** [comment]
Yep, confirmed this. Dont know what I was thinking when I coded this.. :)

**Comment by cbarratt** [comment]
Excellent @arjan - I'll switch to using github for master branch and give this a test :)

**Comment by arjan** [comment]
OK. FYI, we're pushing 0.9.2 within the hour.
