### ISSUE TITLE
`Appsignal.stop/1` doesn't stop anything?

### ISSUE THREAD

**Issue by CrowdHailer** [appsignal/appsignal-elixir#398]
It appears that `Appsignal.stop/1`, informs the logs that it is stopping and then proceeds to stop nothing at all? :thinking: 

Is there a reason for this?
https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal.ex#L48-L50

**Comment by jeffkreeftmeijer** [comment]
Hey @CrowdHailer! 👋 

`Appsignal.stop/1` doesn’t do anything but log a message, as it’s a callback that’s called after the application’s supervisor is stopped. Usually, this callback is used to do cleanup, but we use it to let the user know the AppSignal app has stopped.

**Comment by CrowdHailer** [comment]
Sorry my miss understanding. The correct way to stop is to use `Application.stop(:appsignal)`?

**Comment by jeffkreeftmeijer** [comment]
That's right. If you'd like to explicitly stop the Appsignal application, you'd call `Application.stop(:appsignal)`. The application will then be stopped, and the `Appsignal.stop/1` callback is called internally. `Appsignal.stop/1`, doesn't actually stop the application. 

May I ask why you're manually stopping the AppSignal app, though? :)

**Comment by CrowdHailer** [comment]
It was incorrectly reporting that the `APPSIGNAL_PUSH_TOKEN` was not set and I was investigating when it was checking this

**Comment by tombruijn** [comment]
Thanks for the check @CrowdHailer about this piece of code! Closing.
