### ISSUE TITLE
`Appsignal.Transaction.set_meta_data/2` can't handle a float value

### ISSUE THREAD

**Issue by naserca** [appsignal/appsignal-elixir#401]
When attempting to send metadata via `Appsignal.send_error/6` like:

```elixir
Appsignal.send_error(reason, message, trace, %{exchange_rate: 1.21})
```

we get a `FunctionClauseError` on `Appsignal.Transaction.to_s/1`:

```
** (FunctionClauseError) no function clause matching in Appsignal.Transaction.to_s/1
    (appsignal) lib/appsignal/transaction.ex:484: Appsignal.Transaction.to_s(1.1)
    (appsignal) lib/appsignal/transaction.ex:369: Appsignal.Transaction.set_meta_data/3
    (elixir) lib/enum.ex:743: anonymous fn/3 in Enum.each/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1915: Enum.each/2
    (appsignal) lib/appsignal/transaction.ex:336: Appsignal.Transaction.set_meta_data/2
    (appsignal) lib/appsignal/error_handler.ex:51: Appsignal.ErrorHandler.submit_transaction/6
```

This seems to be a straightforward fix. Just need a new `to_s` def + guard like:

```elixir
defmodule Appsignal.Transaction do
  defp to_s(value) when is_float(value), do: Float.to_string(value)
end
```

**Comment by tombruijn** [comment]
Hi @naserca, that's correct. Float values are not supported as listed in [our docs](https://docs.appsignal.com/elixir/instrumentation/tagging.html):

> The tagged value must be a String, Atom or Integer.

There's no big reason why we don't support floats at the moment, and we will probably do in the future, but for now you can cast the value to a float to get the value sent to AppSignal.
