### ISSUE TITLE
Ecto 3.0 support

### ISSUE THREAD

**Issue by EskiMag** [appsignal/appsignal-elixir#415]
Hi all,

when compiling Phoenix 1.4.0rc2 + Ecto 3.0.0rc1 with suggested `loggers: [ ... ]` configuration for Ecto.Repo logging, I get this warning:
```
warning: the :loggers configuration for Api.Repo is deprecated.

  * To customize the log level, set log: :debug | :info | :warn | :error instead
  * To disable logging, set log: false instead
  * To hook into logging events, see the "Telemetry Events" section in Ecto.Repo docs

  lib/ecto/repo/supervisor.ex:76: Ecto.Repo.Supervisor.compile_config/2
  lib/api/repo.ex:2: (module)
  (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4
  (elixir) src/elixir_compiler.erl:68: :elixir_compiler.compile/3
  (elixir) src/elixir_module.erl:281: :elixir_module.eval_form/6
```

Should it be ignored or should I configure my app some other way?

Thanks.

**Comment by jeffkreeftmeijer** [comment]
Hey @EskiMag,

Ecto's loggers are deprecated in 3.0, so we should move to using Telemetry instead. I've started a branch to add support and opened a pull request to take the first step in https://github.com/appsignal/appsignal-elixir/pull/416. 

If you have time to help testing, could you switch the appsignal dependency our `telemetry` branch in your app and attach `Appsignal.Ecto` to Ecto's Telemetry events instead of setting the `:loggers` configuration in your Repo config? You should be able to attach to our new `handle_event/4` function like this:

``` elixir
Telemetry.attach("appsignal-ecto", [:your_app, :repo, :query], Appsignal.Ecto, :handle_event, nil)
``` 

Could you let us know how that's working for you? :)

**Comment by EskiMag** [comment]
Hello @jeffkreeftmeijer,

thanks for your quick response. I would like to try your solution, but to be honest, I have no idea where I should place that line of code you proposed. 😊 😁 
Could you please give me more info?

Thank you.

**Comment by jeffkreeftmeijer** [comment]
Hey @EskiMag,

We're looking for a nicer way to configure this, but it would work by adding it to your application's `start/2` function for now. It looks like this in my Phoenix example app:

``` elixir
defmodule AppsignalPhoenixExample.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(AppsignalPhoenixExample.Repo, []),
      # Start the endpoint when the application starts
      supervisor(AppsignalPhoenixExampleWeb.Endpoint, [])
      # Start your own worker by calling: AppsignalPhoenixExample.Worker.start_link(arg1, arg2, arg3)
      # worker(AppsignalPhoenixExample.Worker, [arg1, arg2, arg3]),
    ]

    Telemetry.attach(
      "appsignal-ecto",
      [:appsignal_phoenix_example, :repo, :query],
      Appsignal.Ecto,
      :handle_event,
      nil
    )

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: AppsignalPhoenixExample.Supervisor]
    Supervisor.start_link(children, opts)
  end
```

**Comment by EskiMag** [comment]
OK, it seems to be working. Now I can see the `query.ecto` in the details of the Phoenix Controller action call. One thing that I am confused about is the times shown there. At the top, there's `89 ms` for `ecto` and `371 µs` for `phoenix_controller`, which seems to be OK. But down there in **event timeline**, both events are shown to have the same duration. Is that correct? I am sorry, if I am asking weird questions, but I am just getting to know the AppSignal app. :-) Thanks

![screenshot 2018-10-29 at 13 03 07](https://user-images.githubusercontent.com/23926/47648824-8003e780-db7b-11e8-9ab4-38c418efc33e.png)

**Comment by jeffkreeftmeijer** [comment]
Great to hear that fixes Ecto instrumentation for you, and thanks for diving in to make sure everything's working. We'll propose a way to configure the Ecto instrumentation without having to add it to your application file.

As for your question about the event timeline; In this case, the query is executed within the phoenix controller call. Even though the phoenix controller call only takes 371 µs, the query is nested within, which increases the total duration for the controller event.

**Comment by EskiMag** [comment]
Oh, that makes sense. That nesting was not clear to me, but now I can see it. :-)
Thanks again for help. Feel free to close this issue, or keep it open for others facing the same problem as I was. Have a nice day.

**Comment by lpil** [comment]
Hi all! This issue on the telemetry track may be of interest: https://github.com/beam-telemetry/telemetry/issues/35

**Comment by jeffkreeftmeijer** [comment]
Hey @lpil,

Thanks! We’ll be keeping a close eye on the developments in telemetry_metrics. We’re now requiring users to attach to Telemetry manually, but we’d love to support a way to attach without having the user having to configure it. 

However, we’d like to keep this flexible, which is why we haven’t implemented something to get the database name and attach to it on our side.

**Comment by arkgil** [comment]
@jeffkreeftmeijer Hi there :wave: 🙂 

I have set up a simple Telemetry.Metrics/StatsD integration here https://github.com/arkgil/telemetry_metrics_statsd. With this library, setting up Phoenix + VM metrics looks like this:

```elixir
    metrics = [
      counter(
        "phoenix.controller.call.start",
        name: "http.request.count",
        metadata: fn metadata ->
          controller = Phoenix.Controller.controller_module(metadata.conn)
          action = Phoenix.Controller.action_name(metadata.conn)
          %{controller: inspect(controller), action: action}
        end,
        tags: [:controller, :action]
      ),
      distribution(
        "phoenix.controller.call.stop",
        name: "http.request.response_time",
        buckets: [0, 100, 200, 300],
        metadata: fn metadata ->
          controller = Phoenix.Controller.controller_module(metadata.conn)
          action = Phoenix.Controller.action_name(metadata.conn)
          %{controller: inspect(controller), action: action}
        end,
        tags: [:controller, :action]
      ),
      last_value("vm.memory.total", []),
      last_value("vm.memory.binary", []),
      last_value("vm.memory.ets", []),
      last_value("vm.memory.processes_used", []),
      last_value("vm.run_queue_lengths.total", [])
    ]

    TelemetryMetricsStatsd.start_link(metrics: metrics)
```

Let me know what you think about it and if it suits the way AppSignal defines or collects metrics 🙂

**Comment by jeffkreeftmeijer** [comment]
Hey @arkgil! 👋

Thanks for reaching out! We're planning on looking into Telemetry to switch out current template metrics as well as our custom metrics over from the template and function wrappers we use now. That sample looks like a great fit for us, and I'll be sure to do some more research on that soon.

I'll be sure to keep you posted!
