### ISSUE TITLE
Can't start nested app in Umbrella project

### ISSUE THREAD

**Issue by jvanbaarsen** [appsignal/appsignal-elixir#445]
When you add AppSignal to an Umbrella app, you can not start the nested apps indepdendently from each other. If you try to do so it will show an error that the AppSignal app cannot be found.

**Comment by endersstocker** [comment]
+1

Independent execution is one of the main features of an umbrella project. Following the AppSignal docs breaks that feature.

Ordinarily you would have the OTP app start before the dependent app by putting the dep into each app’s mix.exs (which would obviate its inclusion in `:extra_applications`). Upgrading that dep in the future would require an update to multiple mix.exs files, but the compiler would ensure they matched. Yet the docs explicitly state:
>Install and configure AppSignal in the umbrella, and not separately in each nested app

Why is this?

**Comment by jeffkreeftmeijer** [comment]
Hey @endersstocker,

Thanks for chiming in! We added this in some of the first versions of our integration, where this fixed issues that some of our customers were seeing. We'd love to be able to update the documentation and have users install appsignal in both nested apps, so I've been testing in an umbrella app and found that the integration is still working.

I've [moved the dependency to both nested apps](https://github.com/jeffkreeftmeijer/appsignal-umbrella-example/commit/ce597dd235bb87caff78fe0c726038672d94a799), and [removed `:appsignal` from `extra_applications`](https://github.com/jeffkreeftmeijer/appsignal-umbrella-example/commit/5db91303c35ba8d119258b1d4d9203884e959215). Does this work for your application too? Assuming you're running a Phoenix umbrella, I'm particularly interested to know if you're getting Ecto queries, as well as Phoenix events in.

**Comment by endersstocker** [comment]
Hi @jeffkreeftmeijer,

We were able to the move the dependency down to the nested apps without any apparent negative consequences. Ecto queries and Phoenix events are both successfully making their way into AppSignal. Huzzah!

**Comment by jvanbaarsen** [comment]
@jeffkreeftmeijer Can I contact [Private Internal link](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/search/conversations/20409360001) about this change as well? Since I believe it will solve that issue also.

**Comment by jeffkreeftmeijer** [comment]
@endersstocker that's great to hear! Thanks for getting back to us about this. We'll do some more testing and we'll update the documentation if we don't find any further issues.

@jvanbaarsen yes, great idea. Could you ask them to make sure this setup works for them too?

**Comment by jvanbaarsen** [comment]
@jeffkreeftmeijer Got confirmation that this works for them. Did we already update the docs? If so, shall we close this issue?

**Comment by jvanbaarsen** [comment]
@jeffkreeftmeijer Got confirmation that this works for them. Did we already update the docs? If so, shall we close this issue?

**Comment by jeffkreeftmeijer** [comment]
Thanks! We're updating the docs in https://github.com/appsignal/appsignal-docs/pull/213 and https://github.com/appsignal/appsignal-server/pull/4115. Thanks @endersstocker for your input, we're closing this and will update the documentation in the issues above.
