### ISSUE TITLE
Add macOS build to TravisCI

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#449]
TravisCI supports macOS builds. Add it to the matrix so we don't have to make sure to test the OS locally.

**Comment by jeffkreeftmeijer** [comment]
Gave it a shot in the [macos](https://github.com/appsignal/appsignal-elixir/compare/macos) branch, which is [failing](https://travis-ci.org/appsignal/appsignal-elixir/builds/492077367) because there don't seem to be any pre-built binaries for macOS:

```
19.3 is not installed. Downloading and installing pre-build binary.
Downloading archive: https://s3.amazonaws.com/travis-otp-releases/binaries/osx/10.13/x86_64/erlang-19.3-nonroot.tar.bz2
0.17s$ wget -o ${TRAVIS_HOME}/erlang.tar.bz2 ${archive_url}
The command "wget -o ${TRAVIS_HOME}/erlang.tar.bz2 ${archive_url}" failed and exited with 8 during .
```

**Comment by tombruijn** [comment]
Can possibly pick up in https://github.com/appsignal/appsignal-elixir/issues/545
But didn't decide to do that for the Ruby gem, instead we should pick this up in: https://github.com/appsignal/appsignal-agent/issues/496
