### ISSUE TITLE
Consider usage of Jason instead of Poison

### ISSUE THREAD

**Issue by julien-leclercq** [appsignal/appsignal-elixir#474]
Hello, 
accordingly to latest phoenix team technical choices, the elixir community is dropping poison in favour of jason. Your package still require poison, do you plan a Jason support ?
Cheers, 
Julien.

https://github.com/phoenixframework/phoenix/issues/2693

**Comment by jvanbaarsen** [comment]
Hi @julien-leclercq,

We plan on making both the dependencies optional. Depending on which of the two you have in your project we will use that one.

**Comment by julien-leclercq** [comment]
exactly what I was hoping for, do you have an idea of the release date for this ?

**Comment by jvanbaarsen** [comment]
@julien-leclercq At this moment no, it has been on my list of things to do for a little while now. I'll report back to this issue once it is shipped.

**Comment by julien-leclercq** [comment]
Thanks ! I will keep up to date.

**Comment by fenollp** [comment]
We've just now managed to move to Ecto v3 & would love to drop our last reason to have Poison around (right now we carry both Jason and Poison).

Maybe take a look at how supporting both as optional choice here: https://github.com/open-api-spex/open_api_spex/pull/75

**Comment by jeffkreeftmeijer** [comment]
Hey everyone,

We've just released 1.11.0-beta.1, which includes an optional dependency on both Jason and Poison. In this version, we'll check if either Jason or Poison is available, and use that. It'd be great if you could upgrade to this version to see if everything works for you. If you do, make sure to depend on either Jason or Poison (which should already be the case for Phoenix applications). Please let us know if you run into any issues! :)

Thanks for your input, everybody!
