### ISSUE TITLE
High cpu after upgrade to 1.10.4 from 1.9.4

### ISSUE THREAD

**Issue by jdobrzanski** [appsignal/appsignal-elixir#476]
<img width="1176" alt="Screen Shot 2019-04-08 at 11 45 47 AM" src="https://user-images.githubusercontent.com/5341410/55741806-26da9280-59fc-11e9-9461-cab1e6f54bdb.png">
The deploy that added upgraded appsignal happen on the 4th in the graph, follow by a rollback  on the 5th, followed by a roll forward.
Here is the observer:
<img width="854" alt="Screen Shot 2019-04-08 at 12 46 56 PM" src="https://user-images.githubusercontent.com/5341410/55741907-6903d400-59fc-11e9-8a6a-85940ffd629f.png">

I haven't turned off appsignal yet to confirm that it is appsignal (need to check cpu usage beore/after without using appsignal itself of course) but I expect this to be the case given the reds shown in the observer.  Note that those reds in the screen cap are after only an hour or less of uptime. 

Ironically, I made the upgrade because appsignal caused stuck high cpu usage after ~5 days of up time (killing it made the server normal again) - now the server seems stuck on high-ish cpu usage permanently (even if i kill Elixir.Appsignal.TransactionRegistry).

**Comment by thijsc** [comment]
Hi @jdobrzanski,

Thanks for reporting. We usually don't do support over issues because there's often a back and forth with private information about your app. I'll contact you over email. If it turns out that there is a bug or performance regression we'll open an issue here to track that.

**Comment by thijsc** [comment]
Quick update here because I suspect my e-mails are going into spam: I think this is due to improved support for Docker CPU metrics. We now measure on the container instead of the host metrics.

Do you have any other system that you can verify these numbers against? For example `docker stats`?

**Comment by jdobrzanski** [comment]
@thijsc from the machine, using `top` I can see that `appsignal-agent` is taken minimal cpu time (less then 1%) while the `beam.smp` is hovering around 500% - no other processes are using more than 1%.  Again, its the number of reductions in the beam being by the `Elixir.Appsignal.Transation` process

<img width="460" alt="Screen Shot 2019-04-12 at 2 12 58 PM" src="https://user-images.githubusercontent.com/5341410/56057738-9a96db00-5d2d-11e9-9116-6c4d60fed77b.png">

that is using the cpu.

**Comment by jdobrzanski** [comment]
@thijsc @tombruijn We just experienced a brown out on our site - `Elixir.Appsignal.TransationRegistry`'s message queue backed up and the beam began failing to maintain db connections, etc..  Killing `Elixir.Appsignal.TransationRegistry` only relieved our situation for a minute - finally we had to disable appsignal altogether - and now our site is responsive again and `top` is reporting around 120% for the cpu on the server process.
<img width="459" alt="Screen Shot 2019-04-12 at 3 54 06 PM" src="https://user-images.githubusercontent.com/5341410/56063420-35e37c80-5d3d-11e9-95e0-262a085b6b3d.png">

**Comment by thijsc** [comment]
We're clearing our schedule today to look into this, will get back to you.

**Comment by tombruijn** [comment]
Related support thread: https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/21589919034

**Comment by tombruijn** [comment]
We'll have another look at this once we've shipped a new release with improve container CPU metrics.
We're not entirely sure where the problem is, either with the reported metrics or the reductions in the transaction registry.

**Comment by tombruijn** [comment]
Hi @jdobrzanski,

We've shipped a new Elixir package (1.10.11) with more accurate container CPU metrics. Can you upgrade and let us know if you still see the same high CPU usage as before?

**Comment by BenMorganIO** [comment]
So, I've been researching this for a bit and it appears a large number of reductions doesn't appear to be that bad. The scheduler will still move on and take on other tasks after 2000 reductions or so. What is _concerning_ is the GenServer blocking everything even though ETS is in use.

The GenServer is a clear bottleneck and what's been happening for our app is the scheduler gets stuck running through the transaction registry. This will happen at the beginning and end of each request. If you have some other requests that have finished their allotted 2000 reductions and the scheduler picks up work for the Appsignal GenServer it'll run into quick a bit of a problem, the thing will hang if there's already a call to the GenServer.

Now, this might not be that bad of a problem if you aren't receiving a few million requests a second and since the code is quick efficient and fast. But, if you're like me and you have an app receiving a few million requests a second where you cannot scale this out since it's all tied to _one_ process: you're toast.

**Comment by jeffkreeftmeijer** [comment]
We've merged @BenMorganIO's [pull request](https://github.com/appsignal/appsignal-elixir/pull/505) in, which has a fix for the performance issues we've been seeing in the TransactionRegistry. We've just released it as part of AppSignal for Elixir 1.11.0-beta.1.

If you're running into performance issues like these, please try the beta and let us know if it helped. Also (even if you're not affected by any performance issues), we'd love to know how the rest of the release works for you, so we can release 1.11.0 as soon as possible.

Thanks for your input, everyone, and thanks once again for your work on this, Ben!

**Comment by jdobrzanski** [comment]
@jeffkreeftmeijer moving this to email, we did just have another outage

**Comment by jdobrzanski** [comment]
@thijsc @tombruijn @BenMorganIO @jeffkreeftmeijer 
The transaction registry has consistently stayed on the low end of reductions and queue length today during our highest usage and no outages have occurred.  Thank you some much for the hard work!  Looking forward to 1.11.0.

**Comment by BenMorganIO** [comment]
@jdobrzanski really happy to hear that. There's still a bit of a bottleneck there for errors, but as long as you aren't generating millions a minute, you should be good to go.

**Comment by jdobrzanski** [comment]
@BenMorganIO, thank you - errors, that is the reason for the outages.  I just went back and looked at our fires and they were preceded by an increase in the error count - it seems that when the error count went to ~400-500 then our response times would climb and the transaction registry would run hot and not process messages fast enough until we lost services.

**Comment by BenMorganIO** [comment]
Do you have a NIF in your application? (Besides Appsignal.)
