### ISSUE TITLE
app signal 0.0.9 fails to install on macOS Sierra.

### ISSUE THREAD

**Issue by idyll** [appsignal/appsignal-elixir#5]
```
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
==> chat_server
** (Mix) Checksum verification of /tmp/7d8fcfaappsignal-x86_64-darwin-all-static.tar.gz failed!
Calculated: ad5ff38b7490224efc650dcb7909ca8980b914d6cbad7462e8b1c0712c74f3de
  Expected: 1d2dbd22ad0fe22d9838022533df4debc2fbb9daa2519beed75d7e057b62e980
```

Looks like there 's some sort of checksum issue? Either the checksum is wrong or...

Note that 0.0.8 / 0.0.7 work without issue. So I suspect the checksum or file is just wrong.

**Comment by arjan** [comment]
Sounds like a bug.. Can you try removing the appsignal gz file from /tmp and then retry?

**Comment by arjan** [comment]
Also note there is a 0.1.0 release now.

**Comment by rranelli** [comment]
Had exactly the same issue right now. (but on Linux). 

Removing `/tmp/....tar.gz` worked fine.

**Comment by arjan** [comment]
Thanks, I'll try to reproduce it.

**Comment by arjan** [comment]
I think this will be fixed when you `deps.update` your appsignal to `0.2.0`. You need to change your deps in `mix.exs` to `{:appsignal, "~> 0.0}`, though (that was a documentation error)
