### ISSUE TITLE
Remove Constraint on Decorator

### ISSUE THREAD

**Issue by BenMorganIO** [appsignal/appsignal-elixir#502]
Hey guys,

I'm stopping by to ask if we can release the constraint on have `~> 1.2.3` as the version lock on `decorator`. I'm looking to use the `@decorate_all` feature in 1.3.0 and wondering if we can release the lock.

https://github.com/arjan/decorator/releases/tag/1.3.0

**Comment by tombruijn** [comment]
Hi @BenMorganIO we're going to look if we're compatible with newer version and update the version lock then. Thanks for the suggestion!

**Comment by tombruijn** [comment]
TODO:
- see if we're compatible with the newer version
- update if needed.
- if it requires a significant change plan more time for it.

**Comment by BenMorganIO** [comment]
I actually removed the decorator to use the latest version of GQL which had all of the information available in telemetry.

**Comment by sorliem** [comment]
Bump on this. We are wanting to use Decorators 1.3.0, any plans to update soon?

**Comment by BenMorganIO** [comment]
@sorliem are you able to describe why you need decorators 1.3? I wonder if I could help.
