### ISSUE TITLE
Track mailbox metrics

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#510]
See this conversation for the full idea: https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/conversation/23591645793#part_id=comment-23591645793-3719914749

> I love the insights I get from Appsignal, especially the Erlang specific sections... any plans to add some info on mailbox sizes into the metrics? max, avg, 95th % counts perhaps? That would be awesome if you guys were working on or would consider!
> 
> As for mailboxes, your elixir guy will probably be able to fill you in, but much like Ruby has objects sending messages to other objects, Erlang has processes sending messages to other processes. A Process isn't an object of course, but there are parallels, and of course, unlike ruby, these messages are all being sent in a massively parallel way, as either async cast messages or synchronous call messages. In either case, they land in the receiver's mailbox, and are processed, usually in FIFO order (though there are exceptions). The mailbox is basically the queue for that process, and like any queue, it can back up! They don't usually break as a result (thought they can in extreme cases) but the backups are generally a bottleneck and good to know about as a metric in your system. Make sense? Erlang exposes some details on these mailbox queue sizes and sampling them at some interval and summarizing the results would be an awesome insight to have in most any real world erlang system.

**Comment by tombruijn** [comment]
Estimation (because ZenHub is broken): 2

**Comment by axelson** [comment]
+1 to this! I also wanted to note that the "The Road to 2 Million Websocket Connections in Phoenix" article looked at mailbox length as a major indicator in one portion: https://www.phoenixframework.org/blog/the-road-to-2-million-websocket-connections
