### ISSUE TITLE
Deprecate the old front-end monitoring solution

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-elixir#519]
Linked to https://github.com/appsignal/appsignal-ruby/issues/564, as we now have a fully-fledged front-end monitoring solution now, we can begin to deprecate the old code used for front-end error tracking in the Elixir package.

## TODO:

- [x] Add deprecation message (STDOUT and appsignal.log) in the when the frontend plug is loaded.

**Comment by tombruijn** [comment]
From the Ruby repo issue:

> Same for the Elixir one https://github.com/tombruijn/appsignal-elixir_js_plug
> I need to add a warning to the README and maybe release a new version that prints a deprecation warning too.

The JavaScript Plug is not directly part of this repo, but my separate project is not in our backlog system. For anyone wondering where the code for the Plug in this repo is, it isn't.

**Comment by tombruijn** [comment]
I've deprecated my plug https://github.com/tombruijn/appsignal-elixir_js_plug and released a new message
It will now log a warning message saying the plug has been deprecated and that the official JavaScript integration should be used instead.
