### ISSUE TITLE
Ecto queries are not tracked inside borrowed transaction processes

### ISSUE THREAD

**Issue by szlend** [appsignal/appsignal-elixir#522]
## Describe the bug

Ecto queries are not tracked when inside borrowed transaction processes (e.g. a Task that is assigned the parent process transaction.)

I believe this is caused by:
https://github.com/appsignal/appsignal-elixir/blob/ec77e79960fdd86317d6c1393495f5462bf3b40c/lib/appsignal/ecto.ex#L54

I don't think the borrowed transactions are mapped by pid in the `TransactionRegistry`.

## To Reproduce

```elixir
# inside a Phoenix action / Appsignal transaction
pid = self()

task = Task.async(fn ->
  # my_app.task is logged
  instrument(pid, "my_app.task", "", fn ->
    # ...
    Repo.all(query1) # ecto query1 is not logged
    # ...
  end)
end)

Repo.all(query2) # ecto query2 is logged

Task.await(task)

```

**Comment by tombruijn** [comment]
Hi @szlend,

That's correct. When you start a new task/process we don't track the events in that process. We currently have an AppSignal transaction per process setup. If you want to track the events in that separate process you will need to create a new AppSignal transaction in that process. See the docs here: https://docs.appsignal.com/elixir/instrumentation/instrumentation.html#helper-transactions

**Comment by szlend** [comment]
@tombruijn I understand that. However if you explicitly provide functionality where you can instrument a process for a different pid (see that I called `instrument(pid, ...)` within the new process), then the expected outcome is that all events within that process will be logged for the specified transaction. I believe that this is a bug.

**Comment by szlend** [comment]
I think this could be fixed by allowing the same transaction to be associated with different pids in `Appsignal.TransactionRegistry`. So if you call `instrument(pid, ...)` and `pid != self()`, then you would associate `self()` with `pid`'s transaction.

**Comment by szlend** [comment]
Actually, I may have misunderstood the purpose of `instrument`. Nevermind.

**Comment by tombruijn** [comment]
Ah yes, that's not what we support at this time. We are looking into it, but nothing that's ready to test just yet.

**Comment by tombruijn** [comment]
We can associate transactions yet, but you can start a new transaction in the task to monitor it separately from the process that spawned the task with the docs I linked earlier.
