### ISSUE TITLE
Background jobs prefixed with Elixir

### ISSUE THREAD

**Issue by hfjallemark** [appsignal/appsignal-elixir#529]
## Describe the bug

When using backgrounds transactions the module name is prefixed with `Elixir`. Is there any way to strip that?

E.g:
```
defmodule MyApp.MyModule do
  use Appsignal.Instrumentation.Decorators

  @decorate transaction(:background_job)
  def my_function(search_term) do
    IO.inspect("my function!")
  end
end
```

will log:
```
Elixir.MyApp.MyModule#my_function
```

**Comment by jeffkreeftmeijer** [comment]
Hey @hfjallemark!

You're right, the current implementation doesn't filter the module names to take the `Elixir.` prefix off just yet. We're reviewing a patch in #530 that unifies this between different parts of the integration, which we'll release in an upcoming version. 

In the meantime, you can overwrite the action name inside your function by using the `Transaction.set_action/1` function:

```
Appsignal.Transaction.set_action("MyApp.MyModule#myfunction")
```

Thanks for letting us know!

**Comment by hfjallemark** [comment]
Okay, thanks!
