### ISSUE TITLE
Error running ecto data update migrations with Appsignal installed

### ISSUE THREAD

**Issue by navinpeiris** [appsignal/appsignal-elixir#53]
I'm trying to run a migration which simply updates the values of a particular table column using Repo.update_all, but when Appsignal is active, it throws the following error:

```elixir
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:"$appsignal_transaction_registry", #PID<0.73.0>)
    lib/appsignal/transaction/registry.ex:46: Appsignal.TransactionRegistry.lookup/2
    lib/appsignal/ecto.ex:23: Appsignal.Ecto.log/1
    (db_connection) lib/db_connection.ex:1177: DBConnection.log/6
    (ecto) lib/ecto/adapters/postgres/connection.ex:78: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:424: Ecto.Adapters.SQL.execute_and_cache/7
    (stdlib) timer.erl:197: :timer.tc/3
```

I've got the `Appsignal.Ecto` logger configured via:

```elixir
config :hoffer, MyApp.Repo,
  loggers: [Appsignal.Ecto]
```

This is on:

```
elixir: 1.3.4
ecto: 2.0.6
appsignal: 0.9.2
```
The workaround for me with this was to remove the `Appsignal.Ecto` logger config so that the migration could run, and then re-enable it again.

Do let me know what other information might be helpful, I'll get them across as soon as possible.

**Comment by jeffkreeftmeijer** [comment]
Hey @navinpeiris, thanks for reporting this (and sorry for the inconvenience)! I'll create an example app to reproduce this, and I'll get back to you as soon as I know more.

**Comment by arjan** [comment]
@jeffkreeftmeijer  it seems the migrations are run when the `appsignal` application is not started. The fix would be to check whether the application is running inside the ecto logger. or maybe even in the transaction registry.
