### ISSUE TITLE
Erlang Ecosystem Foundation, AppSignal and OpenTelemetry

### ISSUE THREAD

**Issue by tsloughter** [appsignal/appsignal-elixir#544]
I may have already spoke to someone with AppSignal about this on Slack but I don't recall, so I'm opening this to make sure the question was raised and to have a history of it that I can find next time I wonder if I'd reached out to you :)

For starters there is the Observability Working Group, https://erlef.org/wg/observability, that AppSignal might be interested in taking part in. We meet monthly and coordinate on Slack and Github https://github.com/erlef/eef-observability-wg. Our main focuses recently have been Telemetry (https://github.com/beam-telemetry/telemetry) and OpenTelemetry (https://github.com/open-telemetry/opentelemetry-erlang-api/).

It would be great to have AppSignal involved both with the working group and with Elixir/Erlang OpenTelemetry.

**Comment by anthonator** [comment]
I'm curious. Does AppSignal participates in the Observability Working Group?

**Comment by tsloughter** [comment]
@anthonator na. The only APM with someone involved is New Relic.

**Comment by tsloughter** [comment]
I'll go ahead and close this. But of course please reach out if you have interest.

Since my first post the repo for OpenTelemetry moved to https://github.com/open-telemetry/opentelemetry-erlang and https://github.com/open-telemetry/opentelemetry-erlang-contrib for instrumentation libraries.

Oh, one last update, @anthonator, technically another APM provider participates since I'm now at Splunk :)
