### ISSUE TITLE
Move to SemaphoreCI

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#545]
Move build to SemaphoreCI, so all our builds run there. For the Ruby gem it seems more stable.

Example of the Ruby gem setup: https://github.com/appsignal/appsignal-ruby/blob/2c594a2f710e87c6cd2c36c09c9b3e6bc03df662/.semaphore/semaphore.yml

**Comment by jeffkreeftmeijer** [comment]
We’ve been on Semaphore for 2.x since 3f1bac1923fc412a5f69dcaea4e4dd2a9bb8ef72. Closing this one.
