### ISSUE TITLE
Logging conflict with Plugs that take modules as options after v1.12

### ISSUE THREAD

**Issue by bgentry** [appsignal/appsignal-elixir#546]
## Describe the bug

After upgrading to absinthe-elixir v1.12, we began to see these errors logged in our tests:

```
[error] Handler "appsignal_phoenix_event_handler" has failed and has been detached. Class=:error
Reason=%ArgumentError{message: "cannot convert the given list to a string.\n\nTo be converted to a string, a list must either be empty or only\ncontain the following elements:\n\n  * strings\n  * integers representing Unicode code points\n  * a list containing one of these three elements\n\nPlease check the given list or call inspect/1 to get the list representation, got:\n\n[schema: MyApp.Web.GraphQL.Schema]\n"}
Stacktrace=[{List, :to_string, 1, [file: 'lib/list.ex', line: 925]}, {Appsignal.Phoenix.EventHandler, :handle_event, 4, [file: 'lib/appsignal/phoenix/event_handler.ex', line: 29]}, {:telemetry, :"-execute/3-fun-0-", 4, [file: '/home/actions/actions-runner/_work/my_app/my_app/deps/telemetry/src/telemetry.erl', line: 123]}, {:lists, :foreach, 2, [file: 'lists.erl', line: 1338]}, {Phoenix.Router, :__call__, 2, [file: 'lib/phoenix/router.ex', line: 281]}, {MyApp.Endpoint, :plug_builder_call, 2, [file: 'lib/my_app/endpoint.ex', line: 1]}, {MyApp.Endpoint, :call, 2, [file: 'lib/my_app/endpoint.ex', line: 1]}, {Phoenix.ConnTest, :dispatch, 5, [file: 'lib/phoenix/test/conn_test.ex', line: 235]}, {MyApp.GraphQLHelper, :graphql_query, 3, [file: 'test/support/graphql_helper.ex', line: 11]}, {MyApp.Test.Utils.Package, :import_package_cache, 4, [file: 'test/support/utils/package.ex', line: 111]}, {MyApp.MultiLicenseTransferImportTest, :__ex_unit_setup_1, 1, [file: 'test/controllers/multi_license_transfer_import_test.exs', line: 40]}, {MyApp.MultiLicenseTransferImportTest, :__ex_unit__, 2, [file: 'test/controllers/multi_license_transfer_import_test.exs', line: 1]}, {ExUnit.Runner, :exec_test_setup, 2, [file: 'lib/ex_unit/runner.ex', line: 348]}, {ExUnit.Runner, :"-spawn_test_monitor/4-fun-0-", 2, [file: 'lib/ex_unit/runner.ex', line: 307]}, {:timer, :tc, 1, [file: 'timer.erl', line: 166]}, {ExUnit.Runner, :"-spawn_test_monitor/4-fun-1-", 4, [file: 'lib/ex_unit/runner.ex', line: 306]}]
```

Apologies for the lack of line breaks, but that's how the error comes in and I didn't want to obscure the original. The relevant bit is that AppSignal's Phoenix EventHandler [is trying to stringify](https://github.com/appsignal/appsignal-elixir/blob/8d71916de72df6aba1cc8f222d047fcb6891685b/lib/appsignal/phoenix/event_handler.ex#L29) two options provided by Plug: `:plug` and `:plug_opts`. Here is the relevant part of the above error, formatted for readability:

```
cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[schema: MyApp.Web.GraphQL.Schema]
```

In our case, we are using `Absinthe.Plug` per [its instructions](https://github.com/appsignal/appsignal-elixir/blob/8d71916de72df6aba1cc8f222d047fcb6891685b/lib/appsignal/phoenix/event_handler.ex#L29):

```elixir
forward("/", Absinthe.Plug, schema: MyApp.Web.GraphQL.Schema)
```

The `:plug_opts` value AppSignal is attempting to log is the last part of that command: `schema: MyApp.Web.GraphQL.Schema`. This fails because that list is not inherently able to be stringified.

In my case, I was able to workaround this by dropping the plug's options entirely because it has the ability to pull that schema value from the config directly: `config :absinthe, schema: MyApp.Web.GraphQL.Schema`. However it appears this still represents a flaw in appsignal-elixir, which is that a perfectly valid plug usage can break error reporting.

## To Reproduce

- Using AppSignal for Elixir package version 1.12.0
- In this code:
  ```elixir
  forward("/", Absinthe.Plug, schema: MyApp.Web.GraphQL.Schema)
  ```

**Comment by ckruse** [comment]
I noticed the same problem.

**Comment by jeffkreeftmeijer** [comment]
Hey @bgentry and @ckruse,

Thanks for reporting this issue and writing such a thorough explanation. I've been looking into this today, and pushed a fix to the [plug-with-opts](https://github.com/appsignal/appsignal-elixir/tree/plug-with-opts) branch that should make sure any router dispatches that don't have atoms as their plug_opts are ignored. This should make sure the event handler isn't detached.

We're testing this patch internally, so we can release it as 1.12.1 soon. If you have time, could you try this branch in your apps, and let us know if this fixed the issue for you?

For anyone else reading along running into the same problem; it'd be great if you could test the patch in your apps as well. Otherwise, please revert back to version 1.11.8, which doesn't have this issue, until we release 1.12.1.

Thanks again!

**Comment by maartenvanvliet** [comment]
We ran into the same issue. The `plug-with-opts` branch seems to fix it. Thanks!

**Comment by ckruse** [comment]
It seems to fix it for me, too 👍 thanks!

**Comment by opsb** [comment]
Would really appreciate this being merged into master or even released. I'm a bit reticent about pointing the deps to a branch which may disappear at any time.

**Comment by jeffkreeftmeijer** [comment]
Hey @bgentry, @ckruse, @maartenvanvliet and @opsb!

We've just released version 1.12.1 of the AppSignal for Elixir integration, which is identical to the `plug-with-opts` branch. Could you all upgrade to that version and let us know if you run into any issues?

We'll keep the branch available for the time being, but please upgrade to the released version if you get a chance. 

Thanks again for your help fixing this issue!

**Comment by opsb** [comment]
many thanks for the swift turnaround!

**Comment by opsb** [comment]
Have switched to 1.12.1, working fine for us

**Comment by bgentry** [comment]
@jeffkreeftmeijer all good here, thanks! :v:
