### ISSUE TITLE
:instrumenters configuration for MyAppWeb.Endpoint is deprecated and has no effect

### ISSUE THREAD

**Issue by oliver-kriska** [appsignal/appsignal-elixir#556]
Hello,

looks like :instrumenters config for endpoint is going to be removed in the latest version of Phoenix.  I got this warning:
```
[warn] :instrumenters configuration for MyAppWeb.Endpoint is deprecated and has no effect
```
So I think this has to be changed in your installation guide for Phoenix:
```
instrumenters: [Appsignal.Phoenix.Instrumenter]
```

I just upgraded to the latest version of Phoenix with this [upgrade guide](https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f)
My stack:
```
Elixir 1.10.2 
Erlang/OTP 22 [erts-10.6.2]
phoenix 1.5.1
phoenix_ecto 4.1.0
phoenix_html 2.14.1
phoenix_live_reload 1.2.1
phoenix_live_view 0.12.1
phoenix_pubsub 2.0.0
plug 1.10.0
plug_cowboy 2.2.1
cowboy 2.7.0
appsignal 1.12.1
```

**Comment by marciotoze** [comment]
Hi, that's not an bug :)

Just remove the `instrumenters: [Appsignal.Phoenix.Instrumenter]` line and use appsignal-elixir on version 1.12.0 (or above).

you can see more info into [changelog](https://github.com/appsignal/appsignal-elixir/blob/develop/CHANGELOG.md#1120) or [in this blog post](https://blog.appsignal.com/2020/03/03/elixir-package-1-12.html)

**Comment by jeffkreeftmeijer** [comment]
Hey @oliver-kriska, 

That's right. We've added Phoenix 1.5 support through our new Telemetry hook in Appsignal for Elixir 1.12. After upgrading to that, you can safely remove the instrumenters configuration option from your config file.

Thanks for your help here, @marciotoze! :) 

Best,
— Jeff
