### ISSUE TITLE
Relax version requirements for phoenix_live_view

### ISSUE THREAD

**Issue by ckruse** [appsignal/appsignal-elixir#557]
Currently the `phoenix_live_view` version requirement is `~> 0.9.0`; this collides with `phoenix_live_dashboard`, which has a version requirement of `~> 0.12.0`. Is it possible to relax the requirements to `~> 0.9`? (Hence the missing `.0`)

**Comment by jeffkreeftmeijer** [comment]
Hey @ckruse,

Good call! We're reviewing #558, which we're hoping to release as soon as possible to address this. Thanks for reaching out!

**Comment by jeffkreeftmeijer** [comment]
Hey @ckruse,

We've released version 1.13.1 of the package, which includes the fix for the live_view dependency. Please let us know if you run into anything else!
