### ISSUE TITLE
Erlang/OTP 23.0 Compatibility

### ISSUE THREAD

**Issue by fekle** [appsignal/appsignal-elixir#562]
## Describe the bug

Hi, Erlang/OTP 23.0 was just released, and Elixir 1.10.3 seems to be compatible: https://twitter.com/elixirlang/status/1260556559165292544

However, when deploying my app, I'm getting an error from AppSignal:
```shell
warning: Error loading NIF (Is your operating system (x86_64-pc-linux-musl) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
Failed to load NIF library: 'Error loading shared library /app/lib/appsignal-1.13.1/priv/appsignal_extension.so: No such file or directory'
   (appsignal 1.13.1) lib/appsignal/nif.ex:48: Appsignal.Nif.init/0
   anonymous fn/1 in :init.run_on_load_handlers/2
```

I've checked the docs mentioned in the error message, and `Alpine 1.10.3` should be supported.

When building, `mix deps.compile` fails (but doesn't abort), yielding the following:

```shell
AppSignal installation failed: {:error, {:error, {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}}}
```

Looks like this could be due to the removal of SSL 3?
See https://www.erlang.org/news/140
> SSL:
>    Support for SSL 3.0 is completely removed.
>    TLS 1.3 is added to the list of default supported versions.

## To Reproduce

- Using AppSignal for Elixir package version 1.13.1
- In my app using framework/library phoenix version 1.5.1
- Using docker image `hexpm/elixir:1.10.3-erlang-23.0-alpine-3.11.3`
  - With the image `hexpm/elixir:1.10.3-erlang-22.3-alpine-3.11.3` all works fine.

I'm aware that Erlang/OTP 23 is brand new and contains quite a few breaking changes, so no sweat :)

**Comment by fekle** [comment]
Update: The issue seems to stem from hackney - installing hackney from the master branch resolves the issue (`{:hackney, git: "https://github.com/benoitc/hackney.git", branch: "master"}`).
I guess we'll have to wait for a new version of hackney to be released, as installing a master isn't really a solution for production.

**Comment by fschuindt** [comment]
FYI last hackney release was on Sep 25, 2019. I wonder how long it would take.

**Comment by lukaszsamson** [comment]
macos 10.15.5 is also affected

**Comment by bgentry** [comment]
FYI Hackney v1.16.0 was released 14 days ago and supposedly contains the necessary fixes for this: https://github.com/benoitc/hackney/releases/tag/1.16.0

**Comment by jeffkreeftmeijer** [comment]
Thanks for chiming in, everybody. I'm closing this, as we don't see this issue with Hackney 1.16 anymore. Please `mix deps.update hackney` if you run into this issue.
