### ISSUE TITLE
2.0 beta and Absinthe plug

### ISSUE THREAD

**Issue by strzibny** [appsignal/appsignal-elixir#581]
Hello,

I am currently using an Absinthe plug as follows:

```
defmodule Digi.Plugs.AppsignalAbsinthePlug do
  alias Appsignal.Transaction
  use Appsignal.Instrumentation.Decorators

  def init(_), do: nil

  @decorate transaction_event("absinthe")
  @path "/api/"
  def call(%Plug.Conn{request_path: @path, method: "POST"} = conn, _) do
    Transaction.set_action("POST " <> @path)
    conn
  end

  def call(conn, _) do
    conn
  end
end
```
And in endpoint.ex:

```
plug Digi.Plugs.AppsignalAbsinthePlug
```
But ` Appsignal.Transaction.set_action` is not available anymore.

What's the replacement? Is it no longer needed?

**Comment by jeffkreeftmeijer** [comment]
Hey @strzibny,

That's correct. We've removed the `Appsignal.Transaction` in favour of `Appsignal.Span`. In the new version, we provide a function to override the action name named `Appsignal.Plug.put_name/2`. In your example, you'd call it like this:

``` elixir
@path "/api/"
def call(%Plug.Conn{request_path: @path, method: "POST"} = conn, _) do
  Appsignal.Plug.put_name(conn, "POST " <> @path)
end
```

I've also updated the documentation for this in https://github.com/appsignal/appsignal-elixir-plug/pull/3, to make this clearer in the future. Could you try this and let me know if you run into any issues?

Best,
-- Jeff
