### ISSUE TITLE
Undefined handle_info warnings

### ISSUE THREAD

**Issue by anronin** [appsignal/appsignal-elixir#590]
Hi there, i've upgraded to 2.0 and getting tons of this in my logs:

```
** [warning] Undefined handle_info in 'Elixir.Appsignal.Error.Backend'
** Unhandled message: {io_reply,#Ref<0.3002323228.2069889025.15981>,ok}
```
Not sure from where it coming but after some investigate i've find out that Appsignal.Error.Backend needs to ignore some messages to behave like :gen_event.

### Environment
- appsignal_phoenix, "~> 2.0.0"
- phoenix, "~> 1.5.6"
- elixir 1.11.2

I will send fix for this soon.

**Comment by anronin** [comment]
actually this is the cause of these messages https://erlang.org/doc/apps/stdlib/io_protocol.html

**Comment by akashsethiya** [comment]
I am also facing the same issue after upgrading to 2.0....Any workaround for now?

**Comment by anronin** [comment]
@akashsethiya, one way is to remove `Appsignal.Error.Backend` from logger by adding `Logger.remove_backend(Appsignal.Error.Backend)` to `MyApp.Application` module, another is forking this repo and applying this patch

**Comment by jeffkreeftmeijer** [comment]
We're reviewing a patch for this in #594, based on the work done by @anronin in #591. For anyone running into this issue, please switch to the unhandled-messages branch, and let us know if you run into any issues. We'll work on getting a patch out as soon as possible.
