### ISSUE TITLE
Empty backtrace

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-elixir#597]
Sometimes stack trace part of our errors is empty making it difficult to troubleshoot the error.

![image](https://user-images.githubusercontent.com/5089055/100591778-0caf9f80-3318-11eb-87da-603a526da092.png)

Internal discussions
Basecamp: https://3.basecamp.com/4738529/buckets/18205087/messages/3181330325
Intercom: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700015723

**Comment by thijsc** [comment]
Customer reported that it started working again for him in 1.11.

**Comment by atonse** [comment]
Hi I believe I'm the customer :-) (unless you have others reporting this). I can't really send you guys our app's source code but if you ever do need to do a zoom call where you'd like to see our code and how we've set things up to help you troubleshoot, I'm happy to do that. We can even log on to the server if you wanted to check if directory permissions or something might be an issue. (Anything that AppSignal diagnose wouldn't tell you, of course)

**Comment by jeffkreeftmeijer** [comment]
We have a support thread running for this. Closing this one to continue there.
