### ISSUE TITLE
Create a broadway integration package

### ISSUE THREAD

**Issue by btkostner** [appsignal/appsignal-elixir#598]
Similar to `appsignal_phoenix` and `appsignal_plug`, there should be an `appsignal_broadway` package. 

Ideally this would automatically start a transaction on every message being handled, and automatically track errors that happen during processing. It would be awesome if it automatically plugged into the telemetry data and created a dashboard for you.

**Comment by btkostner** [comment]
Sorry for the wrong template / label. I didn't see anything for feature requests.

Also, I'd be happy to work on a repo for this with a little guidance, and transfer it to you once it's done.

**Comment by jeffkreeftmeijer** [comment]
Hey @btkostner,

Thanks for bringing this up! We’d love to add to our integrations, and Broadway certainly is a good candidate. We haven’t yet decided what to pick up next, and we don’t know when we’ll get to it, though. I’ll discuss planning some time to look into this in the next integrations team meeting. 

In the meantime, if you’re building something like this for your own app, I’d suggest checking out the [custom integrations guide](https://docs.appsignal.com/elixir/instrumentation/instrumentation.html). Also, the [channel instrumentation in appsignal_phoenix](https://github.com/appsignal/appsignal-elixir-phoenix/blob/main/lib/appsignal_phoenix/channel.ex) might be a good example. 

Feel free to reach out any time through this issue or [support](mailto:support@appsignal.com), and I’ll try to be of help. :)
