### ISSUE TITLE
No easy way to instrument async code in 2.0

### ISSUE THREAD

**Issue by lukaszsamson** [appsignal/appsignal-elixir#601]
In 2.0 there is no easy way to instrument async code any more. In 1.x this pattern used to work
```
@decorate transaction()
def instrumented do
  parent = self()
  task = Task.async(fn ->
    Appsignal.Instrumentation.Helpers.instrument(parent, "some name", "some category", fn ->
      do_async_work()
    end)
  end)

  Task.await(task)
end
```
The deprecated `Appsignal.Instrumentation.Helpers.instrument/4` most likely no longer works as it is not using the first argument at all.
I went over the documentation, upgrade guide, examples and tests in this repo and found nothing related to `async`.

**Comment by jeffkreeftmeijer** [comment]
Hey @lukaszsamson,

Thanks for reaching out! We’re updating the documentation for this, but here’s a code sample that should work:
 
``` elixir
  def index(conn, _params) do
    current = Appsignal.Tracer.current_span() 
    fn -> 
      span = "http_request"                                                     
      |> Appsignal.Tracer.create_span(current)                
      |> Appsignal.Span.set_name("name")     
      |> Appsignal.Span.set_attribute("appsignal:category", "category")
      :timer.sleep(1000) 
      Appsignal.Tracer.close_span(span) 
    end 
    |> Task.async() 
    |> Task.await() 
    render(conn, "index.html")
  end
```

If you can pass the current span into the new process, you can start a new child span in there. Like before, you’ll need to make sure to await your Task here, otherwise the nested process doesn’t show up.

Does that help you get a step further?

**Comment by lukaszsamson** [comment]
> Does that help you get a step further?

Yes, thank you.

**Comment by jeffkreeftmeijer** [comment]
Awesome. Feel free to reach out through support or reopen this issue if we can be of more help, here. We’ll get that documentation updated!
