### ISSUE TITLE
Update Changelog link for package

### ISSUE THREAD

**Issue by joetrimble** [appsignal/appsignal-elixir#602]
When reviewing the most recent update on Hex I noticed the Changelog link is pointing to the old master branch. This should probably be updated to main as that is set as the default branch.

## TODO

- [ ] Update the Changelog link in the `package` function inside the mix.exs file. New link should be for main instead of master.

**Comment by jeffkreeftmeijer** [comment]
Hey @joetrimble,

Great find! Updated in https://github.com/appsignal/appsignal-elixir/commit/bdc5435d80e6f376b7f473777e66c1195b967492. It’ll be fixed on Hex after the next release. Thanks!
