### ISSUE TITLE
Support for parallel Ecto preloads

### ISSUE THREAD

**Issue by thijsc** [appsignal/appsignal-elixir#603]
Ecto can preload data using separate tasks. Currently we don't connect those spans to the span above, so this detail is lost. It would be good if these could be tracked.

As reported [here](https://elixirforum.com/t/help-understanding-ecto-telemetry-events-according-to-appsignal/35957) on the Elixir forum.

**Comment by JMurphyWeb** [comment]
This would be much appreciated!

**Comment by crbelaus** [comment]
This would be a big improvement. At work we are currently fighting with slow queries and they aren't easy to track as some of them come from preloads and they are not connected to the parent unit of work in AppSignal.
