### ISSUE TITLE
Performance tab - Query.MyApp.Repo now treated as an event

### ISSUE THREAD

**Issue by JMurphyWeb** [appsignal/appsignal-elixir#605]
<img width="800" alt="Screenshot 2020-12-11 at 11 59 41" src="https://user-images.githubusercontent.com/12638261/101895894-70538b80-3ba8-11eb-8082-8128e6e582b4.png">

## Describe the bug

See screenshot.

Since upgrade to 2.0 I am seeing Ecto.Query in my slow events blowing the stats completely off.

Is this intentional?

**Comment by anronin** [comment]
hey @JMurphyWeb! try to update to 2.0.5 version, seems they fixed this

**Comment by jeffkreeftmeijer** [comment]
That’s correct! We’ve released version 2.0.5, which no longer instruments queries that don’t have a wrapper span. That means you shouldn’t see query-only samples anymore after upgrading. 

Please let us know if that doesn’t resolve your issue!

**Comment by JMurphyWeb** [comment]
@jeffkreeftmeijer I think I opened this issue in the wrong repo.. I amon the latest appsignal-phoenix version (2.0.2)

https://github.com/appsignal/appsignal-elixir-phoenix/releases
