### ISSUE TITLE
Feature Request: performance tab - collapsible events

### ISSUE THREAD

**Issue by JMurphyWeb** [appsignal/appsignal-elixir#617]
It would be useful to be able to show events that have a parent event as collapsed (optionally by default)

Here is an example of how just a few DB calls and their associated preloads can become unwieldy - if they were collapsed by default the timeline would be more digestible:

<img width="125" alt="Screenshot 2021-01-07 at 10 55 06" src="https://user-images.githubusercontent.com/12638261/103884938-31e1bb80-50d7-11eb-8f8e-11847dab7ed8.png">

**Comment by thijsc** [comment]
Thanks for this great feedback. I made a note of it. Closing this issue since we don't track product feature requests in this repo.
