### ISSUE TITLE
Feature request: event timeline should stay fixed to top on scroll

### ISSUE THREAD

**Issue by JMurphyWeb** [appsignal/appsignal-elixir#618]
As soon as I have to scroll from the top of the event table, I lose the timeline across the top of the table:
<img width="2099" alt="Screenshot 2021-01-07 at 11 01 21" src="https://user-images.githubusercontent.com/12638261/103885392-db28b180-50d7-11eb-86da-560064dd0d35.png">
<img width="2115" alt="Screenshot 2021-01-07 at 11 01 36" src="https://user-images.githubusercontent.com/12638261/103885397-dd8b0b80-50d7-11eb-9c20-4d8770644fe4.png">

Which makes it difficult to understand what sort of duration gaps in the events represent:
<img width="2119" alt="Screenshot 2021-01-07 at 11 04 48" src="https://user-images.githubusercontent.com/12638261/103885711-55f1cc80-50d8-11eb-88c2-7d60adfd44fb.png">

It might be handy if the the timeline stayed fixed to the top of the table on scroll:
<img width="2082" alt="Screenshot 2021-01-07 at 11 03 06" src="https://user-images.githubusercontent.com/12638261/103885544-15924e80-50d8-11eb-8671-f29a3170bcde.png">

**Comment by thijsc** [comment]
Thanks for this great feedback. I made a note of it. Closing this issue since we don't track product feature requests in this repo.
