### ISSUE TITLE
Closing a span on halt

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-elixir#619]
Halting the response leads to the rest of the plugs not being called anymore, so the parent span is never closed. The child span which _is_ closed therefore gets dropped.

Can we get the span closed if it halts?

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700020096

**Comment by jeffkreeftmeijer** [comment]
I’ve [prepared an example](https://github.com/appsignal/test-setups/commit/e20e68f8223b9037b9220dd3a0a7f3580a29adef), which is a Phoenix app with a Plug named `HaltPlug`. It returns early and then halts when requesting the `/halt` path.

It’s still registering the span for me, as we wrap the whole `call/2` in our instrumentation. If you return early and skip part of the pipeline, we’ll still record the sample.

I’m closing this for now. Please feel free to reopen if this doesn’t match the described use case.
