### ISSUE TITLE
How I can to disable ecto telemetry in 2.* ?

### ISSUE THREAD

**Issue by mikanoz** [appsignal/appsignal-elixir#621]
In the docs I see only that it configured automatically for all repos from the config by ecto_repos: [MyApp.Repo].
I would to skip the telemetry for Ecto in my app.
Thank you!

**Comment by jeffkreeftmeijer** [comment]
Hey @mikanoz,

To disable the whole Ecto instrumentation, you can pass an empty list to the `ecto_repos` configuration option in the AppSignal configuration:

``` elixir
config :appsignal, :config,
  ecto_repos: []
```

Could you try that and let me know if that works for you? I’ll be sure to make note of this in the docs.

**Comment by mikanoz** [comment]
Hey @jeffkreeftmeijer!

Oh, it works, thanks!
So great.

Regarding docs (maybe this will help),
I seen that Ecto is mentioned only on this page: https://docs.appsignal.com/elixir/integrations/ecto.html:
Here I understand that appsignal fetch `ecto_repos` list only from an `:my_app` config section, but not from `:appsignal` section.

`ecto` was not mentioned on the `options` page (https://docs.appsignal.com/elixir/configuration/options.html)

If I skipped something another, sorry me for that :)

**Comment by jeffkreeftmeijer** [comment]
We’ve added the `ecto_repos` option to the documentation: https://docs.appsignal.com/elixir/configuration/options.html#option-ecto_repos. Thanks again for letting us know about this!
