### ISSUE TITLE
app signal can not parse error

### ISSUE THREAD

**Issue by MeterSoft** [appsignal/appsignal-elixir#625]
i have error in this line https://github.com/appsignal/appsignal-elixir/blob/98e253e9484a8c6a07b3d512f54856448d9f1b1a/lib/appsignal/probes/probes.ex#L57
`protocol String.Chars not implemented for %ErlangError{original: :notsup}`

i think we should do `inspect(e)`

**Comment by jeffkreeftmeijer** [comment]
Hey @MeterSoft, thanks for letting us know about this. We’re reviewing a patch in #626, which should resolve this error, which is planned to be included in the next release. If you can still produce errors like this, could you try the `probes-atom-errors` branch to see if that resolves your issue?

**Comment by MeterSoft** [comment]
@jeffkreeftmeijer hi, yes, this fix resoled problem. Can you let know when release with this will?

**Comment by jeffkreeftmeijer** [comment]
Hey @MeterSoft, thanks for trying the patch. We’ve just released version 2.1.1 of Appsignal for Elixir, which includes that patch. Could you try upgrading and letting us know if you run into any issues?
