### ISSUE TITLE
Unable to compil in elixir:1.8.1-alpine

### ISSUE THREAD

**Issue by iteron-yasir** [appsignal/appsignal-elixir#627]
Can't able to compile the dependency `mix deps.compile`

`==> appsignal
Downloading agent release from https://appsignal-agent-releases.global.ssl.fastly.net/690f4b8/appsignal-x86_64-linux-musl-all-static.tar.gz
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:invalid, {:error, {:error, :nxdomain}}}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    mix_helpers.exs:521: Mix.Appsignal.Helper.write_report_file/2
    mix_helpers.exs:550: Mix.Appsignal.Helper.abort_installation/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
`

My current environment
Docker image: elixir:1.8.1-alpine
Erlang: 21.3.8
AppSignal version: 1.10.13

**Comment by shairyar** [comment]
Hi there,

Could you please re-try and let us know if you are still running into the problem?

I noticed that you are using the version 1.x, the latest version is 2.x, could you please upgrade to the latest version?

**Comment by iteron-yasir** [comment]
Thanks for the response. I've solved the issue. The issue is with my network nameserver. I have changed my system name server to 1.1.1.1. Now it's working.
