### ISSUE TITLE
[debug] Appsignal.Phoenix.View attached to Elixir.xxx

### ISSUE THREAD

**Issue by reneweteling** [appsignal/appsignal-elixir#634]
## Describe the bug

When compiling appsignal output the following debug messages, my guess is that there is a flag on that should be off:

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/3830933/106576991-1a62ea80-653e-11eb-9a9c-e32c1e64768a.png">

## To Reproduce

- Using AppSignal for Elixir package version 2.1.3
appsignal 2.1.3
appsignal_phoenix 2.0.4
appsignal_plug: 2.0.6
- In my app using framework/library ... version
phoenix 1.5.7
elixir: 1.11, otp 23

**Comment by cblavier** [comment]
is there a way to disable those logs? (and still keeping the remaining of my app in debug log level)

**Comment by jeffkreeftmeijer** [comment]
The current way to disable these is to raise your log level, so there’s currently no way to not print these while still keeping the log level on debug. We’re looking into finding a smart way to move these out without removing them altogether, as these are proving helpful in debugging apps for us. We’ll keep you posted on this here.

**Comment by cblavier** [comment]
I get it thanks!
It's a non-blocking issue, but when coding I'm 99% of the time in debug level mode, and it's quite annoying to get 50+ lines of AppSignal debug each time I spin up my server.

**Comment by lpil** [comment]
Can we change these to TRACE at least? It's very noisy, and it's unusual for an Elixir library to log when `use`d

**Comment by jeffkreeftmeijer** [comment]
Hey all, thanks for chiming in! We’re still looking for a nicer way to handle debug logging across our integrations. In the meantime, we’ve made sure to only print these logs when configuring debug mode in your AppSignal configuration, meaning these are now disabled by default. To get rid of the log lines, please update to the latest version of `appsignal_phoenix`, `appsignal_plug` or `appsignal`.

**Comment by lpil** [comment]
That was fast! Thank you
