### ISSUE TITLE
slow api requests and queries

### ISSUE THREAD

**Issue by MeterSoft** [appsignal/appsignal-elixir#638]
i use appsignal 2.1.1
but it not show we queries and slow api requests.
In DB i have this
```
:telemetry.attach(
      "appsignal-ecto",
      [:apps, :my_app, :repo, :query],
      &Appsignal.Ecto.handle_event/4,
      nil
    )
```

**Comment by tombruijn** [comment]
Hi @MeterSoft, can you contact us at support@appsignal.com with this question?
