### ISSUE TITLE
Appsignal 2.0 has barely any documentation

### ISSUE THREAD

**Issue by whatyouhide** [appsignal/appsignal-elixir#640]
Hey friends, it looks like a lot of the new Appsignal 2.0 APIs have **no** documentation (see https://github.com/appsignal/appsignal-elixir/blob/0c46f01e0bcb2b02110392eea9e3e78318138fd4/lib/appsignal/span.ex for one of the examples).

I think this is a bug so I filed it as a bug. Is there any reason for this?

Steps to reproduce the behavior: look at the docs :)

Version: 2.x and master.

**Comment by LostKobrakai** [comment]
Just had the same experience trying to integrate appsignal with oban.

**Comment by jeffkreeftmeijer** [comment]
Hey @whatyouhide,

Thanks for raising this issue. Although the Span API is open, we usually recommend using the [instrumentation helpers](https://docs.appsignal.com/elixir/instrumentation/instrumentation.html) for instrumenting parts of your application outside of our Plug and Phoenix integration.

I agree we can do a better job at adding documentation for these modules, and we'll look into that in the coming period.

In the meantime, feel free to reach out through support, we're happy to help with any question you might have. That should also help us to figure out which parts of the API could use some more work.

**Comment by whatyouhide** [comment]
Hey @jeffkreeftmeijer thanks for your answer!

The instrumentation helpers, if I get things right, will not help us when dealing with start/stop Telemetry-style events. In those cases, you handle Telemetry events through callbacks such as

```elixir
def handle_event([:redix, :something, :start], ...) do
  # Before, I called Appsignal.Transaction.start_event()
end

def handle_event([[:redix, :something, :stop, ...], ...) do
  # Before, I called Appsignal.Transaction.finish_event() or whatever was the name :P
end
```

To replicate the behavior above, it looks like I ought to use spans. Am I misunderstanding something?

Thanks! 💟

**Comment by LostKobrakai** [comment]
I've talked to support and they referred me to the following community implementation for oban, which also uses spans directly.

https://github.com/glific/glific/blob/master/lib/glific/appsignal.ex

**Comment by jeffkreeftmeijer** [comment]
Hey @whatyouhide. For a span to be registered, it’ll need to be opened and closed. We no longer require an explicit “finish” step, like we did for Transactions.

To start a root span, use `Appsignal.Tracer.create_span/2`, then set a name and category. To close it, you’d call `Appsignal.Tracer.close_span/1`:

``` elixir
def handle_event([:redix, :something, :start], ...) do
  Appsignal.Tracer.create_span("background_job", Appsignal.Tracer.current_span())
  |> Appsignal.Span.set_name("name")
  |> Appsignal.Span.set_attribute("appsignal:category", "category”)
end

def handle_event([[:redix, :something, :stop, ...], ...) do
  Appsignal.Tracer.current_span()
  |> Appsignal.Tracer.close_span()
end 
```

@LostKobrakai’s suggestion to check out https://github.com/glific/glific/blob/master/lib/glific/appsignal.ex is a great example as well, indeed! :)

Please let us know if you need any more help, and we’d love to see what you come up with!
