### ISSUE TITLE
missing configuration causes compilation errors for phoenix projects on v2.1.5

### ISSUE THREAD

**Issue by the-mikedavis** [appsignal/appsignal-elixir#643]
:wave: hello!

## The bug

It looks like this commit [`c0b0dfb`](https://github.com/appsignal/appsignal-elixir/commit/c0b0dfb1e2feb9b597bab37d54d8a56134ece907) (released as v2.1.5) introduces a compile-time dependency on the configuration of appsignal (e.g. `config :appsignal, name: ..`) for phoenix services.

Prior to this version, a phoenix service author may `use Appsignal.Phoenix` in an endpoint without configuring appsignal at all. With appsgnal v2.1.5, however, attempting to compile a phoenix service without appsignal configuration yields this compilation error:

```
== Compilation error in file lib/asdf_web/endpoint.ex ==
** (ArgumentError) could not fetch application environment :config for application :appsignal because configuration at :config was not set
    (elixir 1.11.0) lib/application.ex:656: Application.fetch_env!/2
    (appsignal 2.1.5) lib/appsignal/config.ex:121: Appsignal.Config.debug?/0
    (appsignal 2.1.5) lib/appsignal/logger.ex:11: Appsignal.Logger.debug/1
    lib/asdf_web/endpoint.ex:4: (module)
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.0) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

## To Reproduce

I have an example repository here: https://github.com/the-mikedavis/appsignal-compile-time-example-repo and the README has step-by-step instructions.

The TL;DR:

- generate a fresh phoenix project
- add `{:appsignal, "~> 2.1"}` and `{:appsignal_phoenix, "~> 2.0"}` to the dependencies
- add `use Appsignal.Phoenix` to the project's endpoint
- do not add anything to the configuration
- get deps and compile!

## Workarounds

Very minimally, one may get around this by adding the missing configuration such as

```elixir
# config/config.exs
config :appsignal, active: false
```

Or one may pin the prior version of appsignal

```elixir
# mix.exs

  def deps do
    [
      {:appsignal, "== 2.1.4"}
      ..
```

## Potential fix

The issue seems to be with this bit of code which gets executed at compile-time:

```elixir
# lib/appsignal/config.ex

  ..

  @doc """
  Returns true if debug mode is turned on, false otherwise.
  """
  @spec debug?() :: boolean
  def debug? do
    Application.fetch_env!(:appsignal, :config)[:debug] || false
  end
```

Changing to a `Application.get_env/3` gives some nice behavior:

```elixir
  @doc """
  Returns true if debug mode is turned on, false otherwise.
  """
  @spec debug?() :: boolean
  def debug? do
    Application.get_env(:appsignal, :config, [])[:debug] || false
  end
```

Or maybe even better, we can default to the `@default_config` defined at the top of `lib/appsignal/config.ex`!

```elixir
  @doc """
  Returns true if debug mode is turned on, false otherwise.
  """
  @spec debug?() :: boolean
  def debug? do
    Application.get_env(:appsignal, :config, @default_config)[:debug] || false
  end
```

I'd be happy to submit a PR; of course you may beat me to the punch line and do it yourself :slightly_smiling_face:

**Comment by tombruijn** [comment]
Hi @the-mikedavis, I have confirmed the issue. I'll have a look at your PR!
