### ISSUE TITLE
Failure to download agent release does not fail compilation

### ISSUE THREAD

**Issue by validere-ben** [appsignal/appsignal-elixir#679]
## Describe the bug

~It appears that prior to 015a6e6305e1d390cd18c95bc96cf5249265f873, failure to download/verify the agent successfully would raise a `Mix.Error` in `mix_helpers.exs` however a stderr message is just printed now, with a 0 return code.~ This seems to like an issue that would have been present prior to the above commit at a closer look. 

`mix_helpers.exs` only prints a  stderr message and exits with a 0 return code if the agent download itself fails.

Is this intended behaviour? Failure to download the agent during the build step of an application will not raise and one will not be aware of the missing agent unless they inspect their build logs and/or are notified of the failure to load the nif at runtime in the application logs.

## To Reproduce

- Using AppSignal for Elixir package version 2.2.1
- Elixir 1.12.1
- Erlang/OTP 24.0.2

This is a bit of an edge case and as a result of a one-off issue where the hackney request for the agent was closed. i.e.

![Screen Shot 2021-09-17 at 11 55 00 AM](https://user-images.githubusercontent.com/28610765/133818505-73447a24-c8c7-4e0d-ae6c-17b2d7e5d34b.png)

**Comment by jeffkreeftmeijer** [comment]
Hey Ben,

We no longer raise an error when we fail to download the agent to allow apps to compile even if the agent can’t be installed for some reason. The Nif then doesn’t get loaded, but AppSignal should then automatically use the fallback functions. This should then allow the app to run as normal, but without AppSignal’s instrumentation. We should also print a warning to the console when building, so anyone running into this issue knows that the extension wasn’t installed properly.

From your report, there seem to be two issues;

1. The Nif fails to load, causing an error that prevents your app from starting. That’s a problem we should look into to be able fulfill the promise outlined above.
2. The warning is easily missed. We should print a clear warning that shows the user what happened to avoid confusion.

We’ll look into both of these, and we’ll report back. Thanks for letting us know about this!

**Comment by validere-ben** [comment]
@jeffkreeftmeijer 

Ah I see, if this is the intended behaviour then everything seems in order. It just seemed odd to continue compilation when instrumentation would be non-functional.

1. The nif failing to load doesn't prevent the application from starting in this case
2. There is currently error-level logging when this happens i.e.

```
Failed to start AppSignal. Please run the diagnose task (https://docs.appsignal.com/elixir/command-line/diagnose.html) to debug your installation.

anonymous fn/1 in :init.run_on_load_handlers/2

(appsignal 2.2.1) lib/appsignal/nif.ex:23: Appsignal.Nif.init/0

Failed to load NIF library: '/opt/app/lib/appsignal-2.2.1/priv/appsignal_extension.so: cannot open shared object file: No such file or directory'
```

I'll go ahead and close this issue, thanks for the response!

**Comment by jeffkreeftmeijer** [comment]
Ah, I misread your initial comment thinking it didn’t fail on compiling the agent but then compiled when running. Thanks for clarifying.

We’re open for improvements on this, as we understand this can be a bit confusing, but we’d prefer not to break compilation when something fails on our end.
