### ISSUE TITLE
Add scheduler utilization to Erlang magic dashboard

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#685]
https://blog.appsignal.com/2020/02/04/elixir-monitoring-erlangvm-with-magic-dashboards.html
https://erlang.org/doc/apps/observer/observer_ug.html

- [x] Report scheduler utilization (https://github.com/appsignal/appsignal-elixir/blob/main/lib/appsignal/probes/erlang_probe.ex)
- [ ] Add to magic dashboard (https://github.com/appsignal/public_config/)

**Comment by unflxw** [comment]
Due to the changes to the minutely probes introduced in the appsignal-elixir PR, this documentation page needs to be amended: https://docs.appsignal.com/elixir/instrumentation/minutely-probes.html
