### ISSUE TITLE
Config gets reset on hot upgrade

### ISSUE THREAD

**Issue by arjan** [appsignal/appsignal-elixir#71]
When a node is hot-upgraded using an appup, the Appsignal configuration gets reset to how it was defined in the config. This is according to how releases work but it loses all "calculated" config properties (default values; values derived from the OS env) that gets set in the `Config.initialize()` call.

We should find a way to call `Config.initialize()` again after a hot upgrade.

cc @danielwillemse @jeffkreeftmeijer

**Comment by arjan** [comment]
It seems this would boil down to implementing a `config_change/3` function in `appsignal.ex`.

**Comment by arjan** [comment]
I think we should detect whether the config has changed enough to restart the agent (e.g. changed API key), or stop the agent entirely.
Maybe always stopping the agent and then initializing again is good enough, as this won't happen that frequently anyway.

**Comment by thijsc** [comment]
This is already handled by the agent automatically. You can just call start with whatever is the current config and the agent will only reboot if something changed since the last start.

**Comment by arjan** [comment]
so calling `appsignal_stop()` is unnessecary? Just call `appsignal_start()` again?

**Comment by thijsc** [comment]
`appsignal_stop` will just make sure everything is flushed to the agent once a process stops. It doesn't actually stop the agent. I think these function names could be clearer.

You do not need to call `appsignal_stop` to make sure the agent picks up a config change.

**Comment by arjan** [comment]
but when the config becomes invalid, or `:active` changes to false, the agent should stop, right? Does it determine that itself?

**Comment by pdilyard** [comment]
I just got the following error after running a hot upgrade:

```
02:13:32.644 [error] Ranch listener RestApi.Endpoint.HTTP had connection process started with :cowboy_protocol:start_link/4 at #PID<0.4330.0> exit with reason: {{%ArgumentError{message: "argument error"}, [{Appsignal.Transaction, :set_request_metadata, 2, [file: 'lib/appsignal/transaction.ex', line: 381]}, {Appsignal.Phoenix, :submit_http_error, 5, [file: 'lib/appsignal/phoenix.ex', line: 67]}, {RestApi.Endpoint, :"call (overridable 2)", 2, [file: 'web/endpoint.ex', line: 43]}, {RestApi.Endpoint, :call, 2, [file: 'web/endpoint.ex', line: 1]}, {Plug.Adapters.Cowboy.Handler, :upgrade, 4, [file: 'lib/plug/adapters/cowboy/handler.ex', line: 15]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 442]}]}, {RestApi.Endpoint, :call, [%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "example.com", method: "GET", owner: #PID<0.4330.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: [], path_params: %{}, peer: {{10, 0, 0, 7}, 32964}, port: 80, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {10, 0, 0, 7}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"x-real-ip", "xx.xx.xx.xx"}, {"host", "example.com"}, {"connection", "close"}, {"cache-control", "max-age=0"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate, sdch"}, {"accept-language", "en-US,en;q=0.8"}, {"cookie", "_ga=GA1.2.1980976560.1474661291"}], request_path: "/", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, []]}}
```

I believe it's related to this issue, because I attached to the console of the running app, ran `Appsignal.Config.initialize/0`, and the error stopped occurring.

This was causing errors on about 25% of web requests, which is obviously not a good thing for monitoring software to be causing...any fix for this would be greatly appreciated.

**Comment by pdilyard** [comment]
Here's another (possibly better) traceback:

```
02:33:51.193 [error] GenEvent handler Appsignal.ErrorHandler installed in :error_logger terminating
** (ArgumentError) argument error
    (appsignal) lib/appsignal/transaction.ex:381: Appsignal.Transaction.set_request_metadata/2
    (appsignal) lib/appsignal/error_handler.ex:55: Appsignal.ErrorHandler.submit_transaction/6
    (appsignal) lib/appsignal/error_handler.ex:40: Appsignal.ErrorHandler.handle_event/2
    (stdlib) gen_event.erl:533: :gen_event.server_update/4
    (stdlib) gen_event.erl:515: :gen_event.server_notify/4
    (stdlib) gen_event.erl:517: :gen_event.server_notify/4
    (stdlib) gen_event.erl:256: :gen_event.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by arjan** [comment]
Yes this is indeed the issue we've been seeing as well. I have a possible fix in f8ddc67935742ce88108accc72d11a07e81e7153 but I still need to reproduce it before I'l merge it, it's hard to unit-test this :) I'll get to it tomorrow.

**Comment by pdilyard** [comment]
@arjan 

Awesome, thanks. Will we be getting a release for this fix by the end of the week, or should I depend on master?

**Comment by arjan** [comment]
Yes we're doing a release in a few hours, actually.
