### ISSUE TITLE
Compiling AppSignal quietly fails

### ISSUE THREAD

**Issue by smt116** [appsignal/appsignal-elixir#714]
I'm hosting the application on Gigalixir. When deploying the code with AppSignal 2.2.7 and AppSignal Phoenix 2.0.13, I see the following errors in the output:

```
==> appsignal
       Downloading agent release
remote: AppSignal installation failed: Could not download archive from any of our mirrors.
remote: Please make sure your network allows access to any of these mirrors.
remote: Attempted to download the archive from the following urls:
remote: - URL: https://appsignal-agent-releases.global.ssl.fastly.net/09308fb/appsignal-x86_64-linux-all-static.tar.gz
remote: - Error (hackney response):
remote: {:error, {:options, {:insufficient_crypto_support, {:"tlsv1.3", {:versions, [:"tlsv1.3", :"tlsv1.2"]}}}}}
remote:
remote: - URL: https://d135dj0rjqvssy.cloudfront.net/09308fb/appsignal-x86_64-linux-all-static.tar.gz
remote: - Error (hackney response):
remote: {:error, {:options, {:insufficient_crypto_support, {:"tlsv1.3", {:versions, [:"tlsv1.3", :"tlsv1.2"]}}}}}
       Compiling 44 files (.ex)
remote: warning: Error loading NIF (Is your operating system (x86_64-unknown-linux-gnu) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
remote: Failed to load NIF library: '/tmp/build/_build/prod/lib/appsignal/priv/appsignal_extension.so: cannot open shared object file: No such file or directory'
remote:   lib/appsignal/nif.ex:23: Appsignal.Nif.init/0
remote:   (kernel 7.3) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5
remote:
       Generated appsignal app
```

It does not stop the deployment. The application starts, but AppSignal does not work. I see that it logs the following errors on start:

```
...: web.1  | warning: Error loading NIF (Is your operating system (x86_64-unknown-linux-gnu) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
...: web.1  | Failed to load NIF library: '/app/lib/appsignal-2.2.7/priv/appsignal_extension.so: cannot open shared object file: No such file or directory'
...: web.1  |   anonymous fn/1 in :init.run_on_load_handlers/2
...: web.1  |
...: web.1  |   (appsignal 2.2.7) lib/appsignal/nif.ex:23: Appsignal.Nif.init/0
...: web.1  | 13:15:26.160 application=appsignal function=initialize/0 module=Appsignal [error] Failed to start AppSignal. Please run the diagnose task (https://docs.appsignal.com/elixir/command-line/diagnose.html) to debug your installation.
```

I'm using gigalixir-stack-18 which runs on Ubuntu 18.x. It works fine after rolling back to AppSignal 2.2.3 and AppSignal Phoenix 2.0.12.

**Comment by smt116** [comment]
Besides the bug introduced somewhere between 2.2.3 and 2.2.7, shouldn't it fail on compiling the package?

**Comment by tombruijn** [comment]
Hi @smt116, the installer is working as intended. If the install fails, we don't break the deploy. We don't want to break the entire application, worst case only the data reporting to AppSignal fails.

Can you send us a diagnose report from that gigalixir deploy to support@appsignal.com? https://docs.appsignal.com/elixir/command-line/diagnose.html
That way we have more information about what went wrong on which versions of Erlang and Elixir, along with the installation report with more data.

So far it looks like a download issue with the correct SSL options. We modified this recently in package version 2.2.5. Downgrading may help for now.

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700071647 (Private link)
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700071569 (Private link)

**Comment by hazen** [comment]
FWIW - It looks like we had the same problem because our OpenSSL did not support TLSv1.3.  Removing that as an option from the `mix_helpers.exs` got us unstuck.

**Comment by shairyar** [comment]
Thanks @hazen for sharing that information.
