### ISSUE TITLE
Telemetry dependency won't compile on OTP < 21

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#722]
The telemetry package depends on the, in OTP 21 introduced, logger module, which is not available on older versions.

Which would mean that we also don't support OTP < 21 at the moment.

Can we work around this by making telemetry an optional dependency and only test our integration if the package is present on OTP >= 21?

Issue found while debugging #718.

**Comment by tombruijn** [comment]
@jeffkreeftmeijer any thoughts? Can we make telemetry optional as I suggested?

**Comment by jeffkreeftmeijer** [comment]
We could. We’d then need to disable the Ecto integration and the Phoenix integration in appsignal-phoenix, both of which depend on `:telemetry`, on OTP < 21. It should throw a warning to ask users to upgrade.

**Comment by tombruijn** [comment]
> For Telemetry's case, @tombruijn mentioned making it an optional dependency. This should work -- I think we only use Telemetry to get SQL query events from Ecto, which does have Telemetry as a non-optional dependency, so Telemetry should be present whenever Ecto is present.

@unflxw mentioned the above on https://github.com/appsignal/appsignal-elixir/pull/718#issuecomment-971887907, so that would mean that Ecto support would also be absent on those OTP versions. Which I guess is better than a app that won't install. But let's see if we can reasonably try to make telemetry optional. And otherwise I see we have little choice but to bump the minimal supported OTP version.

**Comment by tombruijn** [comment]
Simply marking it as optional is apparently not enough. It will still install it in the CI build. See this build: https://appsignal.semaphoreci.com/workflows/4f727d3c-2334-4230-b59b-2b2561814127?pipeline_id=2fdf48fc-332c-4c56-b820-b0b707a797f7

**Comment by unflxw** [comment]
@tom I've found (somewhat accidentally, while trying to test the OTP < 20 implementation of the scheduler utilization metric) that setting the dependency to `~> 0.4` (as opposed to `~> 0.4 or ~> 1.0` _does_ install correctly. Would that be an acceptable solution/workaround?

**Comment by tombruijn** [comment]
@unflxw Great! I think that works. However, I'm getting failures on unrelated issues I think now.

Could be other issues related to OTP 20 we also need to resolve.

https://appsignal.semaphoreci.com/jobs/d7853144-3ca1-4017-8bf2-36c54f7511e0

But I'm also considering dropping OTP 20 if this takes a lot more time.

**Comment by unflxw** [comment]
I think we're close enough to getting it to work. I do agree that we should look into changing the language version support policy for Elixir/Erlang, but if we can fix this now, we get to make more realistic promises going forward (next major version?) without breaking our original one.

Of the failures I see in that CI run, the ones relating to the scheduler module and the Erlang probe are fixed [in this PR](https://github.com/appsignal/appsignal-elixir/pull/723). I'll have a look at the other two.

**Comment by jeffkreeftmeijer** [comment]
This one’s fixed as part of https://github.com/appsignal/appsignal-elixir/pull/724, and that’s now ready for review.

**Comment by tombruijn** [comment]
With PR #724 merged, I'm closing this.
