### ISSUE TITLE
Add absinthe support

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#751]
Support the [absinthe library](https://hex.pm/packages/absinthe).

## To do

- [ ] Research instrumentation method
  - Can we rely on the Elixir Telemetry package (not opentelemetry) to provide all the instrumentation we need?
  - Do we need to provide a new package for absinthe support like plug and phoenix: `appsignal-absinthe`?
- [ ] Document absinthe support on the docs page: https://docs.appsignal.com/elixir/integrations/
- [ ] Link to the integrations docs from the install guide: https://docs.appsignal.com/elixir/installation/
- [ ] Announce support on the blog

## Requests

- https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540709/conversations/22387046859
- https://github.com/appsignal/appsignal-elixir/issues/176#issuecomment-528653578
- https://github.com/appsignal/appsignal-elixir/issues/176#issuecomment-629040408
- https://github.com/appsignal/appsignal-elixir/issues/176#issuecomment-648228290
- https://github.com/appsignal/appsignal-elixir/issues/176#issuecomment-661798185
- https://github.com/appsignal/appsignal-elixir/issues/176#issuecomment-691489889
- https://github.com/appsignal/appsignal-elixir/issues/176#issuecomment-767544323
- https://github.com/appsignal/appsignal-elixir/issues/176#issuecomment-1018668629

**Comment by tombruijn** [comment]
Let's look at the opentelemetry integration viability first: https://github.com/appsignal/integration-guide/issues/47 (private issue)

**Comment by haizop** [comment]
@tombruijn Any update on this? AppSignal would be a lot more useful for my team if it worked properly for Absinthe.

**Comment by tombruijn** [comment]
@haizop so far no update. It's not on our immediate roadmap. If we were to implement something now to instrument Absinthe, we would not be able to instrument it fully. A feature like asynchronous field resolution would not be supported.

We hope to adopt OpenTelemetry in our Elixir integration, improve the async support, and write an Absinthe instrumentation if it doesn't exist at that time.

For now we recommend writing [your own instrumentation](https://docs.appsignal.com/elixir/instrumentation/instrumentation.html) so you have more control over how it gets instrumented.

I have previously written a page in our docs for some middleware that does basic support, but I hesitate to link it because it should not be considered a full integration. I don't even know if it would still work.
