### ISSUE TITLE
Check that the CA cert file exists and is readable on extension install

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-elixir#756]
As per [the integration guide](https://github.com/appsignal/integration-guide/blob/main/build/support-transmitter.md):
> - CA certificates file
>   - The AppSignal ca_file_path config option is configured. The configured path exists and is readable.
>   - If the configured path does not exist or is not readable, the language or http library default is used. A warning is logged when this happens.

~~The transmitter currently fails if the path does not exist or is not readable.~~ [The transmitter correctly checks whether the file exists and is readable](https://github.com/appsignal/appsignal-elixir/blob/a1d7d72fb5288dc2ef76d8adbd11c6e5acf3ea16/lib/appsignal/transmitter.ex#L16), but [the extension download in the mix helper does not use the transmitter, and it does not check for it](https://github.com/appsignal/appsignal-elixir/blob/243f0d20cb2c83ca47a32cd510abe03ebf071ebb/mix_helpers.exs#L259).

**Comment by tombruijn** [comment]
Let's look if this throws an error. If so, let's fix the error.

**Comment by luismiramirez** [comment]
If you change the cacert file path to some non-existent path, it fails and enters in a retry loop:

```
phoenix-example-app-1       | app: ==> appsignal
phoenix-example-app-1       | app: Downloading agent release
phoenix-example-app-1       | app: AppSignal installation failed: Could not download archive from any of our mirrors.
phoenix-example-app-1       | app: Please make sure your network allows access to any of these mirrors.
phoenix-example-app-1       | app: Attempted to download the archive from the following urls:
phoenix-example-app-1       | app: - URL: https://appsignal-agent-releases.global.ssl.fastly.net/15ee07b/appsignal-x86_64-linux-all-static.tar.gz
phoenix-example-app-1       | app: - Error (hackney response):
phoenix-example-app-1       | app: {:error, {:options, {:cacertfile, '/foo/bar/pepe.pem', {:error, :enoent}}}}
```

Working on the fix
