### ISSUE TITLE
Compilation fails when configured via `releases.exs` after upgrade

### ISSUE THREAD

**Issue by ckruse** [appsignal/appsignal-elixir#773]
After an update from 2.2.10 to 2.2.13 compilation fails when appsignal is configured via `releases.exs` with this error:

```
** (ArgumentError) could not fetch application environment :config for application :appsignal because configuration at :config was not set
    (elixir 1.13.0) lib/application.ex:683: Application.fetch_env!/2
    (appsignal 2.2.13) lib/appsignal/config.ex:389: Appsignal.Config.log_level/0
    (appsignal 2.2.13) lib/appsignal/logger.ex:30: Appsignal.Logger.log/3
    lib/termitool_web/endpoint.ex:4: (module)
```

It has been working before. I guess configuration seems to be a compile-time requirement now, is there a way to circumvent that?

**Comment by tombruijn** [comment]
Hi @ckruse, we will have a look at what might be broken. I think it may be related to our recent logger change https://github.com/appsignal/appsignal-elixir/commit/c325114aa6278d8b4f4cf9587cb288345f5c492f.

**Comment by ckruse** [comment]
To be honest, this is not that easy. I would have to deploy your beta code to prod…

**Comment by jeffkreeftmeijer** [comment]
Hey @ckruse, thanks again for reporting this. We’ve pushed version 2.2.14 of the AppSignal for Elixir integration, which includes a patch for this issue. Could you upgrade to that and let us know if you run into any more issues?

**Comment by ckruse** [comment]
Can confirm, it works now. Thanks for fixing!
