### ISSUE TITLE
Exception after upgrade to version 2.2.14

### ISSUE THREAD

**Issue by juanperi** [appsignal/appsignal-elixir#779]
## Describe the bug

I think there is an issue in the `config_change` function implementation.
The function `initialize`, called at https://github.com/appsignal/appsignal-elixir/blob/ab876253936838369654f11bbcd387a7c52c3994/lib/appsignal.ex#L57 does not always return `:ok`, and so i get the following exception:
```
MatchError: ** (MatchError) no match of right hand side value: nil
lib/appsignal.ex:57 in anonymous fn/0 in Appsignal.config_change/3
```
The elixir logger does return `:ok`, but some of the calls to the elixir logger have been changed to the Appsignal logger, which doesn't return `:ok`

For example at lines 
https://github.com/appsignal/appsignal-elixir/blob/ab876253936838369654f11bbcd387a7c52c3994/lib/appsignal.ex#L73 and https://github.com/appsignal/appsignal-elixir/blob/ab876253936838369654f11bbcd387a7c52c3994/lib/appsignal.ex#L75

- Using AppSignal for Elixir package version 2.2.14

**Comment by juanperi** [comment]
BTW, would this be the right way to start appsignal in my own supervision tree (using `runtime: false` for appsignal_phoenix)? that way I avoid the `config_change` call altogether
```
children =
  [
    %{id: Appsignal, start: {Appsignal, :start, [nil, nil]}},
    %{
      id: Appsignal.Phoenix.Application,
      start: {Appsignal.Phoenix.Application, :start, [nil, nil]}
    },
    App.Repo,
    ...
  ]
opts = ....
Supervisor.start_link(children, opts)
```

**Comment by jeffkreeftmeijer** [comment]
Hey @juanperi,

Thanks for reporting this! I’ve been looking at this, and I’ve added some fixes that should prevent this from happening in the future. To be extra sure we caught the issue, could you try starting your app on the https://github.com/appsignal/appsignal-elixir/tree/initialize-ok branch to see if that resolves the issue for you?

If so, we’ll go ahead and release this as patch version.

Thanks again!

**Comment by juanperi** [comment]
The issue seems to be fixed after trying your branch.

In any case, I think that calling config_change might not be the right thing to do in my case. 
I need to call it because the push api key comes from vault. Vault values are retrieved at runtime inside my application. Which means that I have the following workflow:
1. Start appsignal with invalid configuration -> warning is issued
2. Execute my Application startup
3. Bring values from Vault
4. Call config_change from appsignal
5. Start my application's supervision tree

In this setup, I'm thinking that I should make appsignal not start automatically (`runtime: false`) and start the supervision tree manually as part of my applications supervision tree. 
In that case, would the example in my previous comment be the right way of starting appsignal?

Thank you
