### ISSUE TITLE
Handle nil values in `set_sample_data/3`

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#787]
Much like https://github.com/appsignal/appsignal-elixir/commit/d66ad2d84192d4c6e5e20b489023f8c0264c7c56, if we allow nil values to be passed through `set_sample_data/3`, we could simplify the code we’re adding in https://github.com/appsignal/appsignal-elixir-phoenix/pull/47 (as described in https://github.com/appsignal/appsignal-elixir-phoenix/pull/47#pullrequestreview-1053941991), by using a single function clause.

This would entail returning the span instead of `nil` in [the rescue clause.](https://github.com/appsignal/appsignal-elixir/blob/main/lib/appsignal/span.ex#L225)

**Comment by tombruijn** [comment]
@jeffkreeftmeijer this was fixed in PR #788 right? Can this be closed?
