### ISSUE TITLE
Application is not compiling after update to 0.11.0

### ISSUE THREAD

**Issue by costaraphael** [appsignal/appsignal-elixir#80]
When I try to compile my application for the first time, the following error happens:
![image](https://cloud.githubusercontent.com/assets/7742817/22039300/1f95acae-dcd5-11e6-9352-b6e0dfde979e.png)

Looking at the source, I found that there is a new check at the top of `lib/appsignal/phoenix.ex`, that checks if Phoenix is present with `Code.ensure_loaded?/1`.

The problem is, when the appsignal application is compiled, phoenix is not compiled yet, which causes the check to return false.

A workaround to this is to compile phoenix first and then compile the rest of the dependencies: `mix do deps.compile plug, deps.compile phoenix, compile`.

I guess that there are better ways to check if phoenix is present (maybe using some mix functions?).

**Comment by arjan** [comment]
Hmm this is a clear oversight on our part. I thought i saw this method of compile-time checking in a different project as well, that's why we did it this way. I'll have a look to see if it can be done differently.

**Comment by arjan** [comment]
In your app, do you list the `:phoenix` dependency before `:appsignal`?

I got the idea of doing it like this from Ecto [see here](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/poison.ex#L1).

**Comment by costaraphael** [comment]
But Ecto uses poison as a optional dependency, [look](https://github.com/elixir-ecto/ecto/blob/master/mix.exs#L52).

Reordering my deps is kind of confusing, since I have an umbrella application where one app called `API` depends on phoenix and another app called `Core`. `Core` is the one that depends on appsignal.

**Comment by arjan** [comment]
Oh wait, maybe it has to do with the `only: :test_phoenix` clause in appsignal's phoenix dep.

**Comment by arjan** [comment]
Yes, that's it. Will release 0.11.1 tomorrow with a fix, thanks for the headsup.

**Comment by pdilyard** [comment]
Having the same issue, looking forward to the release

**Comment by jeroenvisser101** [comment]
Same issue here as well, is there anything that I can change to make it compile? Can I force AppSignal to build with Phoenix?
