### ISSUE TITLE
Logging backend

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-elixir#800]
Provide a [logging backend](https://hexdocs.pm/logger/Logger.html#module-backends) so users can send their app logs to AppSignal from the configured Logger(s). This will a manual addition to their app config. Not added automatically.

# TODO

- [x] Open pull request (#829)
- [ ] Open docs pull request

**Comment by thijsc** [comment]
Requested here: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/mentions/conversations/16410700147812

**Comment by shairyar** [comment]
Another customer waiting to test this
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700175149?view=List
