### ISSUE TITLE
Restore running CI on Elixir main 

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#815]
https://github.com/appsignal/appsignal-elixir/commit/63313291bc473f76064bfb36cc98fad8291548dc, https://github.com/appsignal/appsignal-elixir-plug/commit/b7b75829893827e020ca4610b5f4e53a0aec831e and https://github.com/appsignal/appsignal-elixir-phoenix/commit/b46d0da8a4b8b6afac3a19c29e29486b4ec712ee remove Elixir main from the appsignal-elixir, appsignal-elixir-plug and appsignal-elixir-phoenix build matrices to help fix the build. Once #811 has been completed, the tests need to run on the main branch again, so those commits need to be reverted and the failures need to be fixed.

**Comment by jeffkreeftmeijer** [comment]
I’m not sure what’s causing this yet. I’ve added a branch named [test-elixir-main](https://github.com/appsignal/appsignal-elixir/tree/test-elixir-main) which reverts 6331329 and [set up CI to run that branch once per day](https://appsignal.semaphoreci.com/branches/58023e02-8a86-46e9-8d32-e2e4b36147bf). That way, we know when this fixes itself.

**Comment by luismiramirez** [comment]
Spent some time trying to fix this by installing the `erlang-dev` and `erlang-src` with no success. It appears to be a current common issue as stated in the most recents comments of https://github.com/edgurgel/httpoison/issues/46

Let's icebox this one until the scheduled CI returns green.

**Comment by jeffkreeftmeijer** [comment]
Agreed. Moved to the backlog.
