### ISSUE TITLE
disable instrumentations changelog

### ISSUE THREAD

**Issue by mlineen** [appsignal/appsignal-elixir#824]
## Is this description correct in the changelog?

See https://github.com/appsignal/appsignal-elixir/blob/main/CHANGELOG.md?plain=1#L7-L9

Should it say *FALSE* instead?

Set `instrument_ecto`, `instrument_finch` or `instrument_oban` to `false` in order to disable that instrumentation.

**Comment by unflxw** [comment]
Hi @mlineen! You're right, the changelog entry is wrong. 🤦 It should be set to `false` in order to disable it. [The documentation](https://docs.appsignal.com/elixir/configuration/options.html#option-instrument_ecto) does describe it correctly.

**Comment by tombruijn** [comment]
- [ ] Update the CHANGELOG file.
