### ISSUE TITLE
`broken pipe` errors when upgrading from 2.3.0 -> 2.6.0.

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-elixir#839]
A customer has upgraded the integration from 2.3.0 to 2.6.0 and they are experiencing an issue where the log will output that it could not send metrics/data to the agent worker:

```
[xxx (agent) #32736][Error] Could not send host metrics to agent worker: NotifyError::Closed(..)
```

This coincides with `broken pipe` errors when sending data to our endpoint:

```
Some(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }
```

Quote from the customer:

> It works sometimes right after a deploy, and will run for a while, then this problem will surface and it will stop sending data.
Also in the past, I could usually kill the agent process if there was an issue, and it would happily restart. But that doesn't always work with this version.

I suspect the broken pipe errors are the root cause, backing up the agent worker processes (message is queued in the internal queue, that's blocked by the sender thread).

The customer has provided a full log in Intercom: https://app.intercom.com/a/inbox/yzor8gyw/inbox/conversation/16410700208249

**Comment by unflxw** [comment]
Slack conversation: https://appsignal.slack.com/archives/CNPP953E2/p1683095455969069

**Comment by tombruijn** [comment]
@unflxw or @matsimitsu what's the latest status of this issue?

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700210442?view=List (private link)

**Comment by tombruijn** [comment]
This issue was related to big payload sizes trying to be sent by the agent. Now that the underlying issue is fixed, can we close this issue? Assuming the broken pipe happened because of too big payloads being transmitted.

**Comment by jeffkreeftmeijer** [comment]
Closing because the underlying issue should be fixed. Please reopen if the issue persists.
