### ISSUE TITLE
What can be done about performance? Adding Appsignal instrumentation increases execution and reductions by nearly 3x

### ISSUE THREAD

**Issue by pejrich** [appsignal/appsignal-elixir#845]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

## Describe the bug
When adding Appsignal instrumentation to my app, via `@decorate transaction_event()` calls on functions, `:eprof` shows a rather large increase in reductions and execution time with Appsignal turned on.

Reduction difference 3.3x (2.4m wo AS | ~8m w AS)
Execution time difference 2.6x (0.66sec wo AS | 1.74sec w AS)

Here's `:eprof` with AppSignal, and underneath is without. I've tried to denote in the `with Appsignal` trace what the breakdown is on shared calls.

FYI the trace below is code that streams 1k lines from a file, and does some processing on each line of text(not a HUGE amount, but certainly a fair amount more than just some string split or trimming).

The legend for the character at the beginning of each line is as follows:

`M` = calls attributed solely to my app
`B` = calls that are split between both my app and Appsignal, i've tried  to denote on these how many calls my app makes when running the exact same function, without appsignal instrumenting. FYI the first number is my app without appsignal, the second number is with appsignal, and includes my apps calls too. So `658 vs   163158`, means appsignal is making 162,500 calls compared to my 658
`A` = calls attributed solely to Appsignal

```
...
M 'Elixir.String.Break':do_trim_trailing_l/1                             81250     0.47     8189  [      0.10]
M 'Elixir.Unicode.String.Segment':'-evaluate_rules/2-fun-0-'/3           92931     0.47     8241  [      0.09]
B erlang:whereis/1                                             658 vs   163158     0.48     8401  [      0.05]
M 'Elixir.Regex':'match?'/2                                             104483     0.50     8829  [      0.08]
A 'Elixir.Appsignal.Instrumentation':instrument/1                        40625     0.51     8892  [      0.22]
B ets:insert/2                                                    5 vs   40625     0.55     9663  [      0.24]
A 'Elixir.Appsignal.Config':'do_valid?'/1                                81250     0.57    10053  [      0.12]
B 'Elixir.String.Chars':'impl_for!'/1                         110 vs    121985     0.59    10341  [      0.08]
M 'Elixir.Unicode.String.Segment':evaluate_rule/2                        92931     0.60    10473  [      0.11]
A 'Elixir.Appsignal.Config':'valid?'/0                                   81250     0.60    10499  [      0.13]
A 'Elixir.Appsignal.Tracer':create_span/3                                40625     0.61    10614  [      0.26]
A 'Elixir.Appsignal.Tracer':lookup/1                                     81250     0.61    10744  [      0.13]
B 'Elixir.String.Chars':impl_for/1                             110 vs   121985     0.62    10835  [      0.09]
B 'Elixir.Keyword':get/3                                       44846 vs 126096     0.62    10924  [      0.09]
A 'Elixir.Appsignal.Nif':'_set_span_name'/2                              40625     0.67    11776  [      0.29]
M re:internal_run/4                                                      16879     0.68    11829  [      0.70]
B 'Elixir.String.Chars':to_string/1                             110 vs  121985     0.69    12046  [      0.10]
B application:get_env/3                                         20 vs   162500     0.78    13593  [      0.08]
A 'Elixir.Appsignal.Tracer':'running?'/0                                162500     0.78    13605  [      0.08]
B 'Elixir.Application':get_env/3                                0 vs    162500     0.82    14366  [      0.09]
B 'Elixir.Process':whereis/1                                   358 vs   162858     0.85    14790  [      0.09]
A 'Elixir.Appsignal.Nif':'_set_span_attribute_string'/3                  40625     0.87    15129  [      0.37]
M 'Elixir.Regex':version/0                                              115908     0.91    15875  [      0.14]
M 'Elixir.Regex':safe_run/3                                             115908     1.00    17513  [      0.15]
B erlang:send/2                                                   6 vs   40625     1.65    28820  [      0.71]
B application_controller:get_env/2                                5 vs  162500     2.60    45500  [      0.28]
A 'Elixir.Appsignal.Nif':'_create_child_span'/1                          20084     4.68    81913  [      4.08]
M re:run/3                                                              115908     5.11    89312  [      0.77]
A 'Elixir.Appsignal.Nif':'_create_root_span'/1                           20541     5.25    91802  [      4.47]
B ets:lookup/2                                                  200 vs  243950     5.46    95554  [      0.39]
A 'Elixir.Appsignal.Nif':'_close_span'/1                                 40625    10.16   177689  [      4.37]
M gen:do_call/4                                                            658    27.02   472452  [    718.01]
-------------------------------------------------------------------  -------  -------  -------  [----------]
Total:                                                               7949086  100.00%  1748640  [      0.22]
```

Below is the same trace as above, except with appsignal instrumentation commented out and recompiled before running. Both of these traces have been truncated, mostly because it gets very long, and the stuff above this point has quickly diminishing impact on the overall execution time.

```
...
unicode:characters_to_binary/2                                          4800     0.31    2067  [      0.43]
'Elixir.String':replace_guarded/4                                       4800     0.31    2080  [      0.43]
re:process_parameters/6                                                34675     0.33    2226  [      0.06]
lists:keyfind/3                                                        45148     0.35    2328  [      0.05]
'Elixir.Unicode.String.Break':split/3                                   7286     0.35    2371  [      0.33]
'Elixir.Regex':split/3                                                 11226     0.37    2480  [      0.22]
'Elixir.Enum':uniq_list/3                                              35880     0.37    2489  [      0.07]
'Elixir.MapSet':'member?'/2                                            24422     0.38    2524  [      0.10]
'Elixir.String.Unicode':downcase/3                                     38225     0.42    2811  [      0.07]
maps:fold/3                                                            22014     0.44    2958  [      0.13]
maps:next/1                                                            47636     0.45    3012  [      0.06]
binary:split/3                                                          4900     0.51    3379  [      0.69]
maps:fold_1/3                                                          44028     0.56    3758  [      0.09]
'Elixir.Keyword':get/3                                                 44846     0.60    4019  [      0.09]
'Elixir.Kernel':struct/3                                               44028     0.61    4063  [      0.09]
'Elixir.MyApp':do_xxx/2                                                 8895     0.72    4783  [      0.54]
'Elixir.Map':get/3                                                     38412     0.81    5384  [      0.14]
re:version/0                                                          115908     0.93    6234  [      0.05]
erlang:system_info/1                                                  115908     0.95    6369  [      0.05]
'Elixir.Enum':'-map/2-lists^map/1-0-'/2                                50440     1.09    7255  [      0.14]
'Elixir.Enumerable.List':reduce/3                                     100217     1.24    8278  [      0.08]
'Elixir.Unicode.String.Segment':'-evaluate_rules/2-fun-0-'/3           92931     1.25    8335  [      0.09]
'Elixir.Regex':'match?'/2                                             104483     1.30    8697  [      0.08]
ets:lookup/2                                                             200     1.42    9488  [     47.44]
'Elixir.Unicode.String.Segment':evaluate_rule/2                        92931     1.59   10623  [      0.11]
re:internal_run/4                                                      16879     1.89   12639  [      0.75]
'Elixir.Regex':version/0                                              115908     2.30   15392  [      0.13]
'Elixir.Regex':safe_run/3                                             115908     2.59   17319  [      0.15]
re:run/3                                                              115908    14.24   95200  [      0.82]
gen:do_call/4                                                            658    48.81  326207  [    495.76]
-------------------------------------------------------------------  -------  -------  ------  [----------]
Total:                                                               2383271  100.00%  668374  [      0.28]
```
Is there maybe something I'm doing wrong that would cause such a drastic increase? Currently all i'm doing is as follows:

```
defmodule SomeModule do
  use Appsignal.Instrumentation.Decorators

  @decorate transaction_event()
  def some_function(), do: :ok
end
```
Thanks!

One correction, I use the term `reduction` incorrectly above, what I really mean is function calls. `658` is the number of times `gen:do_call/4` is called, _not_ the number of reductions that `gen:do_call/4` consumed.

**Comment by jeffkreeftmeijer** [comment]
Hey Peter,

Thanks for raising this issue. I'm not sure why the reduction numbers in eprof are that high in your testing. The `instrument/0` function should be called once per instrumented function call, for example. I haven't had a chance to check this myself, but do you get the same results if you switch off the decorators and instument your functions [with the `instrument/0` function directly](https://docs.appsignal.com/elixir/instrumentation/instrumentation.html)?

Something we could definitely imrpove on here is the amount of defensive programming we do. We check if AppSignal is enabled whenever we try to write something to ets, to make sure users can update their configurations and have AppSignal pick that up immeditely. We could be a little more lenient there, to allow for some caching.

I'll get back to you on this after I've had time to do some testing with this, although I'm not exactly sure when that will be.

**Comment by jeffkreeftmeijer** [comment]
Hey Peter,

I'm looking into removing some of the checks that are no longer needed. The first step is removing a call to `Config.active?/0` in some of the span functions that is unneeded in https://github.com/appsignal/appsignal-elixir/tree/eprof. In my testing, that drops the number of calls to :ets.lookup/2 by about $2n$ when running eprof on a call to `Appsignal.Instrumentation.instrument/3`:

```
APPSIGNAL_PUSH_API_KEY=00000000-0000-0000-0000-00000000 APPSIGNAL_APP_NAME="appsignal-elixir" mix profile.eprof -e "(1..1_000) |> Enum.each(fn _ -> Appsignal.Instrumentation.instrument(\"name\", \"category\", fn -> :ok end) end)"
```

Note: If you'd like to reproduce this, be sure to pass an actual API key and app name to make sure the integration is active when running the benchmark.

I'd love to see the results from your benchmarking on the https://github.com/appsignal/appsignal-elixir/tree/eprof branch. Also, I'm still interested in seeing the results of using the `instrument/0` function instead of the decorators.

**Comment by jeffkreeftmeijer** [comment]
I pushed two other patches to lower the number of reductions some more:

1. 47dcbed55219ed1f1242cfa26bca8ecec9d6aac6 makes sure calling `Appsignal.Config.active?/0` only checks the configuration once, which saves another ets lookup. Previously, it fetched the configuration once for checking if the configuration is active, and another time for checking if the push key was valid.
2. efb9e2f5bda524f6f3966701c7ee6160f8cc8dbd removes an instance of the `running?/0` check, which was done before every insert. With this patch, the registry isn't checked, but any errors caused by the registry being down are handled.
