### ISSUE TITLE
CI performance regression with Erlang/OTP 26

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-elixir#859]
[Erlang/OTP 26 is being built from source](https://appsignal.semaphoreci.com/jobs/e6d7ea0c-2f25-4010-b4e6-dcd4a5283125#L566-L577) every time, on every job that uses it.

Some logic to [cache Elixir builds](https://github.com/appsignal/appsignal-elixir/blob/main/bin/setup) already exists. Perhaps the artifacts at `~/.kerl/` could be cached similarly to the ones at `~/.kiex/`.

Timebox: 1 day. We can live with the performance regression if not, as it only adds around two minutes to CI runs on average. It's also likely to be solved magically in the near future, as Semaphore will add Erlang/OTP 26 to their CDN eventually.

**Comment by tombruijn** [comment]
This will get automatically fixed in a month or two, when Semaphore does their monthly update thing.

> Timebox: 1 day.

It's only adding another path to cache, right? Takes an hour, maybe two, waiting for builds. That's something I'd be willing to do now.

**Comment by unflxw** [comment]
Go for it @tombruijn!

Depends on how friendly `kerl` artifacts are to being cached, and whether we can keep using `sem-version erlang` to get the versions that don't need building from source.

I recall that I found it useful, when doing the `kiex` caching, to look at what `sem-version` was doing under the hood. The scripts are up somewhere on Semaphore's GitHub.
