### ISSUE TITLE
AppSignal active configuration detection

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#86]
I found a difference in configuration between the AppSignal for Elixir package and the AppSignal for Ruby gem.

Related issue: #49 

## Ruby

In the Ruby gem we automatically set `active` to `true` once we detect the `APPSIGNAL_PUSH_API_KEY` in the environment.

This is the exception to the configuration order which allows us to install the Heroku add-on without setting the `APPSIGNAL_ACTIVE` environment key there. (It's too late to change that now.)

https://github.com/appsignal/appsignal-ruby/blob/0e97b6f9180c4504e4361021fafa6ec7da3e6d42/lib/appsignal/config.rb#L154-L155

## Elixir

In the Elixir package we automatically set `active` to `true` if the `push_api_key` configuration option is set in __any of the configuration stages__ (`app_config` and `env_config`) even when `active` is not explicitly set to `true`.

https://github.com/appsignal/appsignal-elixir/blob/f7fd3f7335130283f19beed335572a44b9f31419/lib/appsignal/config.ex#L37

## Suggested change

We should try to keep the two packages' configuration behave the same way.

We should add the `APPSIGNAL_PUSH_API_KEY` `active` detection to the `load_from_system` function in the Elixir package. This require users to configure `active` per environment.

```elixir
# config/config.exs
config :appsignal, :config,
  name: :appsignal_phoenix_example,
  push_api_key: "xxxx-xxxx-xxxx-xxx"
```

```elixir
# config/dev.exs
config :appsignal, :config,
  env: :development,
  active: false # Default value so it's not necessary to set this
```

```elixir
# config/prod.exs
config :appsignal, :config,
  env: :production,
  active: true
```

@jeffkreeftmeijer @arjan WDYT?
@thijsc We've discussed this behavior before for the Ruby gem, do you agree it should behave the same here?

~Sidenote: Can't we detect the `env` from `Mix.env` ? So it's not necessary to set?~ See #91.

**Comment by jeffkreeftmeijer** [comment]
I'm +1 on keeping the configuration the same in the Ruby and Elixir integrations, but I think I prefer having the :active option set to true by default. That way, we can turn Appsignal off for certain environments if needed, instead of explicitly turning it on. Why did we chose to do it the other way around for the Ruby version, @thijsc?

If we'd follow the Ruby way here (not activating the extension by default and having the user do so explicitly), we need to think of a good upgrade path for existing Elixir integration users.

**Comment by thijsc** [comment]
I don't really get what the issue is. In Ruby active will be set to true automatically if there is a push key. You can disable it manually later on if you like. What would the backwards incompatibility be, people currently already need a key anyway?

**Comment by thijsc** [comment]
Discussed with @tombruijn, this is indeed different from the Ruby version. I think we should keep the behaviour the same as in Ruby, otherwise providing support on this will be very confusing.

**Comment by tombruijn** [comment]
I'll change it then to match the Ruby gem setup. A guide will be in order for everyone that upgrades
