### ISSUE TITLE
Compilation fails after update to Elixir 1.15 and Erlang 26.0.1

### ISSUE THREAD

**Issue by hubertlepicki** [appsignal/appsignal-elixir#860]
I am using the following Docker image: `hexpm/elixir:1.15.0-erlang-26.0.1-debian-bullseye-20230522`

which is Elixir 1.15.0 and Erlang 26.0.1 on Debian. Appsignal is a dependency of the app, and at version 2.7.4.

There's an issue when compiling the app after upgrade from Elrang 1.14.3 and OTP 24 image:

```
==> appsignal
Downloading agent release

08:09:46.310 [notice] Application parse_trans exited: :stopped

08:09:46.313 [notice] Application syntax_tools exited: :stopped

08:09:46.313 [notice] Application certifi exited: :stopped

08:09:46.313 [notice] Application mimerl exited: :stopped

08:09:46.313 [notice] Application idna exited: :stopped

08:09:46.313 [notice] Application unicode_util_compat exited: :stopped
could not compile dependency :appsignal, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile appsignal --force", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 5.0.1) :ets.lookup_element(:hackney_config, :mod_metrics, 2)
    (hackney 1.18.1) /app/deps/hackney/src/hackney_metrics.erl:27: :hackney_metrics.get_engine/0
    (hackney 1.18.1) /app/deps/hackney/src/hackney_connect.erl:75: :hackney_connect.create_connection/5
    (hackney 1.18.1) /app/deps/hackney/src/hackney_connect.erl:44: :hackney_connect.connect/5
    (hackney 1.18.1) /app/deps/hackney/src/hackney.erl:335: :hackney.request/5
    mix_helpers.exs:234: Mix.Appsignal.Helper.do_download_file!/2
    mix_helpers.exs:204: anonymous fn/5 in Mix.Appsignal.Helper.do_download_file!/3
    (elixir 1.15.0) lib/enum.ex:4830: Enumerable.List.reduce/3
Error: building at STEP "RUN mix deps.compile": while running runtime: exit status 1
```

This also happened *once* in my dev machine running Fedora 36 with asfd-installed above versions of Erlang and Elixir, but it since went away and I can compile it just fine. It is happening consistently on the Docker image, however.

**Comment by hubertlepicki** [comment]
To reproduce the bug, follow these steps:

1. Create directory to host the example_app

`mkdir example_app && cd example_app`

2. Place `mix.exs` in there containing the following text:

```
defmodule App.MixProject do
  use Mix.Project

  def project do
    [
      app: :app,
      version: "0.1.0",
      elixir: "~> 1.14",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:appsignal, "~> 2.7.4"},
      {:ssl_verify_fun, "~> 1.1.6", manager: :rebar3, only: [:test], runtime: false, override: true}
    ]
  end
end
```

3. Place the following Dockerfile in the same directory

```
ARG ELIXIR_VERSION=1.15.0
ARG OTP_VERSION=26.0.1
ARG DEBIAN_VERSION=bullseye-20230522

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} as builder

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git curl ca-certificates wget libc6-dev \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

RUN update-ca-certificates

WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV="prod"

COPY mix.exs mix.exs

RUN mix deps.get --only $MIX_ENV
RUN mix deps.compile
```

4. Build Docker image:

```
docker build .
```

If you notice, the mix.exs file contains a workaround for compilation issues of `:ssl_verify_fun` recommended by @josevalim , and it may or may not be related - since it's part of the dependency tree for :hackney

**Comment by hubertlepicki** [comment]
OKAY please ignore me and this bug report, I figured it out.

The problem was in `mix.exs` on this line:

```
      {:ssl_verify_fun, "~> 1.1.6", manager: :rebar3, only: [:test], runtime: false, override: true}
```

It had `only: [:test]` which I blindly copied in and left there, removing this part fixes the issue.

**Comment by hubertlepicki** [comment]
@tombruijn thanks!

BTW: Did you folks consider getting rid of hackney dependency? It appears you use it to download Agent, and maybe there's a better way to do it now - either using the built in Erlang client (probably bad idea) or one of the lightweight pure Elixir clients such as Mint or Finch?

**Comment by josevalim** [comment]
If you are only downloading an agent, then using httpc is fine, as long as you use CAStore for certificates and configure the SSL stuff: https://github.com/livebook-dev/livebook/blob/main/lib/livebook/utils/http.ex#L1 - that's also how Phoenix downloads tailwind, esbuild, etc.

**Comment by tombruijn** [comment]
We're using Hackney to download the agent on package installation, validate the Push API key on installation and send a [diagnose report](https://docs.appsignal.com/elixir/command-line/diagnose.html) for support purposes.

Thanks for the livebook httpc example! We can try using that again.

I remember we tried using httpc before in PR #140, but ran into some issues figuring out how it worked.
