### ISSUE TITLE
How to filter out events programmatically?

### ISSUE THREAD

**Issue by thbar** [appsignal/appsignal-elixir#865]
We started integrating AppSignal in [our app](https://github.com/etalab/transport-site), but it turns out most of the events are generated by parts of the apps that we do not have interest in monitoring via an APM (https://github.com/etalab/transport-site/tree/master/apps/gbfs, https://github.com/etalab/transport-site/tree/master/apps/unlock), resulting in a large billing.

We tried removing AppSignal from the umbrella components for those parts (https://github.com/etalab/transport-site/pull/3275), but it is not enough to actually stop getting traces for Phoenix routes that match them, because all the HTTP traffic is handled in one router (https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/plugs/router.ex).

Is there a way to filter out or opt-in/opt-out on the generation of AppSignal events, in order to let us reduce the overall volume?

(maybe it is more a https://github.com/appsignal/appsignal-elixir-phoenix question, let me know if I should move this over there)

**Comment by unflxw** [comment]
Hi @thbar!

You can denylist specific routes that you're not interesting in monitoring [using the `ignore_actions` config option](https://docs.appsignal.com/guides/filter-data/ignore-actions.html#elixir). Use the name by which those actions show up in the AppSignal "Performance > Actions" view.

Let us know whether this answers your question!

**Comment by thbar** [comment]
Hi @unflxw!

It will work but only for a limited set of cases, because we have many of them. Is there a way to use regular expressions, or maybe a code block instead of a fixed list?

**Comment by thbar** [comment]
(also, one action name is reported as `GET /gbfs/*_`, I am unsure if the filtering will actually work for this or not!)

**Comment by unflxw** [comment]
> Is there a way to use regular expressions, or maybe a code block instead of a fixed list?

This does not currently exist out of the box, but I'm checking in with my colleagues for alternative solutions.

> @thbar `GET /gbfs/*_`

That _should_ be fine, but do let us know if it doesn't work!

**Comment by unflxw** [comment]
@thbar Here's a suggestion: in the code that handles those endpoints that you wish to ignore, [set the root span's namespace to a fixed value](https://hexdocs.pm/appsignal/Appsignal.Span.html#set_namespace/2) (for example, `"ignored"`), and then configure [the `ignore_namespaces` config option](https://docs.appsignal.com/guides/filter-data/ignore-namespaces.html#elixir) to ignore the `"ignored"` namespace.

Would that work for your use case?

**Comment by thbar** [comment]
@unflxw thanks for the quick feedback. I will try that out and see if this works, thank you!

**Comment by unflxw** [comment]
Perfect! Closing this for now, but feel free to re-open this (or reach out at support@appsignal.com) if this doesn't work for you.

Also, as a public transit and open data aficionado, I am really thankful for the project that you're working on. 🎉

**Comment by thbar** [comment]
@unflxw I have tried adding a Plug to change the namespace, but the queries still pop up as "web" on the other side. I believe the namespace is probably re-written by the AppSignal integration itself (but I could not dig into that further).

For reference, my plug (which I didn't add to our app for now since it does not work) is:

```elixir
defmodule TransportWeb.Plugs.AppSignalFilter do
  @moduledoc """
  An attempt to reduce the volume of events sent to AppSignal in order to keep a lower bill.

  This sets the namespace to a well-known "ignore" value, which must be added to the
  AppSignal `ignore_namespaces` config value.

  See: https://github.com/etalab/transport-site/issues/3274
  """

  def init(options), do: options
  require Logger

  def call(conn, _opts) do
    if function_exported?(Appsignal.Tracer, :root_span, 0) do
      if must_ignore?(conn) do
        Logger.info("Marking as ignore for AppSignal")

        Appsignal.Tracer.root_span()
        |> Appsignal.Span.set_namespace("ignore")
      end
    end

    conn
  end

  # this method allows us to filter programmatically as needed
  defp must_ignore?(conn) do
    conn.host =~ ~r/proxy/i or conn.request_path =~ ~r/\/gbfs/i
  end
end
```

I will try to move it further in the Plug pipeline, but I'm unsure if it will work or not.

**Comment by thbar** [comment]
(I cannot re-open although I would like to!)

**Comment by unflxw** [comment]
Hi again @thbar! Sorry to hear that didn't work. As you said, it might be that this is taking place before the integration has created the root span, and it needs to be moved further up the pipeline.

I have consulted with a colleague who might have more information on how to proceed. In the meantime, could you check the value of `Appsignal.Tracer.root_span()` at that point in the code? For example:

```elixir
def call(conn, _opts) do
  IO.puts(inspect(Appsignal.Tracer.root_span()))
  # ...
```

If it is `nil`, then the root span has not been created yet, and this code needs to be moved somewhere up the pipeline -- for example, to a Phoenix controller.

**Comment by thbar** [comment]
It is indeed `nil`, so this explains that. I will try to move the code further down the line.

**Comment by thbar** [comment]
My latest integration is a bit better. I must say it was a bit too involved for that type of things. Maybe having a more flexible way to achieve things (maybe a module name & function name in the config) could be nice, although the existing settings help already.

I think I have nailed it so far, thank you for your help.

**Comment by unflxw** [comment]
I'm glad that worked! I agree that it can be a bit too complicated to fine-tune. I will share your feedback with the team.
