### ISSUE TITLE
Long integers in parameters trigger errors in AppSignal NIF

### ISSUE THREAD

**Issue by jeroenvisser101** [appsignal/appsignal-elixir#88]
When having long integers inside parameters (in our case, keystrokes typed by a user on a phone) AppSignal's NIF throws a `(ArgumentError) argument error`.

### Backtrace
```(appsignal) Appsignal.Nif._data_set_integer("", "keystrokes", 112122121122111122222211122112122)
(elixir) lib/enum.ex:657: anonymous fn/3 in Enum.each/2
(stdlib) lists.erl:1262: :lists.foldl/3
(elixir) lib/enum.ex:656: Enum.each/2
(appsignal) lib/appsignal/utils/data_encoder.ex:16: Appsignal.Utils.DataEncoder.encode/1
(appsignal) lib/appsignal/transaction.ex:209: Appsignal.Transaction.set_sample_data/3
(appsignal) lib/appsignal/transaction.ex:378: Appsignal.Transaction.set_request_metadata/2
(appsignal) lib/appsignal/phoenix/plug.ex:23: anonymous fn/2 in Appsignal.Phoenix.Plug.call/2```

**Comment by tombruijn** [comment]
Hi @jeroenvisser101!

Thanks for reporting (again 😉 ). We've been searching and thinking of a good way to fix this. Right now our idea is to cast the values to string when they are too big, unless we can find of a better/supported way to save these large integer values.

We will try to fix this quickly

**Comment by jeroenvisser101** [comment]
Sounds like a good idea. Is it maybe possible to cast it to a string but then when you pass it into the rust part, it will serialize it to JSON and it converts it back to an integer?

**Comment by jeroenvisser101** [comment]
💯  🎉
