### ISSUE TITLE
Neon startup causes errors to be sent to AppSignal

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-elixir#888]
Intercom conversation: https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/5138541/conversation/16410700249575?view=List

When [Neon](https://neon.tech/) starts up, the run time throws a bunch of errors that are not relevant to track and are sent to AppSignal.

There are three detected types by the customer:

- Postgrex.Error
- DBConnection.ConnectionError
- MatchError

The first two are OK to ignore, but `MatchError` can happen in a bunch of different contexts, and might not be a good practice to ignore it completely.

One proposal is to allow customers to ignore errors also by their content. It'd also be good to create a test-setup using Neon to see if we can build a specific solution for this.

## To do

- [ ] Look if the error is reported by a controller action or by the [catch-all error logger](https://github.com/appsignal/appsignal-elixir/blob/cc526cb63bb4894cd1e6c2e67f9b0f0fee2b5271/lib/appsignal/error/backend.ex). If it's the error logger, they can disable that.
  - It's unlikely we're going to add a dynamic error filtering system that looks at the error message, because it's indistinguishable from a normal can't connect to the database error.

**Comment by jeffkreeftmeijer** [comment]
[Asked](https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/540654/conversation/16410700249575#part_id=comment-16410700249575-21909537744) the customer to disable the fallback error logger:

> I _think_ this error is reported by our fallback error logger, which is what I'd like to check. This logger was introduced before we had other ways of catching errors in applications, and we're slowly phasing it out. I think it'll be off by default in AppSignal for Elixir 3.0.
>
> If that MatchError comes from that error logger, we should be able to get rid of if by disabling the error logger altogether. That'd mean we'd only get errors reported through :telemetry, but that should be fine in most cases.

> Could you set `enable_error_backend` to false in your configuration to see if that stops reporting `MatchError`s?

We're waiting for them to respond. Let's give them some time, then remind them. If they don't get back to us, I think we can close this issue.

**Comment by unflxw** [comment]
The customer seems to be satisfied with setting `enable_error_backend` to `false`. Closing.
