### ISSUE TITLE
Don't crash the compilation on unsupported OS'es

### ISSUE THREAD

**Issue by arjan** [appsignal/appsignal-elixir#89]
Currently the compilation fails when trying to compile Appsignal e.g. on windows (see #36). It would be nicer if the NIF compilation would just be skipped and a big red warning printed that Appsignal is not supported on the platform.

cc @nulian

**Comment by jeffkreeftmeijer** [comment]
Fixed in #93.

**Comment by arjan** [comment]
@nulian would you be so kind to test this on your windows machine? :)
