### ISSUE TITLE
Expose a way to clone the Tracer stack for a process

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-elixir#895]
Currently, the Ash integration [replicates part of our `Appsignal.Tracer` internals](https://github.com/ash-project/ash_appsignal/blob/2734fa4e211936b5cad615087909698f20647362/lib/ash_appsignal.ex#L89-L105) in order to turn the current span of an existing process into the current span to a newly spanned process. This works for Ash's needs at the moment, but it wouldn't work if they needed to, say, write something to the root span.

(Also, it shouldn't be necessary to understand our internals for this to work)

We should provide some way to "clone" the whole "span stack" for a given process to another process. A possible way to do this that comes to mind is something like `Appsignal.Tracer.clone(old_pid)`, which would be called from a newly spawned process, to copy the current span stack for the `old_pid` process ID in the ETS table, to be the span stack of the caller process.

@zachdaniel We would appreciate any and all feedback on what an useful API for doing this would look like! 🤩

**Comment by tombruijn** [comment]
Added in #898. Closing.
