### ISSUE TITLE
Detect the :env from Mix.env

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#91]
Extracted from #86:

> Sidenote: Can't we detect the env from Mix.env ? So it's not necessary to set?

In the Ruby integration, we automatically detect the env from Rails, Padrino and Sinatra applications. For Elixir applications, we can default to the `Mix.env`.

WDYT @thijsc, @tombruijn?

Related: #49.

**Comment by arjan** [comment]
I've already researched this a few months back, and this is not possible, `Mix.env` is not available at runtime.

And when compiling a dependent library (like Appsignal itself) from another project, `Mix.env` is always `:prod`, so the Appsignal code (e.g. `config.ex` cannot really use `Mix.env` at its compiletime to set the default env.

**Comment by jeffkreeftmeijer** [comment]
Thanks, I'll close this one, then. :)
