### ISSUE TITLE
Memory leak when running long, work intensive Oban background job

### ISSUE THREAD

**Issue by michallepicki** [appsignal/appsignal-elixir#913]
## Describe the bug

When running a long and very work-intensive Oban job, the VM memory grows steadily indicating a memory leak. This memory usage is not showing up in Phoenix LiveDashboard's Erlang memory usage for this process or other Erlang memory metrics visible there (it could be NIFs or something else?).

Additionally, when canceling the Oban job, this memory is not freed, and the process memory usage stays high (we restart our app to reclaim the memory for the OS)

## To Reproduce

Run a Oban job which runs long Ecto database transactions from a Repo.stream with ~1 million of rows returned, additional Ecto queries per each row, massaging data and saving streaming it to a CSV file. To get a sense of the scale, for us this job takes ~20 minutes on a fast MacBook or ~40 minutes on a busy server, probably most of the time is spent running additional queries per each row

- Using AppSignal for Elixir package version 2.8.0
- In my app using framework/library Oban version 2.17.1 , oban_pro 1.2.2
- With default Oban instrumentation, so `instrument_oban` not configuration to anything, meaning it is set to `true` (default value)
- In code looking something like this:

```elixir
defmodule Worker do
  use Oban.Worker

  def perform(%Oban.Job{args: args}) do
    try do
      # the real job does this a few times with different parameters, creating a few different CSV files,
      # and also is zipping them, uploading somewhere and sending an email, but I think the "leak" is probably
      # caused by this part
      
      stream = Repo.stream(some_query(args))
      file = File.stream!("filename.csv", [:write, :utf8])
      {:ok, _} =
        Repo.transaction(
          fn ->
            stream
            |> Stream.flat_map(&generate_row/1)
            |> CSV.encode(headers: ["some", "30", "headers"])
          end,
          timeout: :infinity
        )
    rescue
      e -> 
        # ... some additional logging and cleanup
        reraise(e, __STACKTRACE__)
    end
    # ...
  end

  defp generate_row(data) do
    # some calculations, additional database queries
    %{
      "some" => values
    }
  end
end
```

**Comment by michallepicki** [comment]
This is on current Elixir (1.16.0) and Erlang (26.2.1)

**Comment by michallepicki** [comment]
The memory leak still happens if I try to ignore the worker with `ignore_actions: ["Worker#perform"]`

**Comment by unflxw** [comment]
Hi @michallepicki!

Ignoring through the `ignore_actions` configuration option takes place "after the fact" -- the action is instrumented, _then_ ignored. So it makes sense that the configuration option wouldn't help.

I believe the issue might lie in all those millions of Ecto queries being instrumented. Could you try running this job with the `instrument_ecto: false` configuration option, and seeing if the issue persists?

If that does fix the issue, adding `Appsignal.Tracer.ignore()` at the top of the Oban worker's `perform` method should also fix it, without removing Ecto instrumentation for the rest of the application.

**Comment by michallepicki** [comment]
Hi @unflxw 

> I believe the issue might lie in all those millions of Ecto queries being instrumented. Could you try running this job with the instrument_ecto: false configuration option, and seeing if the issue persists?

There's no memory leak when using the `instrument_ecto: false` configuration

> If that does fix the issue, adding Appsignal.Tracer.ignore() at the top of the Oban worker's perform method should also fix it, without removing Ecto instrumentation for the rest of the application.

Thank you, this is a good workaround for us for now

**Comment by michallepicki** [comment]
Sorry, I don't understand why you closed the issue? I think this is a valid usage of Oban and Ecto, and I'm surprised that it's leaking memory (this is a big background job, but ideally we'd like to have the job instrumented anyway)

**Comment by michallepicki** [comment]
And there's a second slightly overlapping issue here as well, that canceling an Oban job is not handled properly and the VM is stuck at high memory usage

**Comment by michallepicki** [comment]
Thank you for writing this up, I hope future improvements will make it possible to use Appsignal for instrumenting batch jobs that perform a large amount of operations. I imagine more state would need to be tracked on your servers, but it may be worth it. In the meantime, do you think there could be some warnings added to the Elixir Appsignal documentation about this, mentioning the `Appsignal.Tracer.ignore()` workaround? Or maybe this behavior is documented somewhere already and I missed it?

**Comment by michallepicki** [comment]
Or maybe a better Appsignal behavior would be to detect an unusually high amount of spans under a root trace, and log a warning or error when it happens, and stop adding more after that to avoid crashing the server 🤔
