### ISSUE TITLE
Automatic application name detection

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#92]
In the Ruby integration, we automatically detect the application name from Rails applications. In Elixir projects, we should be able to default to `Mix.Project.config[:app]` as the project name.

WDYT @arjan, @tombruijn?

Related: #49.

**Comment by arjan** [comment]
Relates to #91 as well; `Mix` functions are not usable in runtime. However what you could do is update the instructions to let people put the following in the project's `config.exs`:

```
config :appsignal, :config,
  name: Mix.Project.config[:app],
  env: Mix.env
```

(untested, but should work)
