### ISSUE TITLE
`Logger.error` does not log AppSignal Error

### ISSUE THREAD

**Issue by PJUllrich** [appsignal/appsignal-elixir#923]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

## Describe the bug

Hey folks, I added all AppSignal loggers as recommended in the docs [base](https://docs.appsignal.com/elixir/installation.html),  [phoenix](https://docs.appsignal.com/elixir/integrations/phoenix.html), and [logs](https://docs.appsignal.com/logging/platforms/integrations/elixir.html) to my Phoenix Application, but whenever I call `Logger.error/1` it doesn't create an Error in AppSignal. The error shows in the logs and it's classified as `error`, but the message doesn't show under the `AppSignal -> Errors -> Issue List`. Only exceptions shows in that list.

I found this https://github.com/appsignal/appsignal-elixir/issues/172 very old issue where you decided to not add the AppSignal Logger backend, but that was 7 years ago and now you have a logger. So, may I ask whether a call to `Logger.error/1` should or shouldn't appear as an error in AppSignal? :D

## To Reproduce

Versions:

```
appsignal: 2.8.3
appsignal_phoenix: 2.3.5
appsignal_plug: 2.0.15
phoenix: 1.7.11
phoenix_live_view: 0.20.9
elixir: 1.16.1
erlang: 26.2.2
```

Code:

### Application
```elixir
# application.ex

defmodule App.Application do
   use Application

  @impl true
  def start(_type, _args) do
    # Will remove this soon
    Logger.add_backend(Sentry.LoggerBackend)
    Oban.Telemetry.attach_default_logger()
    # Same as this (Sentry Logger for Oban)
    App.Workers.ErrorReporter.attach()

    # AppSignal Loggers
    Appsignal.Logger.Handler.add("phoenix")
    Appsignal.Phoenix.LiveView.attach()

    children = [
      # Start the Telemetry supervisor
      AppWeb.Telemetry,
      # Start the HTTP Cache
      {Cachex, name: :http},
      # Start the Ecto repositories
      App.Repo,
      # Start the PubSub system
      {Phoenix.PubSub, name: App.PubSub},
      # Connect to the DNS Cluster
      {DNSCluster, query: Application.get_env(:app, :dns_cluster_query) || :ignore},
      # Start the Background Jobs
      {Oban, Application.fetch_env!(:app, Oban)},
      # Start the Endpoint (http/https)
      AppWeb.Endpoint
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: App.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    AppWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end
```

### Config
```elixir
# config/appsignal.exs

import Config

{_rest, revision} = System.get_env("FLY_IMAGE_REF") |> String.split_at(-8)

config :appsignal, :config,
  active: true,
  revision: revision,
  otp_app: :app,
  name: "app",
  push_api_key: "my-api-key",
  env: :prod
```

**Comment by jeffkreeftmeijer** [comment]
Hey @PJUllrich,

Printing an error to the log produces an error log line, while raising an exception crashes your process and produces an error in AppSignal's error list. We've experimented with turning error log lines into exceptions in the past, but we've chosen to keep those as two separate ideas as we think sending an actual error is more useful.

For your use case, using [`Appsignal.send_error/3`](https://docs.appsignal.com/elixir/instrumentation/exception-handling.html#appsignalsend_error3) should be your best bet. Aside from logging the message, this will also allow you to add contextual information. Would that work for your use case?

**Comment by PJUllrich** [comment]
Hey @jeffkreeftmeijer thank you for the info. That helps. I just wanted to clarify/ask whether I should expect to see my logged errors in the Error List or not. I wasn't 100% sure that my setup was correct. So, thanks for clarifying. I can use the `send_error/3` function, no problem 👍
