### ISSUE TITLE
Clickable stack traces to directly jump into the source

### ISSUE THREAD

**Issue by ouven** [appsignal/appsignal-elixir#924]
## Describe the feature

As a small convenience upgrade, it would be nice if I could configure a template for code links. Like Plug does:

```
PLUG_EDITOR=vscode://file/__FILE__:__LINE__
```

So I can directly click the stack trace and jump into my code editor.

**Comment by luismiramirez** [comment]
Hi @ouven!

I think you can achieve what you want by setting up the backtrace links in your app settings.

https://docs.appsignal.com/application/backtrace-links.html#configure-the-repo-url
