### ISSUE TITLE
Automatic :running_in_container detection

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-elixir#94]
We're currently setting :running_in_container to true if we detect the application running on Heroku (https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal/config.ex#L101). In the Ruby integration, we also set the :running_in_container option on non-Heroku containers: https://github.com/appsignal/appsignal-ruby/blob/master/lib/appsignal/system.rb#L4

**Comment by tombruijn** [comment]
See also https://github.com/appsignal/appsignal-agent/issues/212 about moving the container detection to the agent
