### ISSUE TITLE
LiveComponents shown in "background" namespace

### ISSUE THREAD

**Issue by lunks** [appsignal/appsignal-elixir#940]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

## Describe the bug

I have an error in AppSignal related to a LiveComponent that I expected to be in either "web" or "live_view", but it is in "background"

## To Reproduce

Create a LiveComponent and have it error out. The error is being reported as `background` when it should be `live_view`

- Using AppSignal for Elixir package version 2.9.2, Appsignal Phoenix 2.3.5
- In my app using framework/library ... version Elixir 1.16, Phoenix 1.7.12

- In this code:

We define our live component in `lib/app_web.ex`:

```elixir
  def live_component do
    quote do
      use Phoenix.LiveComponent

      unquote(view_helpers())
    end
  end
```

**Comment by tombruijn** [comment]
Hi @lunks, it sounds like it's reported by our error handler backend which is a last resort to report errors, which is why it's using the "background" namespace.

Can you check if you've added the [AppSignal Phoenix LiveView telemetry](https://docs.appsignal.com/elixir/integrations/phoenix.html#liveview)?

**Comment by tombruijn** [comment]
We also have a branch in the works that should add support for livecomponent you can try out here: https://github.com/appsignal/appsignal-elixir-phoenix/pull/84

**Comment by tombruijn** [comment]
Closing. Let us know if attaching the [AppSignal Phoenix LiveView telemetry](https://docs.appsignal.com/elixir/integrations/phoenix.html#liveview) did not help.
